oamg/convert2rhel

packaging/epel/convert2rhel.spec
- even though convert2rhel is able to convert ppc64 CentOS 7, EPEL koji does not allow building packages for ppc64:
https://fedoraproject.org/wiki/EPEL:Packaging#Limited_Arch_Packages
- it would make sense to make the package a true noarch package with the data for all arches/vendors/major versions included (TBD)
=> Limit EPEL to x86_64

setup.py
The description is a bit weird and does not exactly describe what
this tool does. This is an attempt to better describe what it does.
Also, adjust the license name to match what the code actually says it
is: GPLv3+.
Additionally, this script installs stuff that should not be installed
because of its usage of `find_packages()`. Since there's only one
actual package that needs to be installed, we just list it now.
=> setuptools: Fix description, license tag, and install package entries

.copr/Makefile, packaging/epel/create_epel_srpm.sh
- `--orig-release`: suitable for example for Koji builds
- the changed release with timestamp and git branch is suitable for CD
=> Add option for srpm build with unchanged release

convert2rhel/toolopts.py
- the variant option has no meaning if used with --disable-submgr option
- it is supposed to be used when converting with subscription-manager
=> help/man: variant option for submgr only

packaging/epel/create_epel_srpm.sh
- there was 'HEAD' instead of 'master' when built from the master branch
in https://copr.fedorainfracloud.org/coprs/g/oamg/convert2rhel/builds/
=> Fix names of copr builds

convert2rhel/main.py, convert2rhel/utils.py
Related: https://github.com/oamg/convert2rhel/pull/11
=> Return 0 on help message

run_system_tests.sh
- to describe how to make system tests work
- to not run system tests on CentOS 5 vagrant box for the lack of public copr builds for it
=> Update system tests script

packaging/centos_ol/convert2rhel.spec, packaging/epel/convert2rhel.spec
- also apply the EPEL spec fixes from https://github.com/oamg/convert2rhel/pull/7 to the CentOS/OL spec
=> Add missing dependecies to spec files

convert2rhel/data/7/x86_64/configs/centos-7-x86_64.cfg
- it causes a transaction failure during the conversion to RHEL7
https://bugzilla.redhat.com/show_bug.cgi?id=1798226
=> Blacklist kmod-kvdo on CentOS7

packaging/centos_ol/convert2rhel.spec, packaging/epel/convert2rhel.spec, setup.py
- fixed rpm dependencies
- blacklisted kmod-kvdo causing a transaction failure on CentOS 7
- convert2rhel exits with 0 on a help message
- added packit configuration for Copr builds and unit testing on a PR
Resolves: OAMG-3165
=> Bump version to 0.10

.packit.yaml
For the downstream release proposal, packit configuration requires dist_git_branches instead of dist-git-branch: https://packit.dev/docs/configuration/#packit-service-jobs
The incorrect key most probably caused that the proposal https://src.fedoraproject.org/rpms/convert2rhel/pull-request/1# has targeted Fedora rawhide instead of EPEL.
=> Fix packit conf on proposing a downstream release

packaging/centos_ol/convert2rhel.spec, packaging/epel/convert2rhel.spec, setup.py
- updated license in spec files from GPLv3 to GPLv3+
- set up automated pylint and unit test coverage checks in GitHub
- removed packit smoke test
- fixed packit configuration for downstream release proposals
Resolves: https://github.com/oamg/convert2rhel/issues/42
=> Bump version to 0.11

.github/workflows/pylint.yml, .pylintrc
pylint check on our CI doesn't use the `.pylintrc` configuration file.
These commit fix that
=> Fix CI pylint check

packaging/epel/create_epel_srpm.sh
- to make sure the master branch is installed instead of
PR-related builds from copr with cmd `yum install convert2rhel`
- using this script is temporary until the following packit issues are
dealt with:
https://github.com/packit-service/packit/issues/761
https://github.com/packit-service/packit-service/issues/239
- similar: https://github.com/oamg/leapp-repository/pull/327
=> Fix copr release for master branch

.gitignore, convert2rhel/toolopts.py, convert2rhel/unit_tests/toolopts_test.py
If `--enablerepo` is empty when providing `--disable-submgr`, the tool will fail to function correctly and go past point of no recovery. This PR fixes that by requiring `--enablerepo` if `--disable-submgr` is given
Few more things:
* `--disablerepo` defaults to `*` if `--disable-submgr` is given
* Added `.vscode/` dir to `.gitignore`
It passes the new tests, but I've not tested it manually
=> Fix: Require --enablerepo with --disable-submgr

convert2rhel/cert.py, convert2rhel/logger.py, convert2rhel/main.py, convert2rhel/pkghandler.py, convert2rhel/redhatrelease.py, convert2rhel/repo.py, convert2rhel/rhelvariant.py, convert2rhel/subscription.py, convert2rhel/systeminfo.py, convert2rhel/toolopts.py, convert2rhel/unit_tests/__init__.py, convert2rhel/unit_tests/cert_test.py, convert2rhel/unit_tests/logger_test.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/other_test.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/redhatrelease_test.py, convert2rhel/unit_tests/systeminfo_test.py, convert2rhel/utils.py
As discussed in https://github.com/oamg/convert2rhel/pull/50#issuecomment-631512340
Disabled pylint checks for the:
```
[C0103 invalid-name] Constant name "tool_opts" doesn't conform to UPPER_CASE naming style File: convert2rhel/toolopts.py, line 226, in print_non_interactive_opts
[C0103 invalid-name] Constant name "tool_opts" doesn't conform to UPPER_CASE naming style File: convert2rhel/toolopts.py, line 255, in 
[C0103 invalid-name] Constant name "system_info" doesn't conform to UPPER_CASE naming style File: convert2rhel/systeminfo.py, line 161, in 
```
by adding comment `# pylint: disable=invalid-name  # noqa`
=> Pylint fix warnings: [C0103 invalid-name]

convert2rhel/main.py, convert2rhel/redhatrelease.py, convert2rhel/utils.py
- these objects are not constants but mutable objects
- the change being reverted has been done under https://github.com/oamg/convert2rhel/pull/54
Sorry, @sturivny, I missed three other globals that shouldn't be considered constants.
=> Revert renaming global variables as constants

convert2rhel/pkghandler.py, convert2rhel/repo.py, convert2rhel/toolopts.py, convert2rhel/unit_tests/__init__.py, convert2rhel/unit_tests/cert_test.py, convert2rhel/unit_tests/example_test.py, convert2rhel/unit_tests/logger_test.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/subscription_test.py, convert2rhel/unit_tests/systeminfo_test.py, convert2rhel/unit_tests/toolopts_test.py, convert2rhel/unit_tests/utils_test.py
[C0326 bad-whitespace] No space allowed around keyword argument assignment
[C0411 wrong-import-order] standard import
[C0330 bad-continuation] Wrong continued indentation
=> Pylint fix bad-whitespace, wrong-import-order, bad-continuation

convert2rhel/logger.py, convert2rhel/unit_tests/logger_test.py, convert2rhel/utils.py
Now debug info is stored inside log file, whatever the user use or not
`--debug` argument.
Fixed when user not pass `--debug` information, the info was passed to
stdout, now these info only passed to the stdout if user add the debug
argument.
=> Always log debug info to the log file

convert2rhel/pkghandler.py, convert2rhel/unit_tests/pkghandler_test.py
There's no need for it since that phase is already past the point of no return, so the backup wouldn't be used for a rollback anyway.
=> Do not backup original kernel pkgs

.packit.yaml
The packit team has added the new "commit" trigger so now we can have copr builds created after each merge to master.
Unfortunately, it's not possible to have multiple triggers for one job (https://github.com/packit-service/packit-service/issues/647).
Related: https://github.com/packit-service/packit-service/issues/239
=> Let packit create copr builds on merges to master

packaging/centos_ol/convert2rhel.spec, packaging/epel/convert2rhel.spec
- It was accidentally removed with https://github.com/oamg/convert2rhel/pull/19
=> Return the setuptools dependency on CentOS/OL 6

convert2rhel/systeminfo.py, convert2rhel/unit_tests/other_test.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/utils.py, packaging/centos_ol/convert2rhel.spec, packaging/epel/convert2rhel.spec
- to let convert2rhel rpm to be its owner
- use /var/lib/convert2rhel instead of /tmp/convert2rhel as the latter
is cleared upon booting
=> Create the temp dir in spec

convert2rhel/subscription.py, convert2rhel/unit_tests/subscription_test.py
- To have the log message consistent with the other rollback msgs
- Before:
```
[06/15/2020 20:14:57] TASK - [Rollback: Rollback all non-Red Hat .repo files renamed in /etc/yum.repos.d/] 
No .repo files to rollback
Unregistering the system from RHSM ...
WARNING - subscription-manager not installed, skipping
[06/15/2020 20:14:57] TASK - [Rollback: Removing installed packages] ****************************
```
- After:
```
[06/15/2020 20:14:57] TASK - [Rollback: Rollback all non-Red Hat .repo files renamed in /etc/yum.repos.d/] 
No .repo files to rollback
[06/15/2020 20:14:57] TASK - [Rollback: Unregistering the system from RHSM] *******************
WARNING - subscription-manager not installed, skipping
[06/15/2020 20:14:57] TASK - [Rollback: Removing installed packages] …
```
=> Improve logging of the system unregistration

convert2rhel/pkghandler.py, convert2rhel/unit_tests/pkghandler_test.py
If there is no RHEL kernel, the convert process will halt with CRITICAL message.
=> Add check RHEL kernel

Makefile, convert2rhel/subscription.py, convert2rhel/unit_tests/subscription_test.py
The output of `subscription-manager list --available` has changed [1] and due to that the convert2rhel was unable to list any available subscription.
[1] Specifically the output of `subscription-manager list --available` where the `System Type:` changed to `Entitlement Type:`. The change happened probably between RHEL 7.7 and 7.8. Now the code is able to parse both the old and new output.
Resolves: OAMG-3337
=> Fix parsing RHSM output

convert2rhel/logger.py
Logfile is always overwritten for each execution instead of appended.
This PR fix that, adding appended argument for logging.FileHandler
=> fix: Logfile is overwritten instead of appended

convert2rhel/main.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py
Currently logging is instantiated before utils.require_root() is called which throws a permissions exception.  This PR fix these bug throwing a error message and exiting with code 1, before initialization process started.
=> Fix: throws message when not running as root

convert2rhel/logger.py
Fixes #79 
Python by default exits as 1 if you input a string:
```bash
$ python -c "import sys; sys.exit('testing')"; echo $?
testing
1
```
=> fix: critical logging exit with message

.packit.yaml
With this change, every build of c2r in the master branch will start with release number 2 which should make it higher than all the PR builds.
https://github.com/TomasTomecek/convert2rhel/commit/0c39103eee70c88e2d43f6df6209f7b803cbdf41
https://prod.packit.dev/copr-build/54592
https://copr.fedorainfracloud.org/coprs/packit/TomasTomecek-convert2rhel-master/build/1541479/
=> packit: bump release for builds in master branch

convert2rhel/subscription.py, convert2rhel/unit_tests/subscription_test.py
Subscriptions attached to an activation key are ignored and the script stops to prompt for a subscription, despite the fact that one  as already been attached, This PR fix that.
=> Fix: Subscriptions attached to a Sat6 activation key ignored

.packit.yaml
For copr build from packit, use the version from the spec file instead of from the latest git tag (which is the packit default).
Up until now, the copr builds created by packit had their version based on the convert2rhel tags (https://github.com/oamg/convert2rhel/tags), which caused them to have NEVR like:
`convert2rhel-v0.11-1.20200804110826746138.pr82.84.gb821881.fc31`
The `v` is the problem here.
After this change, the version should be taken from the `packaging/epel/convert2rhel.spec` file, causing the NEVR be like:
`convert2rhel-0.11-1.20200804110826746138.pr82.84.gb821881.fc31`
=> Copr build version from spec

packaging/centos_ol/convert2rhel.spec, packaging/epel/convert2rhel.spec, setup.py
Changes in the new version include:
- Fixes:
- require --enablerepo with --disable-submgr (#45)
- fix failing conversions if gpgcheck=1 not in used custom repos (#31)
- add missing python-setuptools dependency on RHEL 6 to a spec file (#73)
- fix parsing RHSM output due to its change in RHEL 7.8 (#72)
- fix stopping the convert2rhel execution when not running as root (#81)
- do not traceback when intentionally stopping the conversion (#87)
- do not ask for subscription SKU pool IDs when activation key is used (#91)
- Enhancements:
- always logging debug info to the log file (#41)
- unnecessary backup of kernel packages is not being performed (#61)
- unregister from RHN Classic if in use (#47)
- change a temporary folder path from /tmp/convert2rhel/ to /var/lib/convert2rhel (#74)
- add the …
=> Bump version to 0.12

convert2rhel/main.py
When using custom repos instead of RHSM, checking for expected repoids and warning when they're not available is confusing to customers as they fear something is wrong.
Related: OAMG-3144
=> Do not check repoids with disabled RHSM

convert2rhel/main.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py
Some regexp are hardcoded in English, the locale must be set to LANG=C before running the tool.
=> fix:English locale before all c2r process

convert2rhel/redhatrelease.py
The function was more complicated that necessary. The reason is that when the tool supported conversions to RHEL 5, at that system the system release file had a different name. Support for RHEL 5 has been dropped and on RHEL 6+ (and its derivatives_ the path is always `/etc/system-release`.
Related: https://github.com/oamg/convert2rhel/pull/75/.
=> Simplify getting /etc/system-release path

convert2rhel/redhatrelease.py
The code included some leftovers from the time the tool supported
conversions to RHEL 5.
Related: https://github.com/oamg/convert2rhel/pull/75
=> Simplify getting the redhat-release pkg name

convert2rhel/main.py, convert2rhel/pkghandler.py, convert2rhel/subscription.py, convert2rhel/systeminfo.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/repo_test.py, convert2rhel/unit_tests/subscription_test.py
The feature of consuming the offline snapshot of RHEL repos hasn't ever been used in upstream and it's not planned to be ever used. It used to provide information to the user prior the conversion about what packages *might* not be available in RHEL. Considering that we have no mechanism to get such snapshot publicly, the feature is being removed to make the code simpler.
=> Do not expect offline snapshot of RHEL repos

convert2rhel/main.py, convert2rhel/unit_tests/main_test.py
Tests makes sure call order is what we expect, as a benefit it also catches the error introduced in #99
=> Fix: RHSM repo availibility method not found 

convert2rhel/main.py, convert2rhel/pkghandler.py, convert2rhel/unit_tests/pkghandler_test.py
Users may have locked some of the installed packages to a certain version using `yum-plugin-versionlock`. This would most probably cause the conversion to fail because the RHEL equivalent of the package may easily have a different version.
This PR check if `yum-plugin-versionlock` is installed, if so, ask user if want to continue, if yes clear the versionlock list, if no conversion will stop.
See https://access.redhat.com/solutions/98873 for more information.
=> add: Clear yum versionlock

convert2rhel/main.py, convert2rhel/systeminfo.py, convert2rhel/unit_tests/systeminfo_test.py
Created new function `generate_modified_rpms` to check if there's any modified rpm during the conversion process, if yes:
- write a new log file with the modified rpms
- print on standard stdout the modified rpms
- return all modified rpms as list
=> new: Print modified rpm files

plans/unittests.fmf
We can simply install the nose CentOS package.
=> Resolve nose not being available though pip

convert2rhel/pkghandler.py, convert2rhel/toolopts.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/subscription_test.py, convert2rhel/unit_tests/toolopts_test.py
Currently, when using RHSM, convert2rhel renames all non-RHSM repofiles to make sure only the RHSM ones are used. That causes a problem when somebody passes --enablerepo together with using RHSM, and this repo is in some other repofile than /etc/yum.repos.d/redhat.repo. Because of the repofile renaming, this repository is then unexpectedly not used during the conversion.
Some unit tests need to be changed to reflect `--disable=*` from yum command
A/C:
- Add `--disable=*` as default for yum command (if user pass `--disablerepo` arg would have priority over that)
- When using RHSM, use `--enable=XXX` for each of enabled repository from these command: `subscription-manager repos --list-enabled`
=> Fix: Do not rename .repo files

convert2rhel/unit_tests/utils_test.py
There were assertions that were allways evaluated to True.
=> Fix allways True unit test of utils

convert2rhel/pkghandler.py, convert2rhel/subscription.py, convert2rhel/systeminfo.py, convert2rhel/unit_tests/pkghandler_test.py
There was a bug causing that when subscription-manager was used for the
conversions, no repository got enabled when calling yum. And because by
default convert2rhel disables all repos in yum calls except those to be
specifically enabled, the conversion could not proceed.
The issue got introduced in https://github.com/oamg/convert2rhel/pull/84.
=> Enable repos enabled through RHSM in yum calls

convert2rhel/data/6/x86_64/configs/centos-6-x86_64.cfg, convert2rhel/data/6/x86_64/configs/oracle-6-x86_64.cfg, convert2rhel/data/6/x86_64/configs/suse_es-6-x86_64.cfg, convert2rhel/data/7/ppc64/configs/centos-7-ppc64.cfg, convert2rhel/data/7/x86_64/configs/centos-7-x86_64.cfg, convert2rhel/data/7/x86_64/configs/oracle-7-x86_64.cfg, convert2rhel/data/7/x86_64/configs/suse_es-7-x86_64.cfg, convert2rhel/main.py, convert2rhel/pkghandler.py, convert2rhel/systeminfo.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/pkghandler_test.py
Everything blacklist is now renamed to excluded. Such as `blacklisted_pkgs` to `excluded_pkgs`. Spec files with changelog entries have not been changed
=> refactor: move away from blacklist

convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py
Fixes `TypeError: execve() argument 1 must be encoded string without NULL bytes, not str` error with `subprocess` and `shlex` for python 2.6 with OL6/CentOS 6
Gotten the bugfix to work but be wary in testing as the error it fixes may not happen every time
=> fix(Utils): Avoid NULL byte error by ASCII-encoding subprocess command

convert2rhel/data/6/x86_64/configs/centos-6-x86_64.cfg, convert2rhel/data/6/x86_64/configs/oracle-6-x86_64.cfg, convert2rhel/data/7/x86_64/configs/centos-7-x86_64.cfg, convert2rhel/data/7/x86_64/configs/oracle-7-x86_64.cfg, convert2rhel/data/8/x86_64/configs/centos-8-x86_64.cfg, convert2rhel/main.py, convert2rhel/subscription.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/subscription_test.py
RHN has been shut down for good. And the RHN-related package rhn-client-tools started causing the conversion to fail on OL7.8.
=> Remove all things RHN

.github/workflows/coverage.yml, .github/workflows/pylint.yml, Dockerfiles/centos6, Dockerfiles/centos7, Dockerfiles/centos8, convert2rhel/data/6/x86_64/configs/oracle-6-x86_64.cfg, convert2rhel/data/8/x86_64/configs/oracle-8-x86_64.cfg, convert2rhel/pkghandler.py, convert2rhel/redhatrelease.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/redhatrelease_test.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py, packaging/convert2rhel.spec, plans/unittests.fmf
- Added missing dnf-utils dependency for yumdownloader.
- Replaced function getting package NVRA with getting NEVRA as that's what yum/dnf is printing.
- Improved function for downloading packages that uses yumdownloader to be more robust.
- The get_installed_pkgs_w_different_fingerprint function, when using DNF, filters packages by name only, not by package NEVRA as with YUM.
- Fixed getting the redhat-release package name, it's different on RHEL 8 than on RHEL 6 and 7.
To convert OL 8, run the following under root:
```
dnf install -y http://mirror.centos.org/centos/8/BaseOS/x86_64/os/Packages/python3-syspurpose-1.26.20-1.el8_2.x86_64.rpm # temporary before we fix deps
curl https://copr.fedorainfracloud.org/coprs/g/oamg/convert2rhel/repo/epel-8/group_oamg-convert2rhel-epel-8.repo -o …
```
=> Add support for converting OL 8

packaging/convert2rhel.spec
The python-syspurpose and python3-syspurpose packages are the required dependencies of the RHEL 7 and 8 subscription-mananger package, respectively. However this syspurpose package is not available on Oracle Linux, so on OL 7 and 8, the installation of convert2rhel is not possible, unless one installs the syspurpose package from a non-standard repository manually beforehand.
Since the main and documented use of convert2rhel is currently with using custom repositories, and not RHSM, we are removing this dependency.
If anyone would like to use subscription-manager, they need to download the syspurpose package to the /usr/share/convert2rhel/subscription-manager/ upon installing convert2rhel, alongside the subscription-manager pkgs.
In the future:
- all the subscription-manager dependencies …
=> Do not require python-syspurpose in spec

packaging/convert2rhel.spec, setup.py
Changes in this version include:
- allow conversions of CentOS and Oracle Linux 8 (#82, #112)
- fix "TypeError: execve()" py2.6-related error when calling external commands (#114)
- remove unused code related to using offline snapshot or RHEL repositories (#99)
- remove all Red Hat Network (RHN)-related code as RHN has been shut down (#115)
- set POSIX/C locale at the start of running the tool (#83)
- remove python-syspurpose dependency from spec - not available on OL 7 and 8 (#117)
- not renaming the original system repofiles anymore (#84)
- replace the word blacklist with exclude/excluded (#106)
- clearing yum versionlock that could cause the conversion to fail (#92)
- printing rpm files that were modified during the conversion (#90)
- minor UX improvements (#113) and test …
=> Bump version to 0.13

CONTRIBUTING.md
And mention the new epel8 dist-git branch.
=> Doc: Fix path to the spec file in the release guide

convert2rhel/pkghandler.py, convert2rhel/unit_tests/pkghandler_test.py
Previously the installation repo was printed only on systems with yum. With dnf, the repo was always "N/A" due to using an attribute not provided by dnf.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1879168
=> Fix printing package installation repo with dnf

convert2rhel/main.py, convert2rhel/pkghandler.py, convert2rhel/unit_tests/pkghandler_test.py
Warn the user when they provide the same repo in both the --disablerereo and --enablerepo option.
=> add: check/warn user if same repo in both enable / disable repo options

.github/workflows/pylint.yml, .packit.yaml, CONTRIBUTING.md
EPEL 6 is not available anymore, that is - not available in Fedora Copr as chroot, not available as a repository.
As well, CentOS 6 repos are not available anymore (except Vault which is an archive of old and not updated versions of CentOS).
That impacts our pylint tests, package building, unit testing. We'll be looking for another ways to have the packages for CentOS/OL 6 built and the code tested with py2.6.
=> Remove CentOS/EPEL 6 from CI/CD

convert2rhel/pkghandler.py, convert2rhel/unit_tests/pkghandler_test.py
Without this fix the original kernel silently remains not replaced with the RHEL one in case the kernel version on the original system is the same as the version available for RHEL.
Related change that caused this bug: https://github.com/oamg/convert2rhel/pull/112/files#diff-ed1ca2e4a8b27f1bee13d608562d4e94eceb2972790eccf4d84f366b750f221dR433
=> Fix not replacing same version kernel

.packit.yaml
The EPEL 6 chroot in the Fedora Copr was not available for couple of days but it has been brought back:
https://lists.fedoraproject.org/archives/list/copr-devel@lists.fedorahosted.org/message/WWXS2ZBISPYM2AXTP3CKYCHDRHM7OTIZ/
Also, we are removing the `propose_downstream` packit job as we are not going to use this feature going forward. First, [the feature is broken](https://github.com/packit/packit-service/issues/624), even though our team was planning to fix it. Second, the EPEL 6 is gone for good but we still need a place for distributing convert2rhel for CentOS/OL 6.
=> Add back EL 6 copr builds and testing

.github/workflows/pylint.yml
There was an issue with unavailable CentOS 6 repos. They have moved to Vault.
Reverts the removal from https://github.com/oamg/convert2rhel/pull/126.
=> Add back pylint 2.6 check

.github/workflows/release.yml
Upon creating a new release, a GitHub Action is triggered to build RPMs for EL 6, 7 and 8. These RPMs are attached to the release.
Test release: https://github.com/bocekm/convert2rhel/releases/tag/0.13-test-16
=> Automate building rpms with a GitHub release

packaging/convert2rhel.spec, setup.py
The changes in this version include:
- Fix same version kernel not being replaced silently (PR #130)
- Not renaming the original system repofiles anymore (PR #125)
- Fix printing package installation repo with dnf (PR #122)
- Warn users if same repo in both enable/disablerepo options (PR #116)
- Improve manpage/help for the enable/disablerepo options (PR #84)
Merge #125 and #135 first.
=> Bump version to 0.14

convert2rhel/main.py, convert2rhel/subscription.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/subscription_test.py
When using RHSM, we currently rename all repofiles not coming from Red Hat during the conversion so that they are not used for the conversion in any way. That causes a problem when somebody passes --enablerepo together with using RHSM, and this repo is in some other repofile than /etc/yum.repos.d/redhat.repo. Because of the repofile renaming, this repository is then unexpectedly not used during the conversion.
The repofile renaming is not needed if we call yum with the right parameters (--enablerepo and --disablerepo) and that's what we've managed under https://github.com/oamg/convert2rhel/pull/109/.
=> Do not rename repofiles

Dockerfiles/centos6
CentOS 6 has been retired and its repos moved to the Vault. We use CentOS 6 Docker image for unit testing, so we need to point the yum repos to the Vault now.
Related: #136
=> Use Vault in CentOS 6 Docker image

convert2rhel/data/8/x86_64/configs/centos-8-x86_64.cfg, convert2rhel/data/8/x86_64/configs/oracle-8-x86_64.cfg
In CentOS 8.3 the package that used to be named `centos-release` in CentOS 8.2 was renamed to `centos-linux-release`.
Also, the `centos-repos`/`centos-linux-repos` and `centos-obsolete-packages` were missing in the list of pkgs to remove thus not being removed during the conversion.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1913008
=> Add missing CentOS 8 packages - to be removed prior the conversion

packaging/convert2rhel.spec, setup.py
This version includes the following changes:
- Add missing CentOS 8 packages to be removed prior the conversion (PR #140)
=> Bump version to 0.15

convert2rhel/unit_tests/__init__.py, convert2rhel/unit_tests/example_test.py, convert2rhel/unit_tests/logger_test.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/other_test.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/redhatrelease_test.py, convert2rhel/unit_tests/subscription_test.py, convert2rhel/unit_tests/systeminfo_test.py, convert2rhel/unit_tests/toolopts_test.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py
After this MR it will be possible to run tests locally on non-CentOS systems.
Also, python2.6, 2.7, 3 compatible `skipIf` decorator is introduced, that allows to skip tests on condition. API is similar to https://docs.python.org/2/library/unittest.html#unittest.skipIf 
Skipped tests are reported in the testing session log:
```
centos6_1  | ............/data/convert2rhel/unit_tests/__init__.py:182: UserWarning: Test <function test_call_yum_cmd_w_downgrades_continuous_fail at 0x1fba7d0> skipped. Reason: Current test runs only on rpm based systems.
centos6_1  |   warn("Test %r skipped. Reason: %s" % (test_item, reason))
centos6_1  | ...................../data/convert2rhel/unit_tests/__init__.py:182: UserWarning: Test <function test_get_rpm_header at 0x1fc41b8> skipped. Reason: Current test …
```
=> Allow running tests on non CentOS systems

convert2rhel/main.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py
Require the system-to-be-converted to be booted in a single-user mode.
That would prevent other user sessions from doing changes to the system during the conversion.
WARNING:
- Need to update the vagrant test box after merge this PR.
- Need to update the Red Hat Knowledgebase article (https://access.redhat.com/articles/2360841)
=> add: check single-user mode

convert2rhel/pkghandler.py
Add comments to clarify why do we display either package vendor or package packager.
Related: https://github.com/oamg/convert2rhel/pull/133
=> Clarify getting package vendor/packager information

convert2rhel/main.py, convert2rhel/utils.py
The single-user mode check was kind of hidden:
- the check itself was not announced by the tool (TASK),
- ~~executing of the `runlevel` command was not logged,~~ (fixed in https://github.com/oamg/convert2rhel/pull/149)
- ~~the output of the `runlevel` command was always printed to the standard output - that was very mysterious (suddenly seeing `N 3` on the output)~~ (fixed in https://github.com/oamg/convert2rhel/pull/149)
Before:
```
[01/14/2021 22:52:25] TASK - [Prepare: Gather system information] *******************************
Name:                CentOS Linux
OS major version:    7
[01/14/2021 22:52:25] DEBUG - Calling command 'uname -i'
Architecture:        x86_64
Config filename:     centos-7-x86_64.cfg
Skipping the execution of 'rpm -Va'.
N 3
CRITICAL - Convert2RHEL requires the …
```
=> Improve logging of single-user mode check

.gitignore, Makefile
Adding some Makefile good practices. Now targets have dependencies. For example, running:
- make tests, will automatically build images for you (only first time)
- make tests-locally, will create the venv (also only first time)
=> Now tests*,lint* targets automatically installs required dependencies

convert2rhel/data/6/x86_64/configs/centos-6-x86_64.cfg, convert2rhel/data/6/x86_64/configs/oracle-6-x86_64.cfg, convert2rhel/data/6/x86_64/configs/suse_es-6-x86_64.cfg, convert2rhel/data/7/ppc64/configs/centos-7-ppc64.cfg, convert2rhel/data/7/x86_64/configs/centos-7-x86_64.cfg, convert2rhel/data/7/x86_64/configs/oracle-7-x86_64.cfg, convert2rhel/data/7/x86_64/configs/suse_es-7-x86_64.cfg, convert2rhel/data/8/x86_64/configs/centos-8-x86_64.cfg, convert2rhel/data/8/x86_64/configs/oracle-8-x86_64.cfg, convert2rhel/main.py, convert2rhel/pkghandler.py, convert2rhel/subscription.py, convert2rhel/systeminfo.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/subscription_test.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py, packaging/convert2rhel.spec
We currently install dependencies for RHSM through spec files so we can install it through RPM. Instead we should utilize yum to resolve the dependencies for us.
See https://github.com/oamg/convert2rhel/pull/82#issuecomment-680937882 
OAMG-3843
TODO:
=> feat: install subscription-manager through yum, not rpm and spec file

convert2rhel/main.py, convert2rhel/pkghandler.py, convert2rhel/redhatrelease.py, convert2rhel/subscription.py, convert2rhel/systeminfo.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/redhatrelease_test.py, convert2rhel/unit_tests/subscription_test.py, convert2rhel/unit_tests/systeminfo_test.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py, packaging/convert2rhel.spec, pytest.ini
**Blocked by:** #107 
Download subscription-manager automatically, with workaround for CentOS 7, because of this bug: https://bugs.centos.org/view.php?id=14785
TODO:
=> Download subscription-manager automatically

packaging/convert2rhel.spec, setup.py
This version includes the following changes:
- Not requiring users to download the following packages prior the conversion when using RHSM:
- redhat-release (#105)
- subscription-manager and its dependencies (#100)
- Removed subscription-manager dependencies from the convert2rhel spec file by installing subscription-manager through yum/dnf during the conversion instead of through rpm (#107)
- The --variant option for choosing RHEL variant was broken. Instead of fixing it we removed all the related code. The system is always converted to RHEL Server variant in case of RHEL 6 and 7. RHEL 8 has no variants. Using the --variant option now prints a warning. (#139)
- Updated Red Hat EULA to the 2019 version (#162)
- Messages of importance are printed in color in the terminal (#134)
- When …
=> Bump version to 0.16

.github/workflows/release.yml
The trigger on "created" was incorrect as that means the rpm-building GitHub Action is triggered even when a release **draft** is created. And then upon publishing the draft the GitHub Action is not triggered again, leaving the release without built rpms.
Release trigger types: https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#release
I've added "edit" type as well - that is just temporary to be able to trigger the action for the already [released version 0.16](https://github.com/oamg/convert2rhel/releases/tag/v0.16). After triggering it, I'll create a new PR removing the "edit" type.
=> Created rpms on publishing a new release

.coveragerc, pytest.ini
Previously the coverage included the scope of tests itself. This is fixed now. Also, the min coverage margin to make the coverage job was adjusted to reflect the current state
=> Add proper coverage config

.github/workflows/release.yml
I expected that we'll need the release edit trigger to have the packages built for the version 0.16 release, but it was not needed.
The [release publishing event](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#release) is the only trigger we need.
Related: https://github.com/oamg/convert2rhel/pull/173
=> Do not build rpms on GitHub release edit

Dockerfiles/centos6.Dockerfile, Dockerfiles/centos7.Dockerfile, Dockerfiles/centos8.Dockerfile
Due to running the tests inside the containers, there is no sense to cache pyc files, forever this creates additional overhead for the user to remove them before next tests.
This is fixed now
=> Forbid python to create pycache in containers

convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py
We were passing incorrect --releasever to the yumdownloader call. This releasever is to be used with RHEL repositories, not with the original system repositories.
It caused the pkg download to not be able to access the original system repositories and thus to not download the packages for the rollback.
=> Fix backing up packages

convert2rhel/logger.py, convert2rhel/unit_tests/conftest.py, convert2rhel/unit_tests/logger_test.py, requirements/centos6.requirements.txt, requirements/centos7.requirements.txt
Caplog adds its own handler to the root logger to track the records, however
our logger setup blocks the handler from being propagated to all child loggers.
This makes the caplog blind to the emitted entries.
Also, tests are rewritten in pytest because the old way was tested the logger
indirectly, switching to propagate=True led to inconsistent results across
different Python versions, which makes it hard to test.
The logger module coverage increased from 93 -> 100%
Also added helper fixtures to capture stdout and stderr
=> Allow caplog see logger entries

convert2rhel/unit_tests/pkghandler_test.py
Related: https://github.com/oamg/convert2rhel/pull/152
=> Fix unit test due to a typo

convert2rhel/pkghandler.py, convert2rhel/unit_tests/pkghandler_test.py
Under typical circumstances, kernel is installed using yum and with that the system-release/redhat-release pkg is installed as a dependency. However when the original OR kernel and RHEL kernel have the same version, we install it through rpm which causes the "system-release is needed by kernel" error because system-release/redhat-release is not installed at that point.
Reported in https://github.com/oamg/convert2rhel/issues/166.
=> Do not check deps when force replacing kernel

convert2rhel/pkghandler.py, convert2rhel/unit_tests/pkghandler_test.py
For the case when the all installed kernels have the same version as those available in RHEL repos, we need to download one of the RHEL kernels and force replace the already installed one. However for the download we were using only the RHEL repos passed through the --enablerepo option. That would cause the download to fail if the tool uses RHSM and not custom repos (--enablerepo).
TODO:
=> Use RHSM repos for downloading same version kernel

packaging/convert2rhel.spec, setup.py
Changes in this version include:
- Fix broken package backup causing an incomplete rollback (#177)
- Fix dependency issue when force replacing same-version kernel (#182)
- Allow using RHSM repos when downloading same-version kernel (#178)
=> Bump to version 0.17

Dockerfiles/centos6.Dockerfile, Dockerfiles/centos7.Dockerfile, Dockerfiles/centos8.Dockerfile
URL for pip was moved, this uses the new URL as mentioned in their notice
> Hi there!
> 
> The URL you are using to fetch this script has changed, and this one will no
> longer work. Please use get-pip.py from the following URL instead:
> 
>     https://bootstrap.pypa.io/pip/2.7/get-pip.py
> 
> Sorry if this change causes any inconvenience for you!
> 
> We don't have a good mechanism to make more gradual changes here, and this
> renaming is a part of an effort to make it easier to us to update these
> scripts, when there's a pip release. It's also essential for improving how we
> handle the `get-pip.py` scripts, when pip drops support for a Python minor
> version.
> 
> There are no more renames/URL changes planned, and we don't expect that a need
> would arise to do this again in the near …
=> fix: Change URL for pip in containerfiles

convert2rhel/main.py, convert2rhel/unit_tests/__init__.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py
This commit will check if `/mnt` and `/sys` are read/write, if not, will abort the conversion.
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1887513
=> add: Check if /mnt /sys is read/write

convert2rhel/checks.py, convert2rhel/main.py, convert2rhel/unit_tests/checks_test.py
In case the system is booted using the UEFI firmware, the bootloader
is broken (user ends with the grub prompt). Inhibit the conversion
in case the UEFI is detected to prevent users from the broken
bootloader state.
Note: The current UEFI detection solution is not handling hybrid boot
(e.g. used on AWS, Azure, ...). It's possible that in case of hybrid
boot an additional checks will be needed. But such systems are not
supported for conversions right now so using just the simple detection.
Relates:  https://bugzilla.redhat.com/show_bug.cgi?id=1898314
Co-author: Fellipe Henrique <fellipeh@gmail.com>
On BIOS:
```
[03/15/2021 18:26:50] TASK - [Prepare: Gather system information] *******************************
Name:                CentOS Linux
OS version:          7.9
Architecture: …
```
=> Inhibit the system conversion on UEFI

convert2rhel/pkghandler.py, convert2rhel/unit_tests/pkghandler_test.py
Fixes conversion failures due to packages like `abrt-cli` not resolving dependencies. We do this by taking all the errors we can find and removing them manually if the resolving of dependencies do not take care of them
`abrt-cli` caused conversion to fail due to dependency errors. A dependency `abrt-retrace-client` is in base CentOS repo but not in RHEL repo, only RHEL optional repo.
Since packages in RHEL optional repo is not supported we cannot enable this by default. For now we will simply remove the packages to ensure that the conversion goes smoothly
Closes #166, closes #200
=> fix: Remove dependencies that isn't fixed

.github/workflows/pylint.yml, .github/workflows/tests.yml
Currently, container can't be build due to inability to install pip. We need to disable centos6 pipelines until finishing the investigation, in order do not block other MRs
=> Disable centos6 jobs until resolving the issue with ssl

.github/workflows/pylint.yml, .github/workflows/tests.yml
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
Allows matrix-runs to continue running if a run fails
---
Re-enables CentOS 6 runs
=> test: disable fail-fast for CI & enable CentOS 6

convert2rhel/data/7/x86_64/configs/centos-7-x86_64.cfg
Adds `mod_ldap` and `mod_proxy_html` to `excluded_pkgs`. Only happens on CentOS 7
=> fix: remove mod_ldap and mod_proxy_html

CONTRIBUTING.md, Makefile, convert2rhel/pkghandler.py, convert2rhel/subscription.py, packaging/build_locally.sh, packaging/convert2rhel.spec
All occurrences of CentOS X, or just CentOS are replaced with CentOS Linux X, or CentOS Linux
=> Rename CentOS -> CentOS Linux

convert2rhel/main.py, convert2rhel/unit_tests/main_test.py
`centos-release` wasn't backed up properly, this PR just changes the order of operations so we get proper backups to restore from.
Fixes #190
=> fix: enable rhel repos after repofile pkg removals

convert2rhel/checks.py
We call the `find` command to get the list of installed kernel modules.
We unintentionaly print the output of this command as a debug information. But it's of little value and adds hundreds or thousands lines to the log file.
Implements this missed review suggestion: https://github.com/oamg/convert2rhel/pull/193/files#r599911927.
=> Do not print the output of finding kmods

convert2rhel/checks.py, convert2rhel/unit_tests/checks_test.py
Otherwise the itertools.groupby doesn't work properly on python2
=> pkgs should be sorted for get_most_recent_unique_kernel_pkgs

convert2rhel/checks.py, convert2rhel/unit_tests/checks_test.py
There might be false positives so we don't want to inhibit in those
cases.
=> Do not inhibit conversion on unsupported kmods

convert2rhel/data/7/x86_64/configs/centos-7-x86_64.cfg
Leaving this package on the system leads to a transaction failure. It conflicts with files of the RHEL package cockpit-system that is being installed during the conversion.
=> Remove cockpit-subscriptions not available in RHEL

convert2rhel/data/7/x86_64/configs/centos-7-x86_64.cfg, convert2rhel/data/7/x86_64/configs/oracle-7-x86_64.cfg
The anaconda-dracut and anaconda-core rpms share by mistake 2 libexec
libraries on RHEL 7. As the anaconda-dracut rpm is present just inside
the optional repository on RHEL 7 which is by default disabled for
the conversion, the rpm transaction ends with conflicts between
anaconda-dracut and anaconda-core rpms. It do not even seems expected
that users could want to use the rpm at all. So just remove the rpm
during the conversion if installed.
The lists have been sorted for better orientation. Just the anaconda-dracut has been added.
=> Remove anaconda-dracut (in the optional repo)

convert2rhel/subscription.py, convert2rhel/unit_tests/__init__.py, convert2rhel/unit_tests/subscription_test.py
Previously utility tried an infinite number of times, asking the user for the credentials.
And only one time if credentials were provided through cli.
New solution provides fixed number of trials for both options
(may be adjusted via subscription.MAX_NUM_OF_TRIALS_TO_SUBSCRIBE)
and then inhibit the conversion.
The call for this feature comes from the experience of running integration tests when sometimes the system is unable to subscribe through the credentials provided by cli options.
=> Try the system to subscribe finite number of times

convert2rhel/checks.py, convert2rhel/data/6/x86_64/configs/centos-6-x86_64.cfg, convert2rhel/data/6/x86_64/configs/oracle-6-x86_64.cfg, convert2rhel/data/6/x86_64/configs/suse_es-6-x86_64.cfg, convert2rhel/data/7/ppc64/configs/centos-7-ppc64.cfg, convert2rhel/data/7/x86_64/configs/centos-7-x86_64.cfg, convert2rhel/data/7/x86_64/configs/oracle-7-x86_64.cfg, convert2rhel/data/7/x86_64/configs/suse_es-7-x86_64.cfg, convert2rhel/data/8/x86_64/configs/centos-8-x86_64.cfg, convert2rhel/data/8/x86_64/configs/oracle-8-x86_64.cfg, convert2rhel/systeminfo.py, convert2rhel/unit_tests/checks_test.py, convert2rhel/unit_tests/conftest.py
Some kernel modules move from kernel modules to kernel core. Instead of
inhibiting the conversion saying that such a module is not available in
RHEL and thus is unsupported, we ignore it.
=> Ignore kmods moved to kernel core

convert2rhel/pkghandler.py, convert2rhel/unit_tests/other_test.py, convert2rhel/unit_tests/pkghandler_test.py
Currently whenever we get dependencies to remove we don't use the correct output. We should grab the output that comes from already resolving the dependency issues.
=> fix: remove dep resolve correctly

convert2rhel/main.py, convert2rhel/toolopts.py
Currently the feature of suggesting a convert2rhel command to run on other systems to convert in a non-interactive fashion is not working properly. For example, it is missing couple of switches (e.g. --no-rpm-va and --debug) and does not handle well the situation with enabled repoids when RHSM is used.
To reduce the codebase to maintain and for the lack of feedback on this feature, we decided to remove it.
An example of the output being removed:
```
[03/29/2021 19:55:12] TASK - [Final: Non-interactive mode] **************************************
For the non-interactive use of the tool, run the following command:
convert2rhel --disable-submgr  --disablerepo=*  --enablerepo=rhel-7-server-rpms  -y
```
Related: https://issues.redhat.com/browse/OAMG-3141
=> Remove non-interactive command suggestion

convert2rhel/main.py, convert2rhel/special_cases.py, convert2rhel/unit_tests/special_cases_test.py
In case the java package is not installed, the log unsatisfactorily showed only the following message:
`[03/29/2021 19:34:37] TASK - [Convert: resolve possible edge cases] **********`
=> Add log messages around the java workaround

convert2rhel/toolopts.py
The warning messages are giving incorrect information when converting to RHEL 8 which comes with no variants.
This follows up on https://github.com/oamg/convert2rhel/pull/246.
=> Remove misleading --variant related messages

convert2rhel/toolopts.py, convert2rhel/unit_tests/toolopts_test.py
- The option was basically now showing in the help message.
- The warning message was not shown when the -v or --variant was used without a value.
- The help message was missing the point that RHEL 8 comes with no variants.
Resolves: https://issues.redhat.com/browse/OAMG-4558
=> Improve messaging around the obsoleted --variant option

convert2rhel/checks.py, convert2rhel/main.py, convert2rhel/unit_tests/checks_test.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py
Related ticket: OAMG-4697
Moving check_readonly_mounts function from `utils.py` to `checks.py`, since we defined one place for checks in checks.py. This will allow us easier to manage those checks.
=> fix: Moving check_readonly_mounts function from utils.py to checks.py

convert2rhel/subscription.py
The piece of message "provide username and password" is not printed - it does not make sense when using RHSM with activation key + org ID
The message "Attempt x of 3..." is printed only if registration unsuccessful to not scare people as most of the time it's successful
Looks like many changes, but from me are just two: added if+else from line [99](https://github.com/oamg/convert2rhel/pull/247/commits/0df8b4902a08d4871d82a8e98e7de3f2ec54c5bc#diff-51e9ff11d39778d3b26778b293fc350430a82e2feed0dab2938da7c0069ffdc6R99) and if+else from line [147](https://github.com/oamg/convert2rhel/pull/247/commits/0df8b4902a08d4871d82a8e98e7de3f2ec54c5bc#diff-51e9ff11d39778d3b26778b293fc350430a82e2feed0dab2938da7c0069ffdc6R147). The rest of the changes is made by Black code formatter.
=> Improvement of UX registration

convert2rhel/subscription.py
Convert2RHEL no longer tries to attach a subscription when an activation key
is used. It was resolved under https://github.com/oamg/convert2rhel/pull/91.
=> Remove obsolete TODO comment about activation keys

convert2rhel/checks.py, convert2rhel/unit_tests/checks_test.py, plans/integration/inhibit-if-oracle-system-uses-not-standard-kernel/main.fmf, plans/integration/inhibit-if-oracle-system-uses-not-standard-kernel/vm_oracle7.fmf, plans/integration/inhibit-if-oracle-system-uses-not-standard-kernel/vm_oracle8.fmf, tests/integration/conftest.py, tests/integration/inhibit-if-oracle-system-uses-not-standard-kernel/ansible/replace_oracle_kernel.yml, tests/integration/inhibit-if-oracle-system-uses-not-standard-kernel/main.fmf, tests/integration/inhibit-if-oracle-system-uses-not-standard-kernel/test_oracle_bad_kernel.py
We can't guarantee the fully functional state of the OS after the conversion if a kernel that is not available in RHEL is being used before the conversion. This change inhibits the conversion in an early conversion stage. Example of the message:
```
SystemExit: The booted kernel is not compatible with the target RHEL system.
To proceed with the conversion, boot a RHEL-compatible kernel (RHCK) by 
executing the following steps:
1. yum install kernel
2. (optional step) grubby --set-default /boot/vmlinuz-{{ installed_kernel_version_from_step_1 }}
3. reboot the machine and if step 2 was not applied choose RHCK (installed in step 1) manually.
```
TODO:
=> Feature: inhibit if non-standard kernel is used

convert2rhel/main.py
Without this it may not be obvious that the conversion finished successfully. See:
```
[05/11/2021 14:24:05] TASK - [Final: rpm files modified by the conversion] **********************
Skipping the execution of 'rpm -Va'.
Skipping comparison of the 'rpm -Va' output from before and after the conversion.
WARNING - In order to boot the RHEL kernel, restart of the system is needed.
```
=> Print confirmation of a successful conversion

convert2rhel/pkghandler.py, convert2rhel/unit_tests/pkghandler_test.py
In https://github.com/oamg/convert2rhel/pull/237/files#diff-361f5dc14483ec43e37529967acee396da5714dbf6562472ccece5db4bba5e0dR150, I did not expect yum to print parentheses when describing what dependency is missing. It does not print a package name but [a capability](https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch-dependencies.html#RPM_Guide-Dependencies-capabilities) and that can be _"any arbitrary text string"_.
Specifically it wasn't able to deal with errors like this:
```
Error: Package: redhat-lsb-trialuse-4.1-27.el7.centos.1.x86_64 (@base/7)
Requires: redhat-lsb-core(x86-64) = 4.1-27.el7.centos.1
Removing: redhat-lsb-core-4.1-27.el7.centos.1.x86_64 (@base/7)
redhat-lsb-core(x86-64) = 4.1-27.el7.centos.1
Downgraded By: …
```
=> Fix incorrect dependency error resolution

ansible/ansible-convert2rhel.yml
With RHEL 8.4 soon upon us, we need to update the Ansible playbook to check for release version 8.4.
=> update ansible playbook to 8.4

pyproject.toml, requirements/local.centos8.requirements.txt, scripts/extract_version_from_rpm_spec.py, tests/ansible_collections/roles/packaging/tasks/install_rpm_from_local_build.yml
**Warning this MR is needed to be able to test release 0.21-2**
Previous way to recognize the pkg version was:
cat packaging/convert2rhel.spec | awk '/Version.+/ {print $2}'
Release data were ignored in parsing
This MR introduce better parsing mechanism, which is able to identify Version and Release
=> Now the convert2rhel package version is properly recognized

convert2rhel/checks.py, convert2rhel/systeminfo.py, convert2rhel/unit_tests/checks_test.py
The message around unsupported kernel modules was not asking to make sure the system runs the latest kernel which is an important prerequisite of the kernel module check.
Also, it was stating that disabling the modules will help. But it does not. The module needs to be removed in order to not be picked up by the check.
And printing plainly the `uname -r` call result was confusing.
=> Improve messaging around the unsupported kmods error

convert2rhel/checks.py
Quick leftover from #285 . I ran tests in a different branch, so they passed but were irrelevant.
After running the tests on #285 I found a bug, which this MR fixes.
Function `get_most_recent_unique_kernel_pkgs` returned a generator, because it was assumed to be used only once. In #285 it was used two times, so second time (when do a repoquery -l it was empty and the conversion inhibited with all kmods are unsupported
=> fix list of recent kernel pkgs was a generator -> tuple

tests/ansible_collections/roles/oracle-linux-specific/tasks/boot_standard_kernel.yml
For playbook which reboots the OL into RHCK:
The previous solution was unable to install kernel if there were present a kernel-.+ package name. This is fixed now
Resolves https://issues.redhat.com/browse/OAMG-4960.
=> OL: ensure kernel.{arch} pkg to be installed

convert2rhel/data/8/x86_64/configs/centos-8-x86_64.cfg, convert2rhel/data/8/x86_64/configs/oracle-8-x86_64.cfg
With RHEL 8.4 out and CentOS/Oracle Linux still 8.3, the conversion is stopped on kernel differences. Before we introduce a proper solution, this change is letting the systems convert to RHEL 8.3 instead of 8.4.
=> Hardcode RHEL 8.3 as a target

tests/integration/conftest.py
We need the system to be unregistered instead of unsubscribed. This way the command fails at the end of a test and the test then fails because of that as well.
Blocks: https://github.com/oamg/convert2rhel/pull/288
=> Unregister upon finishing a test

convert2rhel/subscription.py
We were removing all packages with their name starting with katello. We wanted to remove only katello-ca-consumer* packages though (this package configures the subscription-manager to talk to a Satellite server). But we were unintentionally removing also katello-host-tools and katello-host-tools-tracer.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1962193#c7
=> Do not remove katello-host-tools

convert2rhel/main.py, convert2rhel/pkghandler.py, convert2rhel/subscription.py
And pytest deprecation warnings about using logger.warn() instead of logger.warning().
=> Resolve >120 chars line pre-commit failure

Makefile
Closes OAMG-5037
Makefile eval, inside a target, executed before any other command.
In our case, this was resulted in getting the image id before building it, so rpms were outdated at 1 build.
This MR fixes this issue
=> fix: wrong order of the commands in make rpms

convert2rhel/checks.py, convert2rhel/unit_tests/checks_test.py, plans/integration/check-custom-repo/main.fmf, plans/integration/check-custom-repo/vm_centos7.fmf, plans/integration/check-custom-repo/vm_centos8.fmf, plans/integration/check-custom-repo/vm_oracle7.fmf, plans/integration/check-custom-repo/vm_oracle8.fmf, tests/integration/check-custom-repo/main.fmf, tests/integration/check-custom-repo/test_custom-repos.py
When using custom repos but the repoid passed through --enablerepo is not valid (typo in the repoid, the baseurl not accessible, etc.), convert2rhel continues without a problem beyond the point of no return (PONR) and then it fails, leaving the user with a message that they need to fix their system manually.
This PR check the validity os repos before anything.
=> add: check function to validate custom repos

convert2rhel/subscription.py
When registering the system through subscription-manager, the key can contain a space character.
Related: https://access.redhat.com/discussions/5676681#comment-2117741
=> Add quotes around the activation key

tests/ansible_collections/group_vars/all.yml.example
`rpm_build_provider` has been renamed to `rpm_provider`, this updates a reference from the old to the new name
=> test: rename old reference

convert2rhel/checks.py, convert2rhel/main.py, convert2rhel/pkghandler.py, convert2rhel/redhatrelease.py, convert2rhel/unit_tests/checks_test.py
Without using the --debug, the output of the tool was not providing information about whether certain steps succeeded. Or it provided irrelevant information (like the output of `yum clean metadata`).
For example:
```
[06/14/2021 16:59:48] TASK - [Prepare: Initial system checks before conversion] *****************
[06/14/2021 16:59:48] TASK - [Prepare: Checking the firmware interface type] ********************
[06/14/2021 16:59:48] TASK - [Convert: Checking /mnt and /sys are read-write] *******************
[06/14/2021 16:59:48] TASK - [Prepare: Check kernel compatibility with RHEL] ********************
[06/14/2021 16:59:48] TASK - [Prepare: Checking if --enablerepo repositories are accessible] ****
Loaded plugins: fastestmirror
Cleaning repos: rhel-7-server-rpms
4 metadata files removed
3 …
```
=> Improve the non-debug output

convert2rhel/checks.py, convert2rhel/main.py, convert2rhel/subscription.py, convert2rhel/systeminfo.py, convert2rhel/toolopts.py, convert2rhel/unit_tests/checks_test.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/toolopts_test.py
Both are still possible to use and both have the same effect.
The reason is that:
1. we are not disabling the subscription-manager (bad choice of wording) and
2. the same option is used in LEAPP for RHEL system upgrades.
=> Rename --disable-submgr option to --no-rhsm

convert2rhel/main.py, convert2rhel/subscription.py, convert2rhel/toolopts.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/subscription_test.py, convert2rhel/unit_tests/toolopts_test.py
New option --keep-rhsm is used. The user needs to install the subscription-manager packages before performing the conversion.
To do:
=> Allow conversions of offline systems

tests/integration/main.fmf
Setting maximal duration for all tests to 30 minutes. Without this the default value is 5 minutes. In 5 minutes any test cannot be successfully finished.
[Documentation](https://tmt.readthedocs.io/en/stable/spec/tests.html#duration)
=> Set max duration for test

tests/integration/check-custom-repo/test_custom-repos.py
Fix failing test for ` /plans/integration/check-custom-repo/` plan
=> Fix wrong expected msg in custom-repos test

convert2rhel/cert.py, convert2rhel/main.py, convert2rhel/unit_tests/cert_test.py, convert2rhel/unit_tests/main_test.py
Instead of requiring the pre-download and installation of redhat-release, we now copy the RHSM .pem certificates to /etc/pki/product-default/ at the beginning of the conversion process. However in case of any failure, we do not rollback this action, leaving the certificate where we copied it. That does not follow our official statement that "until the point of no return, convert2rhel reverts all its actions in case of a failure".
=> Copying of RHSM certs not rolled back

convert2rhel/unit_tests/cert_test.py
FileExistsError does not exist in python 2. Missed in review of #203
OSError can be used instead
=> fix: python 2 FileExistsError

.env.example, plans/integration/conversion/basic-conversion/main.fmf, plans/integration/conversion/main.fmf, tests/ansible_collections/reboot.yml, tests/ansible_collections/roles/oracle-linux-specific/tasks/boot_standard_kernel.yml, tests/integration/conversion/basic-conversion/main.fmf, tests/integration/conversion/basic-conversion/test_basic_conversion.py, tests/integration/conversion/main.fmf, tests/integration/conversion/run_conversion.py
Add a placeholder for writing conversion tests (tests after successful conversion) and add a basic conversion test.
Replaces #216
~~**Blocked by failing centos8 conversion now #277**~~
~~**Blocked with #304**~~
Testing this MR might be possible after updating tmt:
```pip install git+https://github.com/ZhukovGreen/tmt.git@poc/tmt-adoption-for-convert2rhel --no-cache-dir```
and
prepend your .env with `DEBUG=True`
=> Add basic conversion test

convert2rhel/main.py, convert2rhel/redhatrelease.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/redhatrelease_test.py, plans/integration/changed-yum-conf/main.fmf, tests/integration/changed-yum-conf/main.fmf, tests/integration/changed-yum-conf/test_patch_yum_conf.py
Since https://github.com/oamg/convert2rhel/pull/105 we do no longer install the redhat-release package but instead we copy the RHSM certificates to the system.
Yet currently we are commenting out the distroverpkg variable from the /etc/yum.conf. For example on CentOS 7 it's distroverpkg=centos-release. This variable tells yum at which package to look at to be able to expand the $releasever variable. But in https://github.com/oamg/convert2rhel/pull/105 we've started using the --releasever yum option for every yum call.
The conf patching is not necessary anymore, except one use case - when user touches the yum.conf prior executing the conversion (`rpm -V yum`). Then during the conversion yum is replaced but not this config file, so it keeps the distroverpkg variable. If we don't patch the …
=> Rework patching yum.conf

tests/integration/check-custom-repo/main.fmf, tests/integration/conversion/basic-conversion/main.fmf, tests/integration/inhibit-if-kmods-is-not-supported/main.fmf, tests/integration/inhibit-if-oracle-system-uses-not-standard-kernel/main.fmf, tests/integration/releasever-as-mapping/main.fmf, tests/integration/remove-excluded-pkgs/main.fmf, tests/integration/remove_all_submgr_pkgs/main.fmf, tests/integration/resolve-broken-ol8-rollback/main.fmf, tests/integration/resolve-dependency/main.fmf
Packit runs all tmt plans for each built rpm.
In order to skip irrelevant plans in this case we need to
additional guard to each test, which makes sure only relevant tests
will be run for a given rpm (distro)
This is solved with the help of https://tmt.readthedocs.io/en/stable/spec/core.html#adjust
ref https://github.com/packit/packit-service/issues/1164#
~~blocked by https://github.com/psss/tmt/issues/839~~
This MR do not affect the current functionality of running the tests and can be merged
=> Add distro filtering based on tmt context

convert2rhel/unit_tests/conftest.py, convert2rhel/unit_tests/logger_test.py
In the previous implementation, the type of the fixture was str in py2. This is fixed now and the type is identical (LocalPath) for both python versions.
ref #262
=> make tmpdir fixture be LocalPath type for both python3 and 2

tests/ansible_collections/roles/packaging/tasks/main.yml
Little improvement of the env vars check in ansible-playbook.
the previous solution is deprecated
=> Use proper comparison of the env var

convert2rhel/main.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py, plans/integration/conversion/delete-temp-folder/main.fmf, plans/main.fmf, tests/integration/conversion/delete-temp-folder/main.fmf, tests/integration/conversion/delete-temp-folder/test_delete_temp_folder.py
The utility copies bunch of files to /var/lib/convert2rhel/ (mainly backup for the rollback) and they are not being removed upon uninstalling the rpm. Then it's just a junk data.
I've added the remove of data as the absolutely last step of conversion.
=> Delete temp folder

tests/ansible_collections/reboot.yml
60 seconds to wait for the freshly converted cloud vm to be rebooted
and back online is way too optimistic, increasing to 600.
=> Raise reboot_timeout

Makefile
Whenever we get an error with pytest it displays the captured logs for
stdout and stderr. This may flood the terminal with a lot of logs which
is difficult to parse. By using `SHOW_CAPTURE=no make tests` the logs no
longer show and finding the errors is much easier
=> chore: allow disabling of captured logs

convert2rhel/pkghandler.py, convert2rhel/unit_tests/pkghandler_test.py
The regex used to get problematic packages did not catch all package
name variants. Packages like `mod_ldap` has an underscore in it instead of
a dash. This fix makes it possible to fetch packages like it.
=> fix: allow underscore in package nevr regex

convert2rhel/pkghandler.py, convert2rhel/unit_tests/pkghandler_test.py, plans/integration/resolve-dependency/main.fmf, tests/integration/resolve-dependency/main.fmf, tests/integration/resolve-dependency/test_resolve_dependency.py
This adds another set to the problematic dict that shows packages that
cause a mismatch of two packages. This mismatch will happen if a package
depends on something that cannot be installed.
See OAMG-4944
---
Currently just an idea and will need polishing
=> feat: handle mismatched packages

tests/ansible_collections/roles/install-testing-deps/tasks/main.yml
The main prepare-all-before-conversion playbook was wrongly
implying that pip was present on the vms which is not always
the case (take centos7 for instance).
=> Install pip as part of install-testing-deps role

plans/integration/check-variant-message/main.fmf, tests/integration/check-variant-message/main.fmf, tests/integration/check-variant-message/test_variant_message.py
This PR converts this STI test (https://gitlab.cee.redhat.com/sturivny/convert_tests/-/blob/master/tests/tests_help_message.yml) to TMT. It checks the variant option help message produced by c2r.
=> Convert STI to TMT: Add test that check variant help message

plans/integration/conversion/rhsm/main.fmf, plans/integration/conversion/rhsm/resolve-dependency/main.fmf, tests/integration/conversion/rhsm/resolve-dependency/install_dependency_packages.py, tests/integration/conversion/rhsm/resolve-dependency/main.fmf, tests/integration/conversion/rhsm/resolve-dependency/test_resolve_dependency.py
The equivalent of the dependency-check test (https://gitlab.cee.redhat.com/sturivny/convert_tests/-/blob/master/tests/tests_resolve_dep.yml) already exists in tmt. I moved this test to the `conversion` directory for better structure. 
This PR follows up the PR323 (https://github.com/oamg/convert2rhel/pull/323)
=> Convert STI to TMT: Move dependency check test to conversion directory

plans/integration/check-custom-repo/main.fmf, plans/integration/conversion/custom-repos/main.fmf, tests/ansible_collections/roles/add-custom-repos/main.yml, tests/ansible_collections/roles/add-custom-repos/rhel7-repos.yml, tests/ansible_collections/roles/add-custom-repos/rhel8-repos.yml
We have custom repos on machines provided via libvirt. However in the future we want to run tests on machines provided by Artemis or anything else. Those clean vms do not have custom repos. This PR solve this issue.
Solves [OAMG-5485](https://issues.redhat.com/browse/OAMG-5485).
=> Add ansible role to set up custom repo for int tests

.packit.yaml
*Btw, I see you use pre-commit. Do you know https://pre-commit.ci ?*
=> [packit] test in the internal TF

convert2rhel/breadcrumbs.py
This piece of code was not Python 2.6-compatible so it was failing on CentOS/Oracle Linux 6 .
=> Fix cli option sanitization for py2.6

CONTRIBUTING.md, Makefile
Docker doesn't work everywhere because the version of docker sometimes
needs cgroups v1 but the system is using cgroups v2.  In those places,
podman seems to work fine.
* Give users the ability to specify what docker command to use (ie:
make install DOCKER=podman)
* Autodetect in the Makefile whether there's a working podman or docker
if the user did not specify one.  Note that this uses some GNU make
extensions ($warning).
=> Add support for podman to the Makefile

.packit.yaml
A [convert2rhel specific workaround in packit service](https://github.com/packit/packit-service/pull/1225) has been [reverted](https://github.com/packit/packit-service/pull/1269/commits/3ac2a002308aead558f0c94f88078364f39b78de) because packit service now supports specifying of the [build target to test distros mapping in the config](https://github.com/packit/packit/pull/1407).
Do not merge yet. The change in packit service will be deployed to production next Tuesday, 16th of November, which is the date you should merge this - I'll ping you (if I don't forget ;) )
The [packit.dev docs will be updated](https://github.com/packit/packit.dev/pull/350) once the change is deployed.
=> Explicitly specify distros to test build targets on

convert2rhel/logger.py, convert2rhel/main.py, convert2rhel/unit_tests/conftest.py, convert2rhel/unit_tests/logger_test.py, convert2rhel/unit_tests/main_test.py
This PR aims to add the ability to archive old log files before a new run. 
For example: 
* /var/log/convert2rhel/archive/convert2rhel-1635162445070567607.log
* /var/log/convert2rhel/archive/convert2rhel-1635162478219820043.log
The name chosen for the new file is based on the previous log file name (eg; convert2rhel.log), but with an appended timestamp to it. This timestamp is relative to the last modified date (Which means, the last command sent to the log file).
Beware, this PR is also linked to the [sosreport/sos - PR#2734](https://github.com/sosreport/sos/pull/2734) as we have to include the archived logs in the sosreport tool.
Ticket reference: https://issues.redhat.com/browse/OAMG-5458
=> Add archive to old log files

tests/integration/tier0/inhibit-if-kmods-is-not-supported/test_kmods_not_supported.py
Inside the kmod integration test we call `modprobe -r` command which can sometimes remove unused dependency modules. This can result in multi-line output string thus the assert in the test can fail. This PR replaces the output for return-code assert.
=> Fix tests after RHEL8.5 release

Makefile
When I run the tests in containers on my machine, I get a permission error for some tests (cert_test.py) because they perform a validation of the test certificates are read/write, and as we are setting up our current project directory in the container , the same goes there as `root:root`.
This fix is intended to run the tests as the root user inside the container, as this is a simple change and as this command is only run locally, I believe it should solve the problem.
I also added another command to run the tests in the CentOS7 container.
Here's the output before the fix: 
<details>
<summary>Click to expand.</summary>
```bash
(.venv3) [r0x0d@fedora convert2rhel]$ make tests8
============================= test session starts ==============================
platform linux -- Python 3.6.8, …
```
=> Change running user to `root` when running tests on container

convert2rhel/main.py, convert2rhel/redhatrelease.py, convert2rhel/unit_tests/redhatrelease_test.py
This PR aims to add the ability to make an backup of the file `/etc/os-release` during the conversion process
Ticket reference: https://issues.redhat.com/browse/OAMG-5457
=> /etc/os-release file backup

ansible/ansible-convert2rhel.yml
Updated compability of Ansible Preflight Check to Support CentOS / Oracle Linux 8.5 since CentOS 8.5 was recently released. I tested the playbook and it worked perfectly with 8.5, even fixed some bugs that are currently open as issue, for instance #366.
=> ✨ Updated Versions of Ansible Preflight Check

convert2rhel/pkghandler.py
This change removes two places where we use a set as a default value.
Mutable containers should not be used as default arguments as they are
created when the function is defined (basically, the first time the
module is imported) and then that one instance is used anytime the
method is invoked without that argument specified.  This means that
changes to the container will persist to the next time the function is
invoked.
<strike>This change seems to fix a bug we're seeing on oracle7 where we assemble
a list of packages to downgrade that includes gcc & gcc-c++ but then we find
that systemd is a protected package.  At that point, the list of
packages to downgrade seems to revert to just systemd and we build up
the list again.  This time, when we see that gcc is going to be
downgraded but …
=> Avoid mutable types as default args.

convert2rhel/pkghandler.py, convert2rhel/unit_tests/data/pkghandler_yum_distro_sync_output_expect_deps_for_3_pkgs_found.txt, convert2rhel/unit_tests/pkghandler_test.py, tests/integration/tier1/resolve-dependency/install_dependency_packages.py
The regular expression that was being used to parse package names out of
yum output was missing gcc-c++, NetworkManager, and other package names.
Using a simpler regex and a function that parses the package names from
the rest of the NVR should fix that.
This fixes a user visible problem where packages like gcc-c++ can cause
convert2rhel to fail to downgrade packages.  This is because gcc-c++
would be missed by the regex and thus we'd be unable to figure out that
we need to downgrade gcc-c++ when at the same time as we downgrade gcc.
Resolves [OAMG-6136](https://issues.redhat.com/browse/OAMG-6136).
=> Fix detection of gcc-c++ and other package names.

convert2rhel/breadcrumbs.py
Found some typos on `breadcrumbs.py` file. Didn't want to commit them while fixing another problem for #382.
=> Fix minor typos in breadcrumbs.py

convert2rhel/breadcrumbs.py
This PR changes how the timestamp output is presented in the
/etc/migrations-results is presented on the file.
Before, it used `gmlocal()` which outputs the current time in GMT, now, this
file will have `utcnow()` timestamp output to be more equal on how leapp do
their breadcrumbs.
with gmlocal():
"activity_started": "20211201T1810GMT",
"activity_ended": "20211201T1811GMT",
with utcnow():
"activity_started": "2021-12-02T11:56:07.425477Z",
"activity_ended": "2021-12-02T11:56:59.478299Z",
Reference ticket: https://issues.redhat.com/browse/OAMG-6139
=> Change timestamp format for breadcrumbs

convert2rhel/checks.py
This change improves the command used to set a default non-uek kernel on the Oracle Linux systems.
```bash 
[root@c2r-20211014113529 ~]# rpm -qa kernel
kernel-2.6.32-696.el6.x86_64
kernel-2.6.32-754.22.1.el6.x86_64
kernel-2.6.32-754.35.1.el6.x86_64
```
Sorted kernel versions by the latest build
```bash
[root@c2r-20211014113529 ~]# rpm -q --qf="%{BUILDTIME}\t%{EVR}.%{ARCH}\n" kernel | sort -nr | head -1 | cut -f2
2.6.32-754.35.1.el6.x86_64
```
Detailed output with the `BUILDTIME` query format parameter 
```bash
[root@c2r-20211014113529 ~]# rpm -q --qf="%{BUILDTIME}\t%{EVR}.%{ARCH}\n" kernel | sort -nr 
1602098698	2.6.32-754.35.1.el6.x86_64
1568226128	2.6.32-754.22.1.el6.x86_64
1490222097	2.6.32-696.el6.x86_64
```
Installed kernel versions
```bash
[root@c2r-20211014110341 ~]# rpm -qa kernel …
```
=> Improve rpm query to sort out the latest kernel version

convert2rhel/logger.py
This change provides a more human-readable string to append in the archive log instead of the unix-timestamp previously used in the archive log file names.
Based on the @bocekm comment: https://github.com/oamg/convert2rhel/pull/359#issuecomment-980469344
=> Archived logfile name to include UTC timestamp

convert2rhel/utils.py
Not setting the LANG was causing the RHSM registration to fail because subscription-manager considers LANG to have priority over LC_ALL. That goes against [POSIX which specifies that LC_ALL overrides LANG](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08_02). So even though we were setting LC_ALL to C which should warrant only ASCII output, the output of subscription-manager contains non-ASCII characters.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2022854
=> Set LANG env var to C the same as LC_ALL

convert2rhel/pkghandler.py, convert2rhel/unit_tests/pkghandler_test.py, plans/tier1.fmf, tests/integration/conftest.py, tests/integration/tier1/yum-distro-sync/add-extras-repo/main.yml, tests/integration/tier1/yum-distro-sync/add-extras-repo/oracle7.yml, tests/integration/tier1/yum-distro-sync/add-extras-repo/oracle8.yml, tests/integration/tier1/yum-distro-sync/install_problematic_package.py, tests/integration/tier1/yum-distro-sync/main.fmf, tests/integration/tier1/yum-distro-sync/test_yum_distro_sync.py
On RHEL 8 based systems the `yum distro-sync` command returns 1 when no package passed to it is available in the enabled RHEL repositories. Convert2RHEL did not account for this situation because there's essentially "nothing to do" so it expected return code 0 (the same as when for example trying to update a package).
We have these 2 case when running distro-sync on RHEL 8 based systems:
- If all of the packages passed to distro-sync are unavailable in the enabled repos, yum returns 1 with a message `Error: No packages marked for distribution synchronization.`
- If at least one package from those passed to distro-sync is available in the enabled repos, yum returns 0. No problem occurs in this case.
On top of that, yum distro-sync behaves differently on RHEL 7 and 8. On RHEL 7 yum returns …
=> Fix yum distro-sync problem

convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py, tests/integration/tier0/backup-release/test_backup_release.py
I changed what happens when the conversion can't rollback the rpm files. it now prompts the user after letting them know that the conversion couldn't rollback the packages and shows them the packages that couldn't be rolledback and then prompts the user to see if they want to continue of not.
Fixes OAMG-5463
=> Halt when unable to download backup

.github/dependabot.yml
Add a really simple configuration for dependabot, it tracks down the
`actions` and `pip` dependencies to keep them up-to-date.
Jira reference: https://issues.redhat.com/browse/OAMG-6328
=> Add dependabot.yml for keeping track of deps

tests/ansible_collections/roles/oracle-linux-specific/tasks/boot_standard_kernel.yml, tests/integration/tier0/inhibit-if-oracle-system-uses-not-standard-kernel/ansible/install_unbreakable_kernel.yml
The regex inside the integration test `inhibit-if-oracle-system-uses-not-standard-kernel` stopped working. We decided to simplify it and also change a similar regex in other place so it has the same approach.
This PR fixes this issue.
=> Fix regex in integration test for OL not standard kernel

convert2rhel/checks.py, convert2rhel/grub.py, convert2rhel/pkghandler.py, convert2rhel/redhatrelease.py, convert2rhel/subscription.py, convert2rhel/systeminfo.py, convert2rhel/unit_tests/__init__.py, convert2rhel/unit_tests/grub_test.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/subscription_test.py, convert2rhel/unit_tests/systeminfo_test.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py
Security hardening: change the run_subprocess() function to take the command as a list instead of a string.
This is complete and ready for review. @Andrew-ang9 and I have been working on this together.
Implements: https://issues.redhat.com/browse/OAMG-6183
=> Port run_subprocess to take the command as a list instead of a string.

Dockerfiles/centos8.Dockerfile, Dockerfiles/rpmbuild.centos8.Dockerfile
The CentOS 8 reached EOL in december and archived all their mirorrs from
mirrors.centos.org to vault.centos.org, this broke our CI system and fresh local
development images as well.
Jira reference (If any): https://issues.redhat.com/browse/OAMG-6445
=> Update CentOS 8 mirrors in Dockerfile

Makefile, convert2rhel/unit_tests/README.md
This small improvement is to allow us to pass different parameters to the pytest
runner without having to modify anything in the Makefile when necessary.
For example, we can do `make tests EXTRA_ARGS="-k test_efibootinfo"` to test only
this specific test inside the centos7 and 8 containers.
Jira reference (If any): https://issues.redhat.com/browse/OAMG-6434
=> Add EXTRA_ARGS to Makefile

tests/ansible_collections/roles/update-system/tasks/update-system.yml
Scenario:
We make a request to a testing farm and tell it to install artifact (convert2rhel package). TF then install this package in artifact installation phase. This happens before the the preparation phase in our playbook (`plans/main.fmf`). If the installed package is not the latest version inside the copr repo it then will be updated during our playbook installation. This would break the test case where we want to test specific version of the package (eg. some older PR build).
=> Do not update convert2rhel package during test preparation step

ansible/run-convert2rhel.yml, ansible/setup-convert2rhel.yml
We may start pointing end users at these playbooks to install and run
convert2rhel.  An end user may want to setup the environment separately
from running convert2rhel so we need to split the two steps into
separate playbooks.
The idea of modifying CentOS 8.5 systems to use vault repositories prior
to running convert2rhel was the prompt for doing this.
Note, @tabowling, this PR is only for the split, not the other things that we talked about doing in the meeting.  IIRC, those were:
* Use activation key instead of rhsm username and password
* Point users at documentation on setting an activation key
* Add the ability to give the activation key in a file instead of at the command line.
* If the user is on CentOS 8.5, make sure their repositories are pointed at vault rather than …
=> Split ansible playbook into setup and executing stages.

Dockerfiles/centos8.Dockerfile, Dockerfiles/rpmbuild.centos8.Dockerfile, tests/ansible_collections/roles/install-submgr/install_submgr_from_centos_8.yml, tests/integration/tier1/remove-all-submgr-pkgs/ansible/install_submgr_8.yml, tests/integration/tier1/yum-distro-sync/add-extras-repo/oracle8.yml
It seems that the protocol in C8 URLs changed from `http` to secure `https`. Let's see if this fixes the issues.
=> Change http to https for CentOS8 URLs

plans/tier0.fmf, tests/integration/tier0/check-privileges/main.fmf, tests/integration/tier0/check-privileges/test_user_privileges.py
Run as a basic user and check for the program to exit as it is required to run as root.
Relates to https://github.com/oamg/convert2rhel/pull/81.
=> Add integration test to verify requiring root

.github/dependabot.yml
On these systems pylint 2.x.x is not available.
I'm not sure if Dependabot is going to ignore the 1.x.x version we use. Maybe the ignore clause checks only the version it would update the dependency **to** (not **from**).
=> Ignore pylint 1.x.x we use for CentOS Linux 6/7

plans/main.fmf, plans/tier1.fmf, tests/ansible_collections/reboot.yml, tests/ansible_collections/roles/oracle-linux-specific/tasks/boot_standard_kernel.yml, tests/ansible_collections/roles/reboot/main.yml, tests/ansible_collections/roles/update-system/tasks/update-system.yml, tests/ansible_collections/update_templates.yml
As @mkluson suggested in the https://issues.redhat.com/browse/OAMG-6415 we can try add extra steps for reboot steps. The problem may be that the system reboots correctly, however the ansible play has trouble connecting back to the machine. 
This PR:
- use extra steps to the reboot role so it's able to reconnect to the machine
- there were 3 places where we had a reboot role implemented. Instead use just one role, so it's easier to maintain. This requires updating all test plans that use reboot.
- remove update_templates.yml file as it is not used anymore. We have an update role already.
=> Fix rebooting machines

.github/dependabot.yml, requirements/centos6.requirements.txt
We currently don't run anything (tests/analysis) on CentOS Linux 6.
Also, the dependabot ignore clauses do not work as we expected - it ignores just the versions to be updated to, not those to be updated from.
=> Remove unused CentOS Linux 6 pip deps file

CONTRIBUTING.md, Makefile, requirements/local.centos8.requirements.txt, tests/integration/README.md
We don't run integration tests locally anymore - we run them just in the Testing Farm nowadays.
=> Remove unused local integration testing

.packit.yaml
Since CentOS 8 reached EOL the repositories were quite unstable. We
decided to disable running tests in upstream CI until this issue gets
resolved. See OAMG6499 and OAMG-6535 for more information.
=> Disable CentOS 8 integartion tests in upstream CI

plans/tier0.fmf, tests/integration/tier0/backup-release/test_backup_release.py, tests/integration/tier0/inhibit-if-kmods-is-not-supported/ansible/files/Makefile, tests/integration/tier0/inhibit-if-kmods-is-not-supported/ansible/files/my_kmod.c, tests/integration/tier0/inhibit-if-kmods-is-not-supported/ansible/main.yml, tests/integration/tier0/inhibit-if-kmods-is-not-supported/test_kmods_not_supported.py, tests/integration/tier0/resolve-broken-ol8-rollback/test_resolve_broken_ol8_rollback.py, tests/integration/tier1/one-kernel-scenario/install_one_kernel.py, tests/integration/tier1/set-locale/use_non_english_language.py, tests/integration/tier1/yum-distro-sync/install_problematic_package.py, tests/integration/tier1/yum-distro-sync/test_yum_distro_sync.py
This PR adds an integration test verifying that the conversion stops when there's a loaded kernel module marked as tainted. Test builds own kernel module on the testing machine and use it. Kernel is then marked with appropriate flags which makes the kernel 'tainted'. 
This kernel module causes following flags:
- P - proprietary module was loaded
- O - externally-built (“out-of-tree”) module was loaded
- E  - unsigned module was loaded
Conversion of tainted kernel is then inhibited.
Ref. ticket [OAMG-4927](https://issues.redhat.com/browse/OAMG-4927).
=> Add test for tainted kernel inhibitor

convert2rhel/logger.py, convert2rhel/unit_tests/logger_test.py, convert2rhel/utils.py
For log messages, you can do lazy evaluation of the format string to
occassionally boost performance when a log message is not used.  For
instance:
``` python
class Hypothetical(object):
def __str__(self):
return self.calculate_fibonacci_10000()
log.debug("10,000th fibonacci number is: %s", Hypothetical())
```
The format string will not be interpolated (and thus the 10,000th
fibonacci number will not be calculated) unless we are actually going to
log the debug() output.
The code in commit b870460 broke that because it calculated its own
format string and args for the message, interfering with whatever was
passed in via function parameter.  This change fixes that by moving the
formatting pieces of b870460 into the CustomFormatter class.  By that
time, the message string has already been …
=> Fix lazy evaluation of string logs for loglevel.FILE

pyproject.toml
Branch coverage tests that the tests cover when a condition is true and
when it is false, even if both branches do not have statements.  This is
useful, for instance, when one branch doesn't set all the variables that
another branch does.  For instance:
def function(allow):
if allow:
variable = True
return variable
def test_function():
assert function(True) is True
With just statement coverge, the function would read as 100% covered.
Turning branch coverage on will show that the allow=False case is
untested.  Writing a test for that will reveal the bug where variable is
not set when it is returned: https://coverage.readthedocs.io/en/6.3.2/branch.html
=> Turn on collection of branch coverage

convert2rhel/grub.py
One of the arguments to the command was an int instead of a string.
This didn't cause a problem for run_subprocess() itself but caused
loggerinst.debug() to error when it tried to format the log message
using the argument list.  This change will convert the int to a string
before calling run_subprocess()
=> Fix arguments to run_subprocess to be a list of strings.

.packit.yaml
and be able to specify the precise list of deps needed to create the
SRPM and since you don't need any extra, we "have to" enforce
this process by defining the `srpm_build_deps` key.
=> packit: build SRPM in Copr

.github/workflows/coverage.yml, requirements/centos7.requirements.txt
Enabling the CentOS 7 docker build to run and send coverage do codecov.io
Jira reference (If any): https://issues.redhat.com/browse/OAMG-6611
Bugzilla reference (If any): 
=> Add CentOS 7 to coverage

.packit.yaml
Try to re-enable testing of centos-8 in upstream CI. Monitor the tests and see if it is having infrastructure errors.
=> Re-enable tesing on CentOS-8

CONTRIBUTING.md, convert2rhel/pkghandler.py, convert2rhel/subscription.py, convert2rhel/unit_tests/subscription_test.py, tests/integration/tier0/test-check-rollback-handling/test_check_rollback_handling.py
The changes proposed here are intended to solve a problem that involves
the way we deal with SIGINT signals that are captured and processed by
subprocesses or third-party libraries.
This commit solves two problems, the first being regarding the
`subscription-manager` subprocess managing the SIGINT signals and the
second, this time being `librpm` intercepting such signals internally in
its C code.
Jira reference (If any): https://issues.redhat.com/browse/OAMG-5756
=> Add checks for handling SIGINT events

convert2rhel/checks.py, convert2rhel/unit_tests/checks_test.py
Update the secure boot message to point out the user on how to disable secure
boot as it is not currently available in convert2rhel.
Jira reference (If any): https://issues.redhat.com/browse/OAMG-6665
=> Update the Secure Boot message

.packit.yaml
This reverts commit ea07315c91641fe4aae704c688aa2e7a76b539b8.
Related: https://github.com/packit/packit-service/issues/1450
=> Revert "[packit] Share the get-current-version action between jobs"

convert2rhel/logger.py, convert2rhel/unit_tests/logger_test.py
This PR introduces a fix for the log archival introduced in the
[PR#359](https://github.com/oamg/convert2rhel/pull/359).
The feature introduced there did a `copyfile` instead of a `move` to the
`archive` directory, wich was not the expected way of archiving a log.
Using a `copyfile` instead of a `move` causes the log file to be copied to the
`archive` directory as expected, but we still keep appending the log to the
`convert2rhel.log` file.
Jira reference (If any): https://issues.redhat.com/browse/RHELC-566
=> Fix old logs archival

convert2rhel/checks.py, convert2rhel/main.py, convert2rhel/pkghandler.py, convert2rhel/unit_tests/checks_test.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py, plans/tier1.fmf, tests/integration/main.fmf, tests/integration/tier0/backup-release/test_backup_release.py, tests/integration/tier1/convert-offline-systems/run_conversion.py, tests/integration/tier1/method/activation_key.py, tests/integration/tier1/one-kernel-scenario/install_one_kernel.py, tests/integration/tier1/one-kernel-scenario/run_conversion.py, tests/integration/tier1/set-locale/use_non_english_language.py, tests/integration/tier1/system-up-to-date/install_non_latest_kernel.py, tests/integration/tier1/system-up-to-date/main.fmf, tests/integration/tier1/system-up-to-date/test_non_latest_kernel_inhibitor.py, tests/integration/tier1/system-up-to-date/test_system_up_to_date.py
This PR aims to add a couple of checks before the conversion runs. The checks will prevent the conversion from falling before the process is finished. 
The checks are the following: 
* Check if all the system packages are updated (Through yum/dnf API calls) in enabled repos
* Check if the booted kernel is at the latest version (Through a comparison between `rpm` and `uname`)
If both of the conditions are met, then the conversion will proceed normally in the workflow.
Ticket reference: https://issues.redhat.com/browse/OAMG-4659
Linked ticket: https://issues.redhat.com/browse/OAMG-4709
=> Add live kernel version checks and package status

.packit.yaml
The Fedora Copr is going to remove Oracle Linux chroots and we'll be
left with EPEL chroots only. However we can use the an EPEL copr build
for tests on both CentOS Linux and Oracle Linux.
This change removes our dependence on the soon-to-be-removed oraclelinux
chroots.
Related: https://github.com/packit/packit-service/issues/1123
=> Map multiple TF distros to one copr build

convert2rhel/main.py, convert2rhel/systeminfo.py, convert2rhel/unit_tests/__init__.py, convert2rhel/unit_tests/breadcrumbs_test.py, convert2rhel/unit_tests/grub_test.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/redhatrelease_test.py, convert2rhel/unit_tests/systeminfo_test.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py, tests/integration/tier0/check-custom-repo/test_custom_repos.py, tests/integration/tier0/inhibit-if-oracle-system-uses-not-standard-kernel/test_oracle_bad_kernel.py, tests/integration/tier1/changed-yum-conf/test_patch_yum_conf.py, tests/integration/tier1/method/custom_repos.py, tests/integration/tier1/method/satellite.py, tests/integration/tier1/one-kernel-scenario/remove_other_kernels.py, tests/integration/tier1/remove-excluded-pkgs/test_remove_excluded_pkgs.py, tests/integration/tier1/resolve-dependency/install_dependency_packages.py
There was some unused imports left in a few files across the database.
I got a list of the files with the unused imports by running flake8 against the
`main` branch.
```bash
flake 8 convert2rhel/ > result.txt
cat result.txt | grep F401
```
For the integration tests: 
```bash
flake 8 tests/ > result.txt
cat result.txt | grep F401
```
=> Remove some unused imports across the codebase

ansible/setup-convert2rhel.yml
This fix adds a check if on CentOS8 and performs the needed steps to switch repos to vault.centos.org.
=> Fix for unavailable repos on CentOS8

ansible/run-convert2rhel.yml
Avoid passing the rhsm password to convert2rhel on the cli.
Fixes https://issues.redhat.com/browse/RHELC-396
=> Use a password file instead of passing rhsm password on the cli.

convert2rhel/subscription.py, convert2rhel/unit_tests/subscription_test.py
To be able to install the subscription-manager packages, we download
them from the Universal Base Image (UBI) 8 BaseOS publicly available
repository. This repository has been recently updated with packages
corresponding to RHEL 8.6 packages.
When trying to install these downloaded RHEL 8.6 subscription-manager
packages on CentOS/Oracle Linux 8.5 and older, the installation fails
because dnf-plugin-subscription-manager depends on
libjson-c.so.4(JSONC_0.14)(64bit). This symbol is newly available in
RHEL 8.6 json-c package and is not available in the json-c package
distributed with CentOS Linux/Oracle Linux/RHEL 8.5 and older.
For this reason we need to download and install the newer json-c package
version from the UBI 8 repository.
=> Install json-c from UBI 8

convert2rhel/subscription.py, convert2rhel/unit_tests/subscription_test.py, plans/tier1.fmf, tests/integration/tier1/removed-pkgs-centos-85/ansible/install_removed_pkgs_from_centos_85_repos.yml, tests/integration/tier1/removed-pkgs-centos-85/main.fmf, tests/integration/tier1/removed-pkgs-centos-85/test_removed_pkgs_centos_85.py
Right now the `subscription-manager-initial-setup-addon` package exists in CentOS Linux 8.4, but was removed from CentOS Linux 8.5. That is causing a conversion error when that package is present on a CentOS Linux 8.5 system because convert2rhel is unable to back it up for rollback purposes.
The simplest fix to this is not backing up the package when we remove it as the backup process uses `yumdownloader` and therefore, `yumdownloader` uses any enabled repos that are present on the system.
This primary scenario to cover:
1. I have CentOS Linux 8.4 and I install subscription-manager-initial-setup-addon (it's available in the default repos)
2. I update the system to 8.5 (and I still have the package installed)
3. I run convert2rhel and shouldn't fail on backing up the package as it's N/A in …
=> Do not back up subscription-manager-initial-setup-addon

convert2rhel/pkghandler.py, convert2rhel/unit_tests/pkghandler_test.py
Using YumBaseCli caused doubling of every log message on the output.
The reason is that instantiating of the YumBaseCli class includes calling logging.basicConfig() which sets up handlers on the root logger.
It is possible to use the YumBase class, which does not affect logging, to get the same data - list of packages having updates available.
The YumBaseCli logging handlers interfered with the convert2rhel logging as we use propage=True to be able to use caplog in our unit tests:
https://github.com/oamg/convert2rhel/pull/179
=> Use YumBase instead of YumBaseCli to get pkg updates

convert2rhel/special_cases.py, convert2rhel/unit_tests/special_cases_test.py, plans/tier1.fmf, tests/integration/tier1/resolve-dependency/install_dependency_packages.py
This package is causing problems when replacing the package `iwl7260-firmware`
to it's RHEL counterpart.  The reason for that is in OL8 they splitted the
package `iwl7260-firmware` and the `iwlax2xx-firmware` the later became a
dependency of the former. In RHEL this is not true, there is only the package
`iwl7260-firmware` which contains all the files.
Jira reference (If any): https://issues.redhat.com/browse/RHELC-567
=> Exclude iwlax2xx-firmware dependency from the conversion in OL8

plans/tier0.fmf, tests/integration/tier0/basic-sanity-checks/main.fmf, tests/integration/tier0/basic-sanity-checks/test_basic_sanity_checks.py, tests/integration/tier0/check-privileges/main.fmf
As a part of morf tool decommission add some basic sanity checks to the
integration tests using tmt.
- check for manpage
- basic smoke test
Rename the test scenario previously named as check-privileges and add
mentioned above.
=> Add basic sanity checks

convert2rhel/subscription.py, convert2rhel/unit_tests/subscription_test.py
In a case where the system registration using --org and --activationkey failed, the logging message _"Trying again - provide username and password."_ didn't make sense because we're not asking in that case for a username and a password.
Also I moved printing the _"Gathering subscription-manager registration info"_ to be under the "Attempt 2 of 3: Registering" because the info gathering is actually already part of the next attempt.
Original output:
```
[05/18/2022 18:27:13] TASK - [Convert: Subscription Manager - Subscribe system] *****************
Gathering subscription-manager registration info ... 
... organization detected
... activation key detected
Registering the system using subscription-manager ...
The system has been registered with ID: 8159c801-909d-4b96-9331-3c61e1dc31a5
The …
```
=> Improve logging of the rhsm registration

.github/workflows/coverage.yml
By default, the checkout github workflow will rebase the PR onto the
HEAD of main before running.  This is generally what you want because it
is testing the state your main branch would be in after you merge the
PR.  However, there is a problem with that for codecov.io.  Coverage.io
uses the tree at the branch point to decide what the previous coverage
was and also what the line numbers are.  If we generate the coverage
data using the HEAD of the main branch, then codecov.io will display
the wrong lines as being covered or uncovered.  This will lead it to
think that lines which were previously covered are no longer, which
makes leadds to false positives and makes it hard to tell what has
actually changed.
Changing the checkout action to use the branch point fixes this.
(We also tried to …
=> Have the unittest run that makes coverage use the branch point.

Dockerfiles/centos6.Dockerfile, Makefile, convert2rhel/breadcrumbs.py, convert2rhel/systeminfo.py, convert2rhel/unit_tests/backup_test.py, convert2rhel/unit_tests/cert_test.py, convert2rhel/unit_tests/checks_test.py, convert2rhel/unit_tests/conftest.py, convert2rhel/unit_tests/grub_test.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/redhatrelease_test.py, convert2rhel/unit_tests/special_cases_test.py, convert2rhel/unit_tests/subscription_test.py, convert2rhel/unit_tests/systeminfo_test.py, convert2rhel/unit_tests/toolopts_test.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py, requirements/centos6.requirements.txt, requirements/centos6_pre.requirements.txt, scripts/centos6_pip_prep.sh
Mainly in unit test there was used a condition for importing the corresponding variant of module for python 2 or 3, if they have different names. The better way is to use the `six` library.
Changed the conditions to imports through `six`, removed partial compatibility with Python 2.6 (just in some of unit test, not in all of them - module `unittest2`), removed unused imports in tests and small improvement of `utils.py`: changed deprecated `warn` to `warning` which caused deprecated error in unit tests.
RHELC-588
=> Improve of Python 2 & 3 compatibility

.github/workflows/coverage.yml, tests/ansible_collections/roles/add-custom-repos/main.yml, tests/ansible_collections/roles/install-submgr/main.yml, tests/integration/tier1/yum-distro-sync/add-extras-repo/main.yml
import_playook is almost the same thing.  Replace usage of toplevel
include with import_playbook.
=> The new version of ansible-core has removed support for toplevel include

.packit.yaml
=> Oracle Linux 8.6 in upstream CI

ansible/setup-convert2rhel.yml
Fixes two playbook issues.  These issues prevented the ansible playbook from converting centos machines.  People could still run convert2rhel from the command line.
*   Fix syntax of looping over centos8_repos. As reported in #533, the loop syntax we have in the ansible playbook is
not quite right.  Instead of simply writing the variable name as we have it now, we are responsible for asking for it to be expanded in the loop construct (using "{{ }}").
Fixes #533
*  Fix setup playbook feature allowing user to skip os version check. As reported in #532, the logic in the ansible playbook was to fail when either the version check showed an unhandled version OR the skip_os_version_check was set to true. This meant that the toggle would either check the version or the playbook will fail.
By …
=> Playbook fixes

convert2rhel/checks.py, convert2rhel/unit_tests/checks_test.py
adds a unit test to catch where the tag "{{NAME}}" has an extra set of curly brace.
This error was fixed in the PR https://github.com/oamg/convert2rhel/pull/389
if you'd like to test this use the commit hash 31a304c63f815efe77fa32170a7f3d253a559310 to use the istant with the error
and use commit hash 9a1c5f50e44d2a098e2458263580d748e7ba6282 for the fix for this error
Jira ticket: [RHELC-126](https://issues.redhat.com/browse/RHELC-126)
=> Stop if the booted kernel is not owned by any package

renovate.json
Ignoring CentOS Linux 6 dependencies in requirements file as we don't want to update them.
This also only allows 7.0.x updates for pytest with centos8 requirements file
=> [RHELC-640] chore(renovate): Ignore CentOS 6 deps

packaging/convert2rhel.spec
Change a few conditions which were only True of RHEL8 to be True on
RHEL8 and above.
=> Allow for RHEL9 builds in the rpm spec file.

convert2rhel/cert.py, convert2rhel/unit_tests/cert_test.py, convert2rhel/unit_tests/conftest.py, pytest.ini, tests/integration/tier0/basic-sanity-checks/test_basic_sanity_checks.py
RHSM was throwing an logging error when removing the current certs on the system, this error was not supposed to be displayed at this moment in the conversion because it might've not been installed yet.
If you want to test this fix, you can follow the steps in the Jira ticket and observe that the error message doesn't appear anymore.
Jira: [RHELC-45](https://issues.redhat.com/browse/RHELC-45)
=> [RHELC-45] Fix an error logged when removing an RHSM cert

MANIFEST.in, config/convert2rhel.ini, convert2rhel/toolopts.py, convert2rhel/unit_tests/toolopts_test.py, packaging/convert2rhel.spec, plans/tier1.fmf, tests/integration/tier1/checks-after-conversion/test_release_version.py, tests/integration/tier1/config-file/main.fmf, tests/integration/tier1/config-file/test_config_file.py
Add the possibility to give secrets (password or activation key) via configuration file. Configuration file can be 1) user specified and passed via command line or is in 2) ~/convert2rhel.ini, 3) /etc/convert2rhel.ini. The numbers shows priority, 1) is the highest.  The structure of the file is copied to /etc/convert2rhel.ini during installation.
Secrets passed by CLI have precedence and are merged with the secrets in config files. If password is passed via CLI and activation key is in config file, the activation key isn't used. If it would be, during the activation process would be used the activation key and the precedence of secrets from CLI wouldn't be preserved. If there are both, the activation key has priority.
Also contains warnings if user specifies more than one authentication …
=> [RHELC-411, RHELC-413] Add the config file option

packaging/convert2rhel.spec
In https://github.com/oamg/convert2rhel/pull/223 we introduced support for UEFI-based system conversions. With that we call the efibootmgr utility on a couple of places. Yet, we don't require the utility to be installed and that might lead into unwanted behaviour of convert2rhel.
I've verified that the package is named the same across all major versions of RHEL we allow converting.
Jira: https://issues.redhat.com/browse/RHELC-673
=> [RHELC-673] convert2rhel rpm to require efibootmgr installed

convert2rhel/unit_tests/conftest.py, convert2rhel/unit_tests/logger_test.py, convert2rhel/unit_tests/subscription_test.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py
For some of the programs we run, we have to set the terminal size before the process starts.  In the past we've done this by subclassing pexpect.spawn on all platforms.  Newer pexpect gives us the dimensions parameter to spawn() to do this in a better way.  This change will use dimensions.spawn() when available and our hack when it is not.
Fixes [RHELC-570](https://issues.redhat.com/browse/RHELC-570)
=> [RHELC-570] Cleanup pexpect terminal size

convert2rhel/special_cases.py, convert2rhel/unit_tests/special_cases_test.py, plans/tier1.fmf, tests/integration/tier1/handle-special-pkgs-case/main.fmf, tests/integration/tier1/handle-special-pkgs-case/test_handle_shim_x64_pkg.py
shim-x64 packages can be installed on systems that are running BIOS too,
so our previous workaround included only UEFI systems.
This commit removes that condition by backing up and removing the
shim-x64 package protection on both UEFI and BIOS now.
=> [RHELC-678] Remove UEFI condition from shim-x64 workaround

convert2rhel/data/7/x86_64/configs/centos-7-x86_64.cfg, convert2rhel/data/7/x86_64/configs/oracle-7-x86_64.cfg, plans/tier1.fmf, tests/integration/tier1/remove-excluded-pkgs/main.fmf, tests/integration/tier1/remove-excluded-pkgs/test_remove_excluded_pkgs.py
The gnome-documents-libs package is causing file conflicts with gnome-documents
during the package transaction as they both share similar files.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2043724
=> [RHELC-67] Add gnome-documents-libs to excluded packages

.packit.yaml
We introduced the `fix-spec-file` only as a workaround for https://github.com/packit/packit-service/issues/1601. The issue has been fixed on the packit side so the workaround is no longer needed.
Ccing @TomasTomecek.
=> Remove fix-spec-file from packit configuration

Dockerfiles/centos6.Dockerfile, Dockerfiles/centos7.Dockerfile, Dockerfiles/centos8.Dockerfile, Dockerfiles/rpmbuild.centos7.Dockerfile, Dockerfiles/rpmbuild.centos8.Dockerfile, convert2rhel/checks.py, convert2rhel/i18n.py, convert2rhel/logger.py, convert2rhel/subscription.py, convert2rhel/systeminfo.py, convert2rhel/toolopts.py, convert2rhel/unit_tests/__init__.py, convert2rhel/unit_tests/checks_test.py, convert2rhel/unit_tests/conftest.py, convert2rhel/unit_tests/subscription_test.py, convert2rhel/unit_tests/systeminfo_test.py, convert2rhel/unit_tests/toolopts_test.py, convert2rhel/utils.py, packaging/convert2rhel.spec, pytest.ini, tests/integration/tier0/check-cve-2022-1662/test_cve_fixes.py
Part of [RHELC-597](https://issues.redhat.com/browse/RHELC-597)
---
Using the dbus API to register, we're able to stop passing the
activation key over the commandline.
This also lets us avoid pexpect for invoking subscription-manager when
passing the password.
Note that this requires that dbus is installed and running and that the
dbus-python/python-dbus packages are installed.  This package is
available on RHEL6-RHEL9 clones (all that we care about) but is a new
dependency.  The subscription-manager rpm already requires dbus-python so when we install that, we should be installing sbud as well.  RHEL7 and above use systemd which requires that dbus be running.  So RHEL6 is the only place where we might have to install and start up DBus.  Since the supported migration would include …
=> [RHELC-597] Register with subscription-manager via dbus

.github/workflows/greetings.yml, .github/workflows/reuse-get-copr-id.yml, .github/workflows/reuse-int-tests.yml, .github/workflows/tmt-tests.yml, .packit.yaml, plans/main.fmf, scripts/get_copr_build_id.py
We are replacing the integration tests that run with packit to run with
a custom GitHub Actions workflow to prevent DDoS in Red Hat's internal
giltab.
=> [RHELC-635] Call integration tests through GitHub Actions

.github/renovate.json
Let renovate handle the github actions update too.
=> Enable `actions` manager for Renovate

.github/renovate.json
The manager for updating GitHub actions was supposed to be `github-actions`. Due to word-wrapping on the docs we thought it was just `actions`
https://docs.renovatebot.com/modules/manager/#supported-managers
=> chore: change `actions` to `github-actions`

.github/workflows/greetings.yml, .github/workflows/reuse-int-tests.yml, .github/workflows/tmt-tests.yml, .packit.yaml, plans/main.fmf
Follow-up work for the tft integration as a github actions instead of
packit integration.
The last PR #574 introduced the workflow and the reusable workflow files
that will permit us to continue the testing and validate that everything
works as expected as a github action.
- Proof: https://github.com/oamg/convert2rhel/pull/578 
=> [RHELC-635] Follow-up tft integration as github actions

.github/renovate.json
Renovate tries to open pull requests to update old centos dockerfiles to
it's newest version. While this behavior of renovate is the right one,
we don't want them to be updated as we need them to be on a older
version.
=> Ignore old dockerfiles in renovate

.github/workflows/reuse-int-tests.yml, .github/workflows/tmt-tests.yml
The tmt pipeline was failing because of incorrect matrix setup. This
should fix the issue as it generates the matrix in the correct json
syntax.
=> [RHELC-635] Fix errors from tmt pipeline

.github/workflows/reuse-int-tests.yml, .github/workflows/tmt-tests.yml
The `git_ref` property was missing the PR number because inside the
reusable workflow we didn't have the reference that holds the pull
request number.
This commit changes that behavior to get the issue number outside the
reusable workflow and pass it as a input.
=> [RHELC-635] Fix git_ref in reusable workflows

Makefile
When executing the RHEL6 unit_tests locally, our container outputs a lot of
logging text that is not necessary.
If the user still wants to print some other text that the tests may output, the
same can be overrided with `SHOW_CAPTURE=[fd|sys]`.
=> Prevent RHEL6 unit_tests to output logging text

convert2rhel/checks.py, convert2rhel/pkghandler.py, convert2rhel/subscription.py, convert2rhel/systeminfo.py, convert2rhel/unit_tests/subscription_test.py
Repositories should not be abbreviated to "repos" in user facing messages.
The GPG key message was mentioning "keys" being imported while it referred to a single key.
=> Improve GPG key import and repository-related messages

convert2rhel/special_cases.py, convert2rhel/unit_tests/special_cases_test.py
In PR #553 we removed a condition from the shim-x64 special case workaround
where it was only supposed to handle UEFI systems, and now we are handling BIOS
as well. The problem is that in the BIOS systems, this package may not be
installed at all.
This commit introduces a quick check to validate if the package is present on
the system before trying to backup it's protection file under
`/etc/yum/protected.d`.
=> Check if shim-x64 package is present in the system

.github/workflows/greetings.yml, .github/workflows/reuse-int-tests.yml, .github/workflows/tmt-tests.yml
This commit introduces the fix to the github actions that requests the
integration tests through a custom GitHub Actions.
- https://github.com/oamg/convert2rhel/pull/584
- https://github.com/oamg/convert2rhel/pull/582
- https://github.com/oamg/convert2rhel/pull/577
- https://github.com/oamg/convert2rhel/pull/574
The wait time for feedback is way less than with packit, that's because we are sending lots of requests to the tft API to run the tiers for each operating system we want. This way, we have the following matrix for our tests: 
| Tier 0     | Tier 1     |
|------------|------------|
| OL 7       | OL 7       |
| OL 8.4     | OL 8.4     |
| OL 8.6     | OL 8.6     |
| CentOS 7   | CentOS 7   |
| CentOS 8.4 | CentOS 8.4 |
| CentOS 8.5 | CentOS 8.5 |
You can check the wait time for …
=> [RHELC-635] Fix integration tests on github actions

.github/workflows/coverage.yml
Codecov checks were failing with this message:
"No token specified or token is empty"
Related:
https://github.com/codecov/codecov-action/issues/557#issuecomment-1225464370
=> Fix codecov checks by passing a token

.github/workflows/reuse-int-tests.yml, .github/workflows/tmt-tests.yml
This commit introduces an update to the `tmt-tests.yml` workflow to pass the HEAD sha to the `testing-farm-as-github-action` as an input.
It also pins the version to the latest commit introduced in this action in order to be able to use it right away.
=> Update tmt-tests workflow to pass the SHA from PR event

.github/workflows/coverage.yml
Token is removed as fork PRs can't access it - making it useless for our project. It also creates errors or simply assumes the fault is the token when it errors
Flags argument is added to separate the coverage for the three centos machines
Name is added to assign a name to the code coverage
=> chore(codecov): remove token and add more arguments

.github/workflows/tmt-tests.yml
With our current concurrency group, the PRs are conflicting with each other, if one PR is executing the tmt-tests.yml workflow, and then another PR receives an update and trigger the same workflow, the first one will stop executing as canceled.
Jira Issue: [RHELC-635](https://issues.redhat.com/browse/RHELC-635)
Checklist
=> [RHELC-635] Update concurrency group to prevent interference

convert2rhel/cert.py
We check whether we can access the certificate files shipped with convert2rhel prior to installing them.  The check for the directory they live in was checking whether the directory was readable and writable. We don't write to that directory, though, so the check shuld be whether the directory is readable and executable.
Note that convert2rhel should always be run by root so this bug won't be encountered in normal use.
This issue mentioned in:
Jira Issue: [RHELC-740](https://issues.redhat.com/browse/RHELC-740)
Checklist
=>  [RHELC-740] Fix permissions check for certificates.

.github/workflows/coverage.yml, .github/workflows/tests.yml, .gitignore, Makefile
Turning the `BUILD_IMAGES=1` to be the default option when running make commands locally, and turning this setting off when running inside the CI.
Checklist
=> Build images locally as default option

.github/workflows/tmt-tests.yml
The concurrency setting was preventing other PRs to run the same workflow.
Jira Issue: [RHELC-635](https://issues.redhat.com/browse/RHELC-635)
Checklist
=> [RHELC-635] Remove concurrency from tmt-tests workflow

.pre-commit-config.yaml
Add tmt-lint to verify correct fmf syntax.
For now introduce tmt-tests-lint, once we move away from GitLab hosted values, add tmt-plans-lint which is now failing due to SSL error whilst trying to reach to internal GitLab.
[RHELC-749](https://issues.redhat.com/browse/RHELC-749)
=> [RHELC-749] Add tmt-lint to pre-commit hooks

convert2rhel/utils.py
The name of the rpm we download during a package backup can be so long that the length of the line of 120 characters we set in the pseudo-terminal may not be sufficient. If the downloaded package file name (NEVRA.rpm) is too long, the yumdownloader truncates it and then our output parsing fails. That leads to not tracking the downloaded package and, more importantly, not installing the package back during a rollback.
Real world example of a truncated rpm name:
`libvirt-daemon-driver-storage-core-8.0.0-5.4.0.1.module+el8.6.0+20743+999ad699.x86_64.r 326 kB/s | 253 kB     00:00`
Jira Issue: [RHELC-760](https://issues.redhat.com/browse/RHELC-760)
Checklist
=> [RHELC-760] Increase the line length in a pseudo-terminal

Makefile
The `.images` target was changed to `.build-images` in https://github.com/oamg/convert2rhel/commit/7512287598a36ca80eab328c91a1e7b9cacc5f9c#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L66 and the `install` target should have been updated accordingly.
~~Jira Issue: [RHELC-]()~~ N/A
Checklist
=> Fix Makefile: .images no longer exists

convert2rhel/checks.py, convert2rhel/unit_tests/checks_test.py, tests/integration/tier1/system-up-to-date/test_system_up_to_date.py
The main reason for this change was a failing integration test. It had a period at the end of the expected warning message when in fact this period had been removed in
https://github.com/oamg/convert2rhel/pull/458/files#diff-cf19bc90f65d9e26e1b6fa7dcd84a18dfba097f65706e211a4f4ac71b1b467f6R504. For some strange reason the integration test for that PR passed at the time of merging.
~~Jira Issue: [RHELC-]()~~ N/A
Checklist
=> Do not use plural "packages" when there's just one

convert2rhel/logger.py, convert2rhel/toolopts.py, convert2rhel/unit_tests/logger_test.py
We had an issue before where we couldn't disable color output for systems that don't have color functionality. This meant output could look very cluttered
With this change we reimplement it using `NO_COLOR` environment variable
http://no-color.org/
Jira Issue: [RHELC-39](https://issues.redhat.com/browse/RHELC-39)
Checklist
=> [RHELC-39] fix: allow CI systems to disable color

plans/main.fmf
Set an environment variable NO_COLOR=1 for tests to align with changes in #622
Jira Issue: [RHELC-39](https://issues.redhat.com/browse/RHELC-39)
Checklist
=> [RHELC-39] Enable NO_COLOR for tests

convert2rhel/systeminfo.py
We use systemctl to tell us whether dbus is running on the system. When we do so, we don't want to directly emit the output of the systemctl command to the log as it is cryptic for the end user.
Fixes https://issues.redhat.com/browse/RHELC-729
Jira Issue: [RHELC-729](https://issues.redhat.com/browse/RHELC-729)
Checklist
=> [RHELC-729] Do not show output from systemctl show during systeminfo gathering.

Makefile
There was a leftover .env in #634 we didn't spot. This removes that so it
no longer errors out
Jira Issue: N/A
Checklist
=> fix: remove leftover .env file

convert2rhel/unit_tests/checks_test.py
unit_tests should be designed to work even when there isn't an internet connection (for security of downstream build systems).  Mock out system_info.has_internet_access since we are also mocking out the repoquery call which would require internet access to exist.
This is an extremely simple patch that just adjusts a unit test to not need internet access to function.
Checklist
=> Remove a unit_test dependency on having internet.

convert2rhel/checks.py, convert2rhel/unit_tests/checks_test.py, tests/integration/tier0/basic-sanity-checks/test_basic_sanity_checks.py
This PR was made to clean up PR #415, which was merged without taking care of some of the other comments that were left on the PR. Those comments weren't vital enough to stop the PR from being merged. 
All comments have been put in the Jira ticket and addressed for the first commit of this PR.
Jira ticket: [RHELC-670](https://issues.redhat.com/browse/RHELC-670)
=> [RHELC-670] Clean up new version check

convert2rhel/checks.py
In is_loaded_kernel_latest(), repoquery is subject to exclude= in /etc/yum.conf. If there is "exclude=kernel", the conversion can fail with the following:
CRITICAL - Could not find any kernel from repositories to compare against the loaded kernel.
This patch resolves that condition by explicitly disabling all "exclude" options with:
--setopt=exclude""
Signed-off-by: John Castranio <jcastran@redhat.com>
Jira Issue: [RHELC-772](https://issues.redhat.com/browse/RHELC-772)
Checklist
=> [RHELC-772] checks: Omit exclude= options from repoquery

convert2rhel/checks.py, convert2rhel/main.py, convert2rhel/pkghandler.py, convert2rhel/systeminfo.py, convert2rhel/unit_tests/checks_test.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/systeminfo_test.py, convert2rhel/unit_tests/toolopts_test.py, convert2rhel/utils.py, tests/integration/tier0/inhibit-if-kmods-is-not-supported/main.fmf, tests/integration/tier0/inhibit-if-kmods-is-not-supported/test_kmods_not_supported.py
These changes are cleanup of most of the things that were left behind from
PR #193.
Some of the functions were changed to make it easier to read and debug if
necessary, some of them were moved around to the files that made sense to place
they and some of them just needed a docstring to tell what the function was all
about.
This PR it is introduced a unit test for the function `get_enabled_rhel_repos`
since that was introduced in the past and never had a unit test tied to it.
Jira reference (If any): https://issues.redhat.com/browse/OAMG-4668
=> [RHELC-297] Clean up kmods functionality

convert2rhel/systeminfo.py, convert2rhel/unit_tests/conftest.py, convert2rhel/unit_tests/systeminfo_test.py, plans/tier0.fmf, tests/integration/tier0/check-internet-connection/main.fmf, tests/integration/tier0/check-internet-connection/test_internet_connection.py, tests/integration/tier1/convert-offline-systems/prepare_system.py
This check was introduced in PR #458 as a quick way to validate if the internet
connectionw as up or not. The way that it was introduced was not very robust,
as it was checking for a public Google DNS that may be blocked on some
machines/servers as not essential.
This commit tries to improve it by, instead of checking Google Public DNS, we
check a static file hosted by Red Hat. That should be a little more robust
since `*.redhat.com` is supposed to be reachable from the customer servers when
running convert2rhel.
=> [RHELC-637, RHELC-742] Improve internet connection check

convert2rhel/checks.py
In #469, one of the cleanups ended up calling `"\n".join()` on a list of kernel modules twice.  The first time changes the list into a string with each entry separated by a newline but the second time changes the string into another string with each chatacter separated by a newline. Fixed that by removing the second `str.join()`.
This also refactors away a call to `map()` and use of `lambda`.  In modern python, any uses of `map()` or `filter()` can be replaced with either a generator expression or list comprehension.
Related to #469
Jira Issue: [RHELC-784](RHELC-784)
Checklist
=> [RHELC-784] Fix the format of message about unavailable kernel modules.

convert2rhel/checks.py, convert2rhel/unit_tests/checks_test.py
We've renamed CONVERT2RHEL_UNSUPPORTED_VERSION to CONVERT2RHEL_ALLOW_OLDER_VERSION.  Allow the old env var name to be used but emit a deprecation warning in the log.
Add unittests to show the deprecation message is emitted when we use the old env var rather than the new one to allow the conversion to continue.
Followup to changes introduced for: #566
Jira Issue: [RHELC-784](https://issues.redhat.com/browse/RHELC-784)
Checklist
=> [RHELC-784] Allow but warn about deprecated env var

plans/tier0.fmf, tests/integration/tier0/verify-latest-kernel-check-with-failed-repoquery/files/broken_repo.repo, tests/integration/tier0/verify-latest-kernel-check-with-failed-repoquery/main.fmf, tests/integration/tier0/verify-latest-kernel-check-with-failed-repoquery/test_verify_kernel_check_passes.py
Add a verification test with intentionally tainted repository to verify handling unsuccessful repoquery.
* add verification test for #557
* tested with old build and build for PR#557
Jira Issue: [RHELC-689](https://issues.redhat.com/browse/RHELC-689)
Checklist
=> [RHELC-689] Verification test - Latest kernel check: Handle unsuccessful repoquery call

convert2rhel/systeminfo.py, convert2rhel/unit_tests/systeminfo_test.py, tests/ansible_collections/roles/add-custom-repos/main.yml, tests/integration/tier0/backup-release/test_backup_release.py, tests/integration/tier0/check-custom-repo/test_custom_repos.py, tests/integration/tier1/checks-after-conversion/test_enabled_repositories.py, tests/integration/tier1/method/custom_repos.py, tests/integration/tier1/satellite_non_eus_repos/satellite_non_eus_repos.py
When RHEL 8.7 is released, RHEL 8.6 will transition into the Extended Update Support. Our next release will happen post RHEL 8.7 GA so this is to make sure we then correctly detect 8.6 as EUS.
Some integration may be failing now as:
- they don't expect 8.6 to be EUS
- different RHEL repos are being enabled
- some checks during the conversion are being skipped if converting to EUS, namely loaded kernel currency check and system up-to-date check on Oracle Linux (because Oracle does not make repos of older minor versions available)
- the convert2rhel will start locking to the minor version through RHSM
Jira Issue: [RHELC-738](https://issues.redhat.com/browse/RHELC-738)
Checklist
=> [RHELC-738] Add RHEL 8.6 among the supported EUS minor versions

convert2rhel/systeminfo.py, convert2rhel/unit_tests/systeminfo_test.py, tests/ansible_collections/roles/oracle-linux-specific/tasks/boot_standard_kernel_84.yml, tests/ansible_collections/roles/oracle-linux-specific/tasks/main.yml
Skip the check on OL 8.4 because there are no available repositories.
https://issues.redhat.com/browse/RHELC-645
=> [RHELC-645] Skip check of latest kernel on OL8.4

convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py
Gpg writes a temporary socket file for a gpg-agent into --homedir.  Sometimes gpg removes that socket file after rmtree has determined it should delete that file but before the deletion occurs. This will cause a FileNotFoundError (OSError on Python 2).  If we encounter that, try to run shutil.rmtree again since we should now be able to remove all the files that were left.
Jira Issue: [RHELC-787](https://issues.redhat.com/browse/RHELC-787)
Checklist
=> [RHELC-787] Fix for temporary gpg home dir race.

.packit.yaml, convert2rhel/subscription.py, convert2rhel/unit_tests/subscription_test.py, plans/tier0.fmf, plans/tier1.fmf, tests/integration/tier0/check-cve-2022-1662/test_cve_fixes.py, tests/integration/tier0/inhibit-if-kmods-is-not-supported/test_kmods_not_supported.py, tests/integration/tier0/sub-man-rollback/main.fmf, tests/integration/tier0/sub-man-rollback/test_sub_man_rollback.py, tests/integration/tier0/test-check-rollback-handling/test_check_rollback_handling.py, tests/integration/tier1/remove-all-submgr-pkgs/test_no_submgr_pkg_installed.py, tests/integration/tier1/single-yum-transaction/test_single_yum_transaction.py
Not removing and backing up the python3-syspurpose and python3-cloud-what packages, which are also built out of the subscription-manager SRPM, was causing a rollback failure on CentOS Linux 8.5 when an older version of these two packages was installed.
The rollback failure caused the following issues during the subsequent second run of convert2rhel:
1. when the rollback happened before removing the centos-linux-release package, the removed subscription-manager-rhsm-certificates was not re-installed back during the rollback leading to a missing /etc/rhsm/ca/redhat-uep.pem file which is necessary for accessing the official convert2rhel repo on CDN
2. when the rollback happened before removing the centos-linux-release package, this package was not re-installed back during the rollback and …
=> [RHELC-744, RHELC-762] Backup all CentOS subscription-manager packages

.packit.yaml, plans/tier0.fmf, plans/tier1.fmf, tests/integration/tier0/verify-latest-kernel-check-with-failed-repoquery/main.fmf, tests/integration/tier1/removed-pkgs-centos-85/main.fmf
* disable for Oracle Linux 8.6 as it is now listed as EUS
=> Disable up to date test

convert2rhel/main.py, convert2rhel/systeminfo.py, convert2rhel/unit_tests/systeminfo_test.py
After we introduced the collection of breadcrumbs (#612) as a RHSM facts, we started to use some internal (now public) functions from the systeminfo.py module, which at first, those functions were responsible for logging out some system information, such as: Name, Version, Config file used, and so on... That change caused some duplicated lines in the Convert2RHEL log output.
This commit fixes this by moving the logs to the `resolve_system_info` function instead of placing the logs in each of the facts collection.
Checklist
=> Move system info logs to happen after the data collection

tests/ansible_collections/roles/hardcode-minor-version-repos/tasks/main.yml, tests/ansible_collections/roles/oracle-linux-specific/tasks/main.yml, tests/ansible_collections/roles/packaging/tasks/main.yml, tests/ansible_collections/roles/update-system/tasks/main.yml
* using `include` in ansible to import tasks shows the following: `[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks instead.`
* change to suggested
=> Remove deprecated `include`

.packit.yaml
* split tests dispatched through packit based on tiers
Jira Issue: [RHELC-807](https://issues.redhat.com/browse/RHELC-807)
Checklist
=> [RHELC-807] Split packit jobs for tests

convert2rhel/checks.py, convert2rhel/subscription.py, convert2rhel/unit_tests/subscription_test.py, plans/tier0.fmf
We need this certificate for the convert2rhel repo if the user installed using the convert2rhel.repo file:
https://ftp.redhat.com/redhat/convert2rhel/8/convert2rhel.repo
This is a workaround for https://issues.redhat.com/browse/RHELC-744 When we make uninstalling and reinstalling the RHEL subscription-manager packages a single step process, we will no longer need this as there will always be a redhat-uep.pem available from an rpm package.
Jira Issue: [RHELC-744](https://issues.redhat.com/browse/RHELC-744)
TODO:
Checklist
=> [RHELC-744] Install the redhat-uep.pem certificate if it is needed.

.packit.yaml, plans/main.fmf, plans/tier0.fmf, plans/tier1.fmf, tests/integration/tier0/custom-kernel/test_custom_kernel.py
* OL8.7 is officially out, re-enable 8.6 as a target to run tests on
* the target will get updated using ansible to 8.7 latest
* when 8.7 image is available on testing farm, switch target to 8.7
=> Re-enable testing on Oracle Linux 8.6

Dockerfiles/centos6.Dockerfile
The old URL we were using seems to be returning 404 when we try to access it. Since we can't retrieve the package from that URL, it was causing the image to not be built.
Checklist
=> Update URL_GET_PIP in CentOS6 dockerfile

convert2rhel/pkgmanager/handlers/yum.py, convert2rhel/unit_tests/pkgmanager/handlers/yum_test.py
We discovered that we were missing a few exception classes to catch during the package download. We went ahead and added a couple of exceptions to catch gpg checks and mirror exceptions too.
Checklist
=> Add a few exceptions class for yum transaction handler

convert2rhel/backup.py, convert2rhel/main.py, convert2rhel/subscription.py, convert2rhel/systeminfo.py, convert2rhel/unit_tests/backup_test.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/subscription_test.py, convert2rhel/unit_tests/systeminfo_test.py, plans/tier1.fmf, tests/integration/conftest.py, tests/integration/tier0/backup-release/main.fmf, tests/integration/tier0/backup-release/test_backup_release.py, tests/integration/tier1/convert-offline-systems/main.fmf, tests/integration/tier1/convert-offline-systems/prepare_system.py, tests/integration/tier1/convert-offline-systems/run_conversion.py, tests/integration/tier1/os-release-removal/remove_os_release.py
There is a problem with backing up the packages on systems which use satellite server. During the conversion is system unregistered from previous subscription - in that step we lose access to the CentOS repositories. And then we need to backup packages, which could come from CentOS. 
So the step with backup and remove the package is moved before the unregistration. With that show up another problem - the backed up and then removed package remove `os-release` file too. The file is needed for subscribing the system, so it is restored from backup and then removed (if it won't be removed, the file would stay there after conversion as  `os-release.rpmorig`)
Jira Issue: [RHELC-16](https://issues.redhat.com/browse/RHELC-16)
Checklist
=> [RHELC-16] Do not disable RHSM repos before pkg backup

convert2rhel/pkgmanager/handlers/yum.py
The yum transaction handler was not closing the rpmdb properly after the validation phase, thus, leaving the rpmdb opened and causing an traceback in the next step before replacing the packages on the system.
Checklist
=> Fix yum transaction for RHEL6 targets

.pre-commit-config.yaml, convert2rhel/systeminfo.py
This will let us pin the version of black without getting PRs from pre-commit that there is an updated version of black.
Checklist
- [N/A] PR meets acceptance criteria specified in the Jira issue
- [N/A] Jira issue has been made public if possible
- [N/A] `[RHELC-]` is part of the PR title 
- [N/A] When merged: Jira issue has been updated to `Release Pending`
=> Use a local repo for black.

.devcontainer/.bashrc, .devcontainer/centos8-development.Dockerfile, .devcontainer/centos8.requirements.txt, .devcontainer/devcontainer.json, .gitignore, .pre-commit-config.yaml, .vscode/settings.json, CONTRIBUTING.md
Since convert2rhel is a volatile tool to run on our own machines without
prior understanding that the tests we are running are mocked out
correctly. We may break our machine. It is better to run within a
container but we then get into issues where debugging, testing, and so
on isn't as integrated with existing tools as we'd like.
This is the first step to adding devcontainer using VSCode Remote
Development which will show VSCode as normal but within a container,
making it much easier to run tests and debug
---
I believe most things work at the moment but there are some tasks that need to be done. This also assumes a Podman environment, I do not think it will work with Docker
Jira Issue: [RHELC-823](https://issues.redhat.com/browse/RHELC-823) 
Checklist
=> [RHELC-823] chore: add devcontainer

tests/integration/tier0/check-user-response/test_user_response.py
Signed-off-by: Preston Watson <prwatson@redhat.com>
Adds a try/expect block to retry an assertion that usually takes 3 tries to pass. The integration test was not built to handle the three retries and fails on the first try. 
[RHELC-598] https://issues.redhat.com/browse/RHELC-598
Checklist
- [] PR has been tested manually in a VM (either author or reviewer)
- [ x] The commits are squashed to as few commits as possible (without losing data)
=> [RHELC-598] Fix for check-user-response test

convert2rhel/unit_tests/cert_test.py
Jira Issue: [RHELC-839](https://issues.redhat.com/browse/RHELC-839)
Checklist
=> [RHELC-839] Port the cert unittests to use pytest instead of unittest.

.packit.yaml
Removed the epel-6 target from the RPM builds in our packit configuration.
Jira Issue: [RHELC-861](https://issues.redhat.com/browse/RHELC-861)
Checklist
=> [RHELC-861] Remove epel-6 from .packit.yaml config

.pre-commit-config.yaml, convert2rhel/main.py, pyproject.toml
We had pre-commit-config settings the args for black and the
pyproject.toml file as also setting some properties for the tool.
It seems that black override those properties from pyproject.toml since
we used the CLI args for it, but in any case, we should rely only on one
configuration file to tell the tool what property it should override.
Also removed the unnecessary property in pre-commit-config for `isort`.
Checklist
=> Remove black args from pre-commit-config file

.gitignore, Makefile
This makes it so that if you want to run just tests for centos7 using
make tests7 it will now only build an image for centos7 instead of all
images at once.
Jira Issue: [RHELC-862](https://issues.redhat.com/browse/RHELC-862)
Checklist
=> [RHELC-862] chore: Separate make fetch-images 

.github/renovate.json
There was a trailing comma that created a JSON error for Renovate
Fixes: #544
Checklist
=> chore: fix Renovate config parse error

.github/workflows/build_images.yml
We forgot to rename the build_images workflow to use Containerfile
Jira Issue: [RHELC-864](https://issues.redhat.com/browse/RHELC-864)
Checklist
=> [RHELC-864] chore: fix GitHub workflow with container

.pre-commit-config.yaml, .pylintrc, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py, tests/integration/tier1/set-locale/use_non_english_language.py
This PR fixes the conversion when you set the "LANGUAGE" envar, because currently you would run into an traceback.
in this PR:
- utf-8 will beset as the default codec to fix the traceback
- "LANGUAGE" will be added to the set of envar alonge with "LC_ALL" and "LANG" 
Jira Issue: [RHELC-745](https://issues.redhat.com/browse/RHELC-745)
Checklist
=> [RHELC-745] Fix conversion with "LANGUAGE" envar 

convert2rhel/checks.py, convert2rhel/unit_tests/checks_test.py
This PR allows the user to convert using kmods that are not signed by Red Hat, though this conversion would not be supported. 
In this PR the code has been changed to add an environment variable, as well as a case for when the user has activated the envar. The original log message has been changed as well to reflect this. The unit test has been added for this as well.
Jira Issue: [RHELC-244](https://issues.redhat.com/browse/RHELC-244)
Checklist
=> [RHELC-244] allowing the overriding of kmod inhibitors

.github/release.yml
When generating release docs we want to split the PRs into different
categories more easily. This will spllit it into several categories and
ignore some labels and bots
Jira Issue: [RHELC-836](https://issues.redhat.com/browse/RHELC-836)
Checklist
=> [RHELC-836] Improve release notes

convert2rhel/subscription.py
The terminal output was confusing when the --keep-rhsm option was used because the only thing that the user was seeing was the message "Skipping due to the use of --keep-rhsm." They had no clue what activity this message relates to, i.e. what is being skipped.
Example of the old output:
```
WARNING - Abnormal exit! Performing rollback ...
Skipping due to the use of --keep-rhsm.
[01/05/2023 12:56:47] TASK - [Rollback: Removing installed packages] ****************************
```
Jira Issue: [RHELC-886](https://issues.redhat.com/browse/RHELC-886)
Checklist
=> [RHELC-886] Always print the RHSM rollback task "title"

convert2rhel/backup.py, convert2rhel/checks.py, convert2rhel/unit_tests/checks_test.py, tests/integration/tier0/basic-sanity-checks/test_basic_sanity_checks.py
There were two info-level log message printed with basically the same information:
```
[02/03/2023 19:08:44] TASK - [Convert: Import Red Hat GPG keys] *********************************
GPG key 37017186 imported
GPG key /usr/share/convert2rhel/gpg-keys/RPM-GPG-KEY-redhat-legacy-release imported successfuly.
GPG key fd431d51 imported
GPG key /usr/share/convert2rhel/gpg-keys/RPM-GPG-KEY-redhat-release imported successfuly.
```
Also, the message `Continuing conversion.` was giving users no real value. To be consistent, we'd need to have it at the end of each passed check.
```
[02/03/2023 19:41:01] TASK - [Prepare: Check if this is the latest version of Convert2RHEL] *****
Latest available Convert2RHEL version is installed.
Continuing conversion.
```
--------------------
How it's going to look …
=> [RHELC-890] Deduplicate log messages about imported keys

plans/tier1.fmf
* Previously the Satellite repository was out of sync, therefore we needed to install older kernel to match the latest available in the repository
* the satellite repository is now synced weekly, the workaround is not needed anymore
=> [hotfix] Remove workaround from convert_offline_systems test

convert2rhel/toolopts.py, convert2rhel/unit_tests/toolopts_test.py
The check making sure the organization is specified by the user is currently skipped when you don't specify the organization on the command line AND you pass the activation key through either the CLI OR the config file.
[RHELC-693](https://issues.redhat.com/browse/RHELC-693)
=> [RHELC-693] Check if org and key passed

convert2rhel/initialize.py, convert2rhel/utils.py
When we created `initialize.set_locale()`, removing the function from its former location in `utils.py` was missed.  Subsequently, some new code was added to `utils.set_locale()` when it should have been added to `initialize` instead.  This commit merges the new changes into `initialize.set_locale()` and finishes the move by removing the duplicate from `utils.py`.
Fixes RHELC-892
Jira Issue: [RHELC-892](https://issues.redhat.com/browse/RHELC-892)
Checklist
=> [RHELC-892] Finish the move of set_locale() to initialize.

convert2rhel/subscription.py, convert2rhel/unit_tests/subscription_test.py, tests/integration/tier0/check-user-response/test_user_response.py, tests/integration/tier0/test-check-rollback-handling/test_check_rollback_handling.py
When #563 was merged we got a few methods that were no longer needed.
Due to forcing the user to provide key and org always now we no longer
need two integration tests either that was failing due to this change.
Jira Issue: [RHELC-693](https://issues.redhat.com/browse/RHELC-693)
Checklist
=> [RHELC-693] test: remove unnecessary code for org and key

convert2rhel/logger.py, convert2rhel/unit_tests/utils_test.py
The contents of FILE are the same as DEBUG.  The only difference is that FILE outputs to the log file whereas DEBUG goes to the terminal and the log file.  This means, in the log file, when we run convert2rhel with the --debug flag, the log messages are labelled with DEBUG.  When we run without --debug, the same messages end up in the log file but they have the label FILE.  Changing the label of LogLevelFile to DEBUG will keep the label the same for both of these cases.
Jira Issue: [RHELC-882](https://issues.redhat.com/browse/RHELC-882)
Checklist
=> [RHELC-882] Change the label for FILE output to DEBUG.

convert2rhel/pkghandler.py, convert2rhel/pkgmanager/handlers/dnf.py, convert2rhel/pkgmanager/handlers/yum.py, convert2rhel/unit_tests/pkghandler_test.py
After merging the #528, we left behind a few comments to be addressed in a future PR as they were mostly about comments/logs that could be improved.
In this PR, there is also a removal of one unused function that was marked as a TODO in #528.
Jira Issue: [RHELC-779](https://issues.redhat.com/browse/RHELC-779)
Checklist
---
=> [RHELC-779] Remove unused function call_yum_cmd_w_downgrades

convert2rhel/systeminfo.py
Changed the internet connection address to use https instead of http, as it could cause problems under firewalls that blocks http requests.
Jira Issue: [RHELC-891](https://issues.redhat.com/browse/RHELC-891)
Checklist
=> [RHELC-891] Update internet connection check address

convert2rhel/backup.py, convert2rhel/cert.py, convert2rhel/checks.py, convert2rhel/main.py, tests/integration/tier0/backup-release/test_backup_release.py, tests/integration/tier0/latest-kernel-check/test_latest_kernel_check.py
Some of the log messages were using continous tense, some present tense. There was more of the messages with the present tense so this commit transforms all the messages to the present tense.
Jira Issue: [RHELC-889](https://issues.redhat.com/browse/RHELC-889)
Checklist
=> [RHELC-889] Make TASK log messages consistent

convert2rhel/toolopts.py
Small improvement of docustring of `--config-file` option.
Jira Issue: [[RHELC-854](https://issues.redhat.com/browse/RHELC-854)]
Checklist
=> [RHELC-854] Man/help page to mention config file location

convert2rhel/grub.py, convert2rhel/unit_tests/grub_test.py, plans/tier1.fmf, tests/integration/tier1/detect-bootloader-partition/main.fmf, tests/integration/tier1/detect-bootloader-partition/test_detect_correct_boot_partition.py
This PR fixes a bug in convert2rhel. The conversion would fail when getting to the "Configure the Bootloader" step because it wasn't getting the correct partition number if the user had more than one partition on a UEFI system.
Jira Issue: [RHELC-733](https://issues.redhat.com/browse/RHELC-733)
Checklist
=> [RHELC-733] Fixes the bug for converting when trying to add in an new UEFI bootloader entry for RHEL

convert2rhel/checks.py, convert2rhel/unit_tests/checks_test.py
Before we do an upstream release we can still change the CONVERT2RHEL_ALLOW_UNCHECKED_KMODS environment variable used for overriding the check that inhibits the conversion when kernel modules not available in RHEL are loaded. This variable was introduced recently under https://github.com/oamg/convert2rhel/pull/613.
It is not clear what we mean by UNCHECKED in the envar. CONVERT2RHEL_ALLOW_UNAVAILABLE_KMODS is more self-explanatory.
Also, this PR rewords the use of _"first-party kernel modules"_ as it's also quite unclear what we mean by that.
The https://github.com/oamg/convert2rhel/pull/735 that introduces an integration check for the new environment variable needs to be updated accordingly.
Jira Issue: [RHELC-244](https://issues.redhat.com/browse/RHELC-244)
Checklist
=> [RHELC-244] Rename unavailable kmod inhibitor envar

convert2rhel/breadcrumbs.py, convert2rhel/subscription.py, convert2rhel/unit_tests/breadcrumbs_test.py, convert2rhel/unit_tests/subscription_test.py, convert2rhel/unit_tests/toolopts_test.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py, tests/integration/tier0/log-command/test_log_command.py, tests/integration/tier0/test-check-rollback-handling/test_check_rollback_handling.py
Until now we've been recording and collecting the RHSM username and organization in their plain text form in the convert2rhel log files and the breadcrumbs files:
- /var/log/convert2rhel/convert2rhel.log
- /var/log/convert2rhel/archive/convert2rhel-*.log
- /etc/migration-results
- /etc/rhsm/facts/convert2rhel.facts
Users might perceive those values as sensitive or private information. Red Hat doesn't need this information for anything so it's better to not collect it at all.
Jira Issue: [RHELC-888](https://issues.redhat.com/browse/RHELC-888)
Checklist
=> [RHELC-888] Make RHSM organization and username a secret

plans/tier1.fmf, tests/integration/tier0/inhibit-if-kmods-is-not-supported/test_kmods_not_supported.py
* add integration test to verify the environment variable introduced overrides the inhibition
* Introduced in [PR#613](https://github.com/oamg/convert2rhel/pull/613/)
Jira Issue: [RHELC-244](https://issues.redhat.com/browse/RHELC-244)
Checklist
=> [RHELC-244] Verify overriding usupported kernel module inhibition

convert2rhel/breadcrumbs.py, convert2rhel/main.py, convert2rhel/subscription.py, convert2rhel/unit_tests/breadcrumbs_test.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/subscription_test.py, plans/tier1.fmf, tests/integration/tier0/basic-sanity-checks/test_basic_sanity_checks.py, tests/integration/tier0/check-internet-connection/test_internet_connection.py, tests/integration/tier0/custom-kernel/test_custom_kernel.py, tests/integration/tier0/inhibit-if-kmods-is-not-supported/main.fmf, tests/integration/tier0/inhibit-if-kmods-is-not-supported/test_kmods_not_supported.py, tests/integration/tier0/latest-kernel-check/test_latest_kernel_check.py, tests/integration/tier0/test-check-rollback-handling/main.fmf, tests/integration/tier1/checks-after-conversion/main.fmf, tests/integration/tier1/checks-after-conversion/test_disable_data_collection.py, tests/integration/tier1/method/activation_key.py, tests/integration/tier1/method/custom_repos.py, tests/integration/tier1/method/main.fmf, tests/integration/tier1/method/rhsm.py, tests/integration/tier1/method/rhsm_non_eus.py, tests/integration/tier1/method/satellite.py, tests/integration/tier1/remove-all-submgr-pkgs/main.fmf, tests/integration/tier1/system-up-to-date/test_system_up_to_date.py
The user is informed about the data we upload to Red Hat servers. They are asked to acknowledge the data collection and in case they do not like it we've added the ability to disable it.
Jira Issue: [RHELC-849](https://issues.redhat.com/browse/RHELC-849)
Jira Issue: [RHELC-850](https://issues.redhat.com/browse/RHELC-850)
Checklist
=> [RHELC-849, RHELC-850] Inform+disable telemetry

tests/integration/tier1/kernel-boot-files/test_handle_missing_boot_files.py
On CentOS and Oracle Linux 7 the test was failing because we were renaming the vmlinuz, thinking that it's enough to simulate that they are not present. But leaving them renamed in the /boot/ folder caused that the grub2-mkconfig picked them up and generated a new grub configuration using these renamed boot files:
```
09:39:43             out: [02/22/2023 09:39:43] TASK - [Final: Update GRUB2 configuration] ********************************
...
09:39:44             out: [02/22/2023 09:39:44] DEBUG - Output of the grub2-mkconfig call:
09:39:44             out: Found linux image: /boot/vmlinuz-3.10.0-1160.83.1.el7.x86_64.backup
09:39:44             out: Found initrd image: /boot/initramfs-3.10.0-1160.83.1.el7.x86_64.backup.img
```
Full test failure log: …
=> [RHELC-752] Fix "missing boot files" test

tests/integration/tier0/log-command/test_log_command.py, tests/integration/tier1/kernel-boot-files/test_handle_missing_boot_files.py
* the test failed to reboot on epel8 due to bad reinstall
* the kernel-core package should be reinstalled, not kernel
=> Test fix: reinstall kernel package for epel8

.pre-commit-config.yaml
This will check for git secrets when pushing to the remote. It should
hopefully catch any mistakes when accidentally pushing secrets.
Checklist
=> chore: add gitleaks to pre-commit hook

convert2rhel/pkghandler.py, convert2rhel/pkgmanager/__init__.py, convert2rhel/pkgmanager/handlers/base.py, convert2rhel/redhatrelease.py, convert2rhel/unit_tests/backup_test.py, convert2rhel/unit_tests/checks_test.py, convert2rhel/unit_tests/conftest.py, convert2rhel/unit_tests/logger_test.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/pkgmanager/pkgmanager_test.py, convert2rhel/unit_tests/subscription_test.py, convert2rhel/unit_tests/systeminfo_test.py, convert2rhel/unit_tests/toolopts_test.py, convert2rhel/unit_tests/utils_test.py, man/build_manpage.py, setup.py, tests/integration/tier0/basic-sanity-checks/test_basic_sanity_checks.py, tests/integration/tier0/single-yum-transaction-validation/test_single_yum_transaction_validation.py, tests/integration/tier1/checks-after-conversion/test_flag_system_as_converted.py, tests/integration/tier1/config-file/test_config_file.py, tests/integration/tier1/convert-offline-systems/run_conversion.py
This commit introduces a bunch of fixes for the warnings/notices that CodeQL was showing for Convert2RHEL under the the `Security` tab.
Checklist
=> Fix CodeQL warnings

convert2rhel/initialize.py, convert2rhel/logger.py
@r0x0d added initialize.py for steps that need to be taken early to initialize various subsystems.  Adding of the NullHandler to the root logger (to avoid some libraries initializing themselves in a way that ends up outputting messages multiple times) needs to be done very early. So moving it to initialize.py is the logical choice.
Jira Issue: [RHELC-724](https://issues.redhat.com/browse/RHELC-724)
Checklist
=> [RHELC-724] Move adding of NullHandler to the root logger.

CONTRIBUTING.md, ansible/setup-convert2rhel.yml, convert2rhel/checks.py, convert2rhel/grub.py, convert2rhel/pkghandler.py, convert2rhel/redhatrelease.py, convert2rhel/special_cases.py, convert2rhel/subscription.py, convert2rhel/systeminfo.py, convert2rhel/toolopts.py, convert2rhel/unit_tests/__init__.py, convert2rhel/unit_tests/checks_test.py, convert2rhel/unit_tests/conftest.py, convert2rhel/unit_tests/grub_test.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/redhatrelease_test.py, convert2rhel/unit_tests/special_cases_test.py, convert2rhel/unit_tests/subscription_test.py, convert2rhel/unit_tests/systeminfo_test.py, convert2rhel/utils.py, packaging/convert2rhel.spec, scripts/build_locally.sh, tests/integration/tier0/basic-sanity-checks/test_basic_sanity_checks.py, tests/integration/tier0/check-custom-repo/test_custom_repos.py, tests/integration/tier1/method/custom_repos.py, tests/integration/tier1/resolve-dependency/install_dependency_packages.py
All current code regarding conversion to RHEL 6 are to be removed in
this commit. Tests have verified to be working, might have missed
something still but at least 90% of everything regarding el6 is gone
Jira Issue: [RHELC-869](https://issues.redhat.com/browse/RHELC-869)
Checklist
=> [RHELC-869] chore: remove el6 related code

convert2rhel/checks.py, convert2rhel/pkghandler.py, convert2rhel/pkgmanager/__init__.py, convert2rhel/unit_tests/checks_test.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py
This is a WIP PR for RHELC-667. It aims to improve the current package version comparison with the addition of being able to parse NEVRA, NEVR, NVRA, NVR, ENVRA and ENVR formats. The PR will also separate the current package version comparison and parsing function into two separate functions. 
Jira Issue: [RHELC-667](https://issues.redhat.com/browse/RHELC-667)
Signed-off-by: Preston Watson <prwatson@redhat.com>
Checklist
=> [RHELC-667] Improve package version comparison

Containerfiles/centos8.Containerfile, requirements/centos8.requirements.txt
Running `make lint` was failing due to not having pylint available in the CentOS Linux 8 container (we run the linting in just this one container). The original error:
```
$ make lint
Building images
bash: pylint: command not found
```
After adding the dependency, pylint started to complain about not being able to create a certain directory to the home folder of the user running the pylint. So this change also allows creating the user home folder by removing `-r` from the useradd command. The original error:
```
$ make lint
Building images
------------------------------------
Your code has been rated at 10.00/10
Unable to create directory /home/app/.cache/pylint
Unable to create file /home/app/.cache/pylint/convert2rhel1.stats: [Errno 2] No such file or directory: …
```
=> Fix running pylint in a container

convert2rhel/actions/rhel_compatible_kernel.py, convert2rhel/unit_tests/actions/rhel_compatible_kernel_test.py
This PR ports the check_rhel_compatible_kernel_is_used and other associated functions to an action framework.
Jira Issues: [RHELC-934](https://issues.redhat.com/browse/RHELC-934)
Checklist
=> [RHELC-934] Port check_rhel_compatible_kernel_is_used to Action framework

convert2rhel/actions/__init__.py, convert2rhel/actions/package_updates.py, convert2rhel/unit_tests/actions/actions_test.py, convert2rhel/unit_tests/actions/package_updates_test.py
This PR ports the check_package_updates function from checks.py to an Action framework.
Jira Issues: [RHELC-935](https://issues.redhat.com/browse/RHELC-935)
Checklist
=> [RHELC-935] Port check_package_updates to Action framework

convert2rhel/actions/__init__.py, convert2rhel/actions/custom_repos_are_valid.py, convert2rhel/unit_tests/actions/actions_test.py, convert2rhel/unit_tests/actions/custom_repos_are_valid_test.py
This PR ports the check_custom_repos_are_valid function from checks.py to an Action framework.
Jira Issues: [RHELC-929](https://issues.redhat.com/browse/RHELC-929)
Checklist
=> [RHELC-929] Port check_custom_repos_are_valid to Action framework

convert2rhel/actions/__init__.py, convert2rhel/actions/dbus.py, convert2rhel/unit_tests/actions/actions_test.py, convert2rhel/unit_tests/actions/dbus_test.py
This PR ports the check_dbus_is_running function from checks.py to an Action framework
Jira Issues: [RHELC-937](https://issues.redhat.com/browse/RHELC-937)
Checklist
=> [RHELC-937] Port check_dbus_is_running to Action framework

convert2rhel/unit_tests/actions/is_loaded_kernel_latest_test.py
The test separation between yum and dnf had a problem where for the yum part, it was not mocking correctly the run_subprocess command, as it was using `kernel-core` in it's parameter.
Also, the test doesn't need to be in EUS to be performed.
Checklist
=> Fix is_loaded_kernel_latest tests

plans/tier1.fmf, tests/integration/tier1/kernel-core-only/main.fmf, tests/integration/tier1/kernel-core-only/remove_kernel_pkg.py
Test that remove kernel package from the system and leaves only kernel-core package. This is possible only on RHEL-8 systems.
Related ticket: https://issues.redhat.com/browse/RHELC-280
=> [RHELC-280] Add integration test for only installed kernel-core package

convert2rhel/actions/__init__.py, convert2rhel/actions/report.py, convert2rhel/main.py, convert2rhel/unit_tests/actions/report_test.py, convert2rhel/unit_tests/main_test.py, convert2rhel/utils.py
This commit introduces the report summary that will be displayed to the user by end of the analysis, regardless if they are using doing a normal conversion, or a pre conversion check.
The report is pretty simple as it consist mainly of logging the message to the user in a nice format, ordered by most important first.
The catch here is that if the user is doing a pre conversion analysis, they will get all messages generated by the action classes displayed for them, while, if they are doing a normal conversion, only `WARNINGS` and above will be displayed.
Jira Issues: [RHELC-927](https://issues.redhat.com/browse/RHELC-927)
Checklist
=> [RHELC-927] Add actions report to be displayed by the end of the analysis

convert2rhel/actions/pre_ponr_changes/backup_system.py, convert2rhel/unit_tests/actions/backup_system_test.py
This PR ports the backup_system calls in main to an Action framework
Jira Issues: [RHELC-971](https://issues.redhat.com/browse/RHELC-971)
Checklist
=> [RHELC-971] Port main::backup_system to Actions framework

convert2rhel/actions/pre_ponr_changes/handle_packages.py, convert2rhel/actions/system_checks/package_updates.py, convert2rhel/pkghandler.py, convert2rhel/subscription.py, convert2rhel/unit_tests/actions/pre_ponr_changes/handle_packages_test.py, convert2rhel/unit_tests/actions/system_checks/package_updates_test.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/subscription_test.py
This PR removes instances of the ask_to_continue() function from utils.py being used in actions
Jira Issues: [RHELC-972](https://issues.redhat.com/browse/RHELC-972)
Checklist
=> [RHELC-972] Remove user confirmation from actions

convert2rhel/actions/__init__.py, convert2rhel/actions/report.py, convert2rhel/main.py, convert2rhel/unit_tests/actions/actions_test.py, convert2rhel/unit_tests/main_test.py
* Exit from Analyze by setting the ConversionPhase to a new code, ANALYZE_EXIT and then raising an Exception.  This triggers recording of the breadcrumbs and rollback.
* Also rework find_actions_of_severity() so the code can be used in both main.py::main() and actions/report.py::summary().
Jira Issues: [RHELC-974](https://issues.redhat.com/browse/RHELC-974)
Checklist
=> [RHELC-974] Adapt main.py for rollback.

convert2rhel/actions/pre_ponr_changes/backup_system.py, convert2rhel/actions/pre_ponr_changes/handle_packages.py, convert2rhel/actions/pre_ponr_changes/subscription.py, convert2rhel/main.py, convert2rhel/unit_tests/actions/pre_ponr_changes/backup_system_test.py, convert2rhel/unit_tests/actions/pre_ponr_changes/handle_packages_test.py, convert2rhel/unit_tests/main_test.py
This PR do a couple of different things rather than just adding a new dependency to the remove repo files action
- It adds the explicit dependency to the mentioned action
- Remove old code left from the backup system port
- Fixes the unit tests and the BackupRedhatRelease action to use old code fom redhatrelease.py
Jira Issues: [RHELC-982](https://issues.redhat.com/browse/RHELC-982)
Checklist
=> [RHELC-982] Improvements to the backup_system module

convert2rhel/actions/pre_ponr_changes/kernel_modules.py
The EnsureKernelModulesCompatibility was failing and reporting that various kernel modules were not available in RHEL repositories, as it was using an wrong kernel version to determinate that.
This commit fixes the code and allow it to execute correctly.
Checklist
=> Fix repoquery in kernel modules action output

convert2rhel/actions/report.py, convert2rhel/main.py, convert2rhel/unit_tests/actions/report_test.py
Move when we print the report.
There are three separate cases where we want to print the report:
1) For the user to review before confirming that they want to continue
past the PONR.  This is where in the code's workflow that the
happening.
2) For the user to fix things when a conversion failed prior to the PONR
3) For the user to see whether the machine is ready to convert (analyze
report).
Each of these three cases wants to print the report at a different point
in the process:
(1) Just before confirmation that the user should go past the PONR
(2) After rollback, just before failing with return code 1
(3) After rollback, just before returning with return code 0
Output for a conversion that fails before this change:
* https://toshio.fedorapeople.org/convert2rhel/pre-check-2023-04-04.log …
=> Move report to after rollback

convert2rhel/actions/__init__.py, convert2rhel/actions/report.py, convert2rhel/logger.py, convert2rhel/main.py, convert2rhel/unit_tests/actions/report_test.py, convert2rhel/unit_tests/main_test.py, convert2rhel/utils.py
* Print a section heading for each status level in the report.
* Add indentation if a message spans multiple lines.
New output should look like:
```
===== Error (Must fix before conversion) =====
(ERROR) KERNEL_TOO_OLD:OUTDATED: The problem was that there
was a kernel that was older than the RHEL one.  And how
to solve it.
(ERROR) THIRDPARTY_KMODS:NON_RHEL_KMODS: Another problem.
===== Success (No changes needed) =====
(SUCCESS) CONVERT2RHEL_LATEST
(SUCCESS) RHEL_REPOS_AVAILABLE
```
* Colorize report output unless NO_COLOR environment variable is used.
Checklist
=> Format improvements to the report

convert2rhel/actions/report.py, convert2rhel/main.py, convert2rhel/utils.py
* If the user interrupts the conversion before the Actions finish running, then we don't have any results to display to the user.  This lead to a traceback when we attempted to print the report during rollback().  The code has ben modified to inform the user that no report can be printed in this circumstance.
* Fix compatibility code that detects the terminal size. The compat code was returning (height, width) while the pyhton-3.6+ code was returning (width, height).  Changed so both return width first.
* Preserve existing whitespace when printing messages in the report.  This leads to better formatting for tracebacks and longer messages which embed their own newlines.
Checklist
=> Fix for traceback in report when Ctrl-C is pressed.

.packit.yaml
We now have cloud costs reporting in Testing Farm.
This is required to tag the cloud resources to this project's sst team.
Will be soon documented here:
https://github.com/packit/packit.dev/pull/632
=> Tag cloud resources to sst_conversions

.pre-commit-config.yaml, plans/rerun.fmf, tests/integration/tier0/basic-sanity-checks/main.fmf, tests/integration/tier0/config-file/main.fmf, tests/integration/tier0/custom-kernel/main.fmf, tests/integration/tier0/custom-repository/main.fmf, tests/integration/tier0/cve-2022-1662/main.fmf, tests/integration/tier0/internet-connection-check/main.fmf, tests/integration/tier0/kernel-modules/main.fmf, tests/integration/tier0/latest-kernel-check/main.fmf, tests/integration/tier0/logged-command/main.fmf, tests/integration/tier0/modified-releasever/main.fmf, tests/integration/tier0/oracle-linux-unbreakable-enterprise-kernel/main.fmf, tests/integration/tier0/rollback-handling/main.fmf, tests/integration/tier0/single-yum-transaction-validation/main.fmf, tests/integration/tier0/sub-man-rollback/main.fmf, tests/integration/tier0/system-release-backup/main.fmf, tests/integration/tier0/user-prompt-response/main.fmf
* With recent changes to the nondestructive tests we have lost the possibility to run them individually
* Creating this plan should enable us to do so again
* The plan is created by concatenating all the .fmf files from the tier0 directory and performing neccessary modifications
* Add new pre-commit hook to regenerate the rerun.fmf file
* Simplify tags in the tier0 .fmf files
Jira Issues: [RHELC-997](https://issues.redhat.com/browse/RHELC-997)
Checklist
=> [RHELC-997] Add a new rerun plan

convert2rhel/pkghandler.py
The order of output of this action was a bit different from what we have in main right now, this commit changes it to a more sane order.
Jira Issues: [RHELC-993](https://issues.redhat.com/browse/RHELC-993)
Checklist
=> [RHELC-993] Fix the output order for RemoveRepositoryFiles action

.packit.yaml, .pre-commit-config.yaml
* do not merge PR in the CI
* currently we are facing issues with Packit/TF trying to merge the PR into the target branch, with the merge not being completed
* this results to checking out to the HEAD of target branch to read the test fmf metadata from, resulting to not having the metadata updated
* add `merge_pr_in_ci: false` to mitigate the issue
* set stage for regenerate-rerun-plan to manual
Jira Issues: [RHELC-1008](https://issues.redhat.com/browse/RHELC-1008)
Checklist
=> [RHELC-1008] Update packit.yaml and pre-commit-config.yaml

convert2rhel/subscription.py, convert2rhel/unit_tests/subscription_test.py
The 'force' D-Bus registration option used to simply be not implemented, effectively being a no-op; because of that, the system is manually unregistered before the actual registration.
Newer versions of subscription-manager (in 8.8 and 9.2) actually do implement the 'force' option; OTOH, since the system was unregistered before the registration attempt, having the option there does not make any difference. Hence, simply drop the 'force' option altogether.
Improve the comment regarding the unregistration to mention the status of the 'force' option, and the general reason for unconditionally unregistering at that point.
Checklist
=> RHSM: do not use the 'force' D-Bus registration option

convert2rhel/pkghandler.py, convert2rhel/unit_tests/pkghandler_test.py
This PR rewrites two log messages for when invalid packages are detected.
Jira Issues: [RHELC-1009](https://issues.redhat.com/browse/RHELC-1009)
Checklist
=> [RHELC-1009] Fix the log message for invalid package detection

convert2rhel/actions/system_checks/is_loaded_kernel_latest.py, convert2rhel/checks.py, convert2rhel/unit_tests/actions/system_checks/is_loaded_kernel_latest_test.py, plans/rerun.fmf, plans/tier1.fmf, pytest.ini, tests/integration/tier1/checks-after-conversion/test_rhel_kernel.py, tests/integration/tier1/kernel-check-skip/main.fmf, tests/integration/tier1/kernel-check-skip/test_latest_kernel_check_skip.py, tests/integration/tier1/one-kernel-scenario/run_conversion.py
The environment variable `CONVERT2RHEL_UNSUPPORTED_SKIP_KERNEL_CURRENCY_CHECK` doesn't work as expected in my opinion. The kernel package check will only be skipped if no kernel packages are found in the repo. If packages are available, the env var will be ignored and the conversion fails.
In a rare edge case, were a new minor kernel release in RHEL 7 is already available but not in CentOS 7, forcing the check to be skipped is the easiest way to move forward without jumping through further hoops. Observed with `kernel-3.10.0-1160.90.1.el7` as latest in RHEL 7 and `kernel-3.10.0-1160.88.1.el7` as latest in CentOS 7.
Even with set env var, the kernel check will not be skipped in `convert2rhel-1.2-2.el7.noarch`:
```
[05/02/2023 19:17:18] TASK - [Prepare: Check if the loaded kernel version is …
```
=> [RHELC-1003] Allow to skip kernel check even if packages are available

tests/integration/conftest.py
* we do not have any .env file in the repository, the line is redundant
Tested on CentOS-8.4 with tier0 set:
http://artifacts.osci.redhat.com/testing-farm/8a854bf5-2487-494b-9dfd-0cfe2c53a8a0/
=> tests/hotfix/Remove parsing .env in conftest

plans/main.fmf, tests/ansible_collections/roles/add-custom-repos/main.yml, tests/integration/tier0/custom-kernel/test_custom_kernel.py, tests/integration/tier1/checks-after-conversion/test_release_version.py, tests/integration/tier1/kernel-boot-files/test_handle_missing_boot_files.py
* change respective values to expect the new minor
* switch SYSTEM_RELEASE_ENV to oracle-8-latest to lower the overhead needed for changing test values
Jira Issues: [RHELC-1016](https://issues.redhat.com/browse/RHELC-1016)
Checklist
=> [RHELC-1016] Expect release of Oracle Linux 8.8

config/convert2rhel.ini, convert2rhel/toolopts.py, convert2rhel/unit_tests/toolopts_test.py, tests/integration/tier0/config-file/test_config_file.py, tests/integration/tier1/config-file/test_config_file.py
Allow the username and organization to be used in the config file as a secure way of using the RHSM credentials duirng the conversion.
Previously, only the password and activation key were used and parsed in the config file.
Jira Issues: [RHELC-901](https://issues.redhat.com/browse/RHELC-901)
Checklist
=> [RHELC-901] Allow username and organization in the config file

convert2rhel/subscription.py, convert2rhel/systeminfo.py, convert2rhel/toolopts.py, convert2rhel/unit_tests/subscription_test.py, convert2rhel/unit_tests/systeminfo_test.py, convert2rhel/utils.py, pytest.ini, tests/integration/tier0/rollback-handling/main.fmf, tests/integration/tier0/rollback-handling/test_rollback_handling.py, tests/integration/tier0/user-prompt-response/main.fmf, tests/integration/tier0/user-prompt-response/test_user_prompt_response.py
This PR removes the need for --pool or --auto-attach options to be required. The listing of available subscriptions to the user has been removed as well as the code hacks introduced to make it possible - these removals are apart of a separate task [RHELC-821]. If SCA is enabled we don't attach any subscription as SCA handles the attachment. A warning has been added if SCA is enabled and the --pool option is added as a CLI argument. If SCA is not enabled and neither the --pool or --auto_attach options are not specified, the code defaults to auto attaching subscriptions similar to how subscription-manager functions. In the event the subscription attachment fails, an error message is printed to the user pointing them to https://access.redhat.com/management/ and mentioning that there they can …
=> [RHELC-781, RHELC-821] Don't require --pool or --auto-attach 

convert2rhel/pkgmanager/__init__.py, convert2rhel/pkgmanager/handlers/dnf/__init__.py, convert2rhel/pkgmanager/handlers/yum/__init__.py, convert2rhel/unit_tests/pkgmanager/handlers/dnf/dnf_test.py, convert2rhel/unit_tests/pkgmanager/handlers/yum/yum_test.py, plans/tier1.fmf, pytest.ini, tests/integration/tier1/single-yum-transaction/main.fmf, tests/integration/tier1/single-yum-transaction/test_check_for_latest_packages.py, tests/integration/tier1/system-up-to-date/main.fmf
During our transaction handler, some packages were trying to be reinstalled/downgraded on the system without necessity, as they were already marked for update.
This patch prevents those packages marked for update to be reinstalled or downgraded in further cases.
Jira Issues: [RHELC-899](https://issues.redhat.com/browse/RHELC-899)
Checklist
=> [RHELC-899] Prevent packages marked for update to reinstall

convert2rhel/actions/report.py, convert2rhel/main.py, convert2rhel/unit_tests/actions/report_test.py, convert2rhel/unit_tests/main_test.py
For integration with insights and other tools, we need to output the assessment report as a json file.
Jira Issues: [RHELC-975](https://issues.redhat.com/browse/RHELC-975)
- Rodolfo thinks it makes more sense alongside the breadcrumbs output.  I've moved it to `/etc/convert2rhel-assessment.json` for now.
- Rodolfo agrees that this location makes sense. 
- Rodolfo thinks that `finally:` in main.py makes more sense so I will make this change. 
Checklist
=> [RHELC-975] Output the pre-assessment as a json file.

tests/integration/tier0/destructive/method/custom_repos.py, tests/integration/tier0/non-destructive/custom-repository/test_custom_repository.py, tests/integration/tier1/destructive/one-kernel-scenario/run_conversion.py
We decided that --no-rhsm was a better name for this option but kept --disable-submgr for backwards compatibility.  Test --no-rhsm in integration tests since it is the preferred name.
Checklist
=> Replaced --disable-submgr with --no-rhsm.

plans/tier0.fmf, plans/tier1.fmf, tests/integration/tier0/destructive/convert-offline-systems/prepare_system.py
Previously we added an offline conversion test. However, it was run only for the centos-7. 
The required repositories are present on the satellite instance also for the remaining distributions.
This PR enables running tests of other distros for the offline conversion test. 
Jira Issues: [RHELC-824](https://issues.redhat.com/browse/RHELC-824)
Checklist
=> [RHELC-824] Add remaining distros for the offline conversion test

convert2rhel/logger.py
The default for convert2rhel was using format that wasn't standardized.
This changes it from "mm/dd/yyyy HH:mm:ss" format to "yyyy-mm-ddTHH:mm:ssZ"
Jira Issues: [RHELC-1000](https://issues.redhat.com/browse/RHELC-1000)
Checklist
=> [RHELC-1000] Change datetime to ISO with timezone to be standardized

tests/integration/tier1/destructive/system-up-to-date/test_system_up_to_date.py
* the workaround removed the oldest kernel installed on the system to get around issues with yum/dnf transaction validation
* this issue was possibly fixed with the transaction validation tweaks in #833
* subsequently the removal allows verifying the issue 
Jira Issues: [RHELC-873](https://issues.redhat.com/browse/RHELC-873)
Checklist
=> [RHELC-873] tests/Remove workaround for three kernels installed

convert2rhel/actions/pre_ponr_changes/kernel_modules.py, convert2rhel/unit_tests/actions/pre_ponr_changes/kernel_modules_test.py, packaging/convert2rhel.spec
The lsmod binary may not always be available through PATH, better to call it using its full installation path.
Also the package that installs this binary was missing in the spec file as a dependency of convert2rhel.
Jira Issues: [RHELC-1056](https://issues.redhat.com/browse/RHELC-1056)
Checklist
=> [RHELC-1056] Fix lsmod not being found on OL7

convert2rhel/actions/__init__.py, convert2rhel/unit_tests/actions/report_test.py, tests/integration/tier0/non-destructive/assessment-report/test_assessment_report.py, tests/integration/tier0/non-destructive/basic-sanity-checks/main.fmf, tests/integration/tier0/non-destructive/basic-sanity-checks/test_basic_sanity_checks.py, tests/integration/tier0/non-destructive/custom-kernel/test_custom_kernel.py, tests/integration/tier0/non-destructive/custom-repository/test_custom_repository.py, tests/integration/tier0/non-destructive/kernel-modules/test_unsupported_kmod.py, tests/integration/tier0/non-destructive/oracle-linux-unbreakable-enterprise-kernel/test_oracle_unsupported_uek.py, tests/integration/tier0/non-destructive/single-yum-transaction-validation/test_single_yum_transaction_validation.py
Jira Issues: [RHELC-1104](https://issues.redhat.com/browse/RHELC-1104)
Checklist
=> [RHELC-1104] Change the id separator in the cli report to match what will be displayed in the insights webUI

convert2rhel/systeminfo.py, convert2rhel/toolopts.py, convert2rhel/unit_tests/toolopts_test.py, man/__init__.py, tests/integration/conftest.py, tests/integration/tier0/non-destructive/assessment-report/main.fmf, tests/integration/tier0/non-destructive/assessment-report/test_assessment_report.py, tests/integration/tier0/non-destructive/basic-sanity-checks/test_basic_sanity_checks.py, tests/integration/tier0/non-destructive/main.fmf, tests/integration/tier1/non-destructive/main.fmf
This PR updates the CLI to accept the new analyze subcommand. There is also a function called _organize_cli_options introduced to reorder the CLI arguments properly.
Jira Issues: [RHELC-970](https://issues.redhat.com/browse/RHELC-970)
Checklist
=> [RHELC-970] Update CLI to introduce new subcommands for pre conversion analysis

.packit.yaml, tests/integration/conftest.py, tests/integration/tier0/non-destructive/sub-man-rollback/test_sub_man_rollback.py, tests/integration/tier0/non-destructive/system-release-backup/test_system_release_backup.py
* update the code to handle the pexpect.TIMEOUT better; in a case the TIMEOUT is raised, do not close the connection, but send SIGINT to the process
* This will send the convert2rhel to the rollback, not breaking the system
* remove the os_release_hardening fixture as naive, not reliable workaround
Add an option to call just non-destructive tests
* use /packit test --labels
(tier0-non-destructive|tier1-non-destructive|non-destructive)
Jira Issues: [RHELC-1129](https://issues.redhat.com/browse/RHELC-1129)
Checklist
=> [RHELC-1129] Update the convert2rhel contextmanager

.github/workflows/label-commenter.yml, .packit.yaml, convert2rhel/applock.py, convert2rhel/initialize.py, convert2rhel/main.py, convert2rhel/unit_tests/applock_test.py, convert2rhel/unit_tests/initialize_test.py, convert2rhel/unit_tests/main_test.py, pytest.ini, tests/integration/tier0/non-destructive/application-lock/main.fmf, tests/integration/tier0/non-destructive/application-lock/test_application_lock.py
Adds an ApplicationLock class that prevents two instances of convert2rhel from running on the same system. An attempt to start a second instance will result in it emitting an error message and exiting.
Jira Issues: [RHELC-1099](https://issues.redhat.com/browse/RHELC-1099)
Checklist
=> [RHELC-1099] Prevent simultaneous instances of convert2rhel on a single system.

convert2rhel/actions/system_checks/dbus.py, convert2rhel/unit_tests/actions/system_checks/dbus_test.py
This PR changes the level for a dbus check skip from warning to info.
Checklist
=> Change level from warning to info for dbus check skip

convert2rhel/subscription.py
If the python3-syspurpose package is installed on the system prior to the conversion, it has a different NEVRA than subscription-manager requires. The subscription-manager is strict about it - the syspurpose VRA (version, release, arch) needs to match exactly the sub-man VRA. And because we're downloading the sub-man packages from UBI, the VRA doesn't match.
Previously we thought this issue affects just CentOS Linux 8 but it does affect Alma and Rocky 8 as well.
Follows-up on #869.
=> Fix sub-man installation on Alma and Rocky 8

convert2rhel/initialize.py, convert2rhel/main.py, convert2rhel/unit_tests/initialize_test.py, convert2rhel/unit_tests/main_test.py
This adds some changes that were accidentally omitted when PR891 was merged. They are necessary to avoid a bug related to importing certain packages in initialize.py.
Jira Issues: [RHELC-1099](https://issues.redhat.com/browse/RHELC-1099)
Checklist
=> [RHELC-1099] Move application lock into main.

.packit.yaml
* with changes in packit/packit-service#2168 we can now move the targeted OS back under the distros key
Jira Issues: [RHELC-1155](https://issues.redhat.com/browse/RHELC-1155)
Checklist
=> [RHELC-1155] Move target compose definition in packit.yaml

convert2rhel/actions/system_checks/package_updates.py, convert2rhel/unit_tests/actions/system_checks/package_updates_test.py
This PR adds sorting to the packages displayed in the package_not_up_to_date_message and adds a remediation to tell the user to run 'yum update' to update the packages on their system.
Jira Issues: [RHELC-1156](https://issues.redhat.com/browse/RHELC-1156)
Checklist
=> [RHELC-1156] Display system packages that are not up to date in alphabetical order

convert2rhel/systeminfo.py
This patch doesn't add any new functionality. It only refactors some cosmetics around the SystemInfo object, such as
* fixes a typo in the doc string
* moves static object out of the class definition
* simplifies the logging in one function
* handles distribution_id consistently with other params.
Each change is done via a separate commit, so they can be reviewed separately or alltogether. 
Checklist
=> Cosmetic fixes for the SystemInfo

.github/workflows/generate_manpage.yml, .github/workflows/release.yml, scripts/manpage_generation.sh
Convert2RHEL has moved away from using optparse, and we have decided to use argparse to generate our manpages now; this PR will change this by adding in a bash script to generate the manpages using argparse, and then it will be automated using GitHub actions.
Jira Issues: [RHELC-1037](https://issues.redhat.com/browse/RHELC-1037)
Checklist
=> [RHELC-1037] Auto-generate manpages

.github/renovate.json
Renovate should now apply `no-changelog` and `tests-skip` to its own PRs
Checklist
=> Update Renovate to auto-label its PRs

.github/workflows/generate_manpage.yml
In the GitHub action, the command for installing the argparse-manpage is not spelled correctly. This was causing argparse-manpage to not install properly.
Jira Issues: [RHELC-1037](https://issues.redhat.com/browse/RHELC-1037)
Checklist
=> [RHELC-1037] fix for typo in generate_manpage github action

convert2rhel/toolopts.py, man/__init__.py, man/convert2rhel.8
The -y option was being registered under the parent options (as if not related to subcommands) but it is more appropriate to have it under the subcommand options.
Follows up on https://github.com/oamg/convert2rhel/pull/917#discussion_r1329972458.
Jira Issues: [RHELC-1150](https://issues.redhat.com/browse/RHELC-1150)
Checklist
=> [RHELC-1150] Move -y option out of parent options

convert2rhel/actions/__init__.py, convert2rhel/actions/report.py, convert2rhel/unit_tests/actions/actions_test.py, convert2rhel/unit_tests/actions/report_test.py
Based on conversation with Marek Hulan from Satellite in which he will be showing to the user the text form of the pre-conversion analysis report, we decided to change the default message from `[No further information given]` to `N/A`.
This is how a text report looked like before this change - [report.txt](https://github.com/oamg/convert2rhel/files/12737729/report.txt) - not that easy to read because of the many `[No further information given]` messages.
What do you think about this change, @mportman12 ?
Jira Issues: [RHELC-1055](https://issues.redhat.com/browse/RHELC-1055)
Checklist
=> [RHELC-1055] Change the default message in report

ansible/setup-convert2rhel.yml
Convert2RHEL has been made available under a new domain that does not require downloading the Red Hat's self-signed SSL cert - cdn-public.redhat.com.
Our public repofiles have been updated accordingly: https://ftp.redhat.com/redhat/convert2rhel/<major ver>/convert2rhel.repo
This update makes use of the updated repofiles and stops downloading the self-signed SSL cert that is no longer needed.
Also, the source distribution validation is updated to reflect the fact that convert2rhel supports converting Alma and Rocky.
Jira Issues: [RHELC-1166](https://issues.redhat.com/browse/RHELC-1166)
Checklist
=> [RHELC-1166] Playbook to install convert2rhel from cdn-public.redhat.com

convert2rhel/unit_tests/__init__.py, convert2rhel/unit_tests/actions/pre_ponr_changes/backup_system_test.py, convert2rhel/unit_tests/actions/pre_ponr_changes/handle_packages_test.py, convert2rhel/unit_tests/actions/pre_ponr_changes/transaction_test.py, convert2rhel/unit_tests/actions/system_checks/convert2rhel_latest_test.py, convert2rhel/unit_tests/actions/system_checks/custom_repos_are_valid_test.py, convert2rhel/unit_tests/actions/system_checks/efi_test.py, convert2rhel/unit_tests/actions/system_checks/rhel_compatible_kernel_test.py, convert2rhel/unit_tests/backup_test.py, convert2rhel/unit_tests/cert_test.py, convert2rhel/unit_tests/checks_test.py, convert2rhel/unit_tests/grub_test.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/pkgmanager/handlers/yum/yum_test.py, convert2rhel/unit_tests/redhatrelease_test.py, convert2rhel/unit_tests/subscription_test.py, convert2rhel/unit_tests/systeminfo_test.py, convert2rhel/unit_tests/utils_test.py, pytest.ini
Deduplicates many mock classes and ports away from unit_tests.MockFunction to unit_tests.MockFunctionObject.
Note that there are still functions which are using Mocked Functions inside of the specific unit_test files instead of the shared unit_tests.  It doesn't look like many of these are shared, though.
There are also a great many tests using one-off mocks like this:
```
dummy_mock = mock.Mock()
PkgName = namedtuple("PkgNames", ["name"])
transaction_pkgs = [PkgName(package) for package in packages]
monkeypatch.setattr(pkgmanager.Base, "read_all_repos", value=dummy_mock)
monkeypatch.setattr(pkgmanager.Base, "fill_sack", value=dummy_mock)
monkeypatch.setattr(pkgmanager.Base, "upgrade_all", value=dummy_mock)
monkeypatch.setattr(pkgmanager.Base, "resolve", value=dummy_mock)
```
Most of …
=> [RHELC-474] Deduplicate mocking classes

convert2rhel/actions/__init__.py
This PR updates the set result for each "SKIP" result to have an updated description as well as diagnosis and remediation fields. 
Jira Issues: [RHELC-1163](https://issues.redhat.com/browse/RHELC-1163)
Checklist
=> [RHELC-1163] Update Skip results to have diagnosis and remediation fields

convert2rhel/actions/pre_ponr_changes/backup_system.py, convert2rhel/backup.py, convert2rhel/exceptions.py, convert2rhel/logger.py, convert2rhel/main.py, convert2rhel/unit_tests/__init__.py, convert2rhel/unit_tests/actions/pre_ponr_changes/backup_system_test.py, convert2rhel/unit_tests/backup_test.py, convert2rhel/unit_tests/logger_test.py, convert2rhel/unit_tests/main_test.py
We do not want to show "UNKNOWN_ERROR" in the insights WebUI.  To get away from that we need to return enough information from where the actual Action happened to where
Documentation on how to port is listed here:
https://github.com/oamg/convert2rhel/wiki/Action-Framework#actions-and-systemexitsysexit
* This implements https://issues.redhat.com/browse/RHELC-1170
* This establishes the framework to fix: https://issues.redhat.com/browse/RHELC-965
The ticket can be marked done once all the Actions have been ported to use this exception framework.
* This is also a small part of: https://issues.redhat.com/browse/RHELC-1168 (porting the Action framework logger.critical to logger.critical_no_exit().) …
=> [RHELC-965,RHELC-1170] Framework to remove UNKNOWN_ERROR from the Assessment.

.packit.yaml, convert2rhel/actions/report.py, convert2rhel/main.py, convert2rhel/unit_tests/actions/report_test.py, convert2rhel/unit_tests/main_test.py, tests/integration/tier0/non-destructive/assessment-report/main.fmf, tests/integration/tier0/non-destructive/assessment-report/test_assessment_report.py
How it works:
- it generates the /var/log/convert2rhel/convert2rhel-pre-conversion.txt every time when the summary is printed
- contains everything except SUCCESS (INFO, WARNING, SKIP, OVERRIDABLE and ERROR are included)
- content is ordered from ERROR to INFO. So the ERROR will be on the top of the file
- in the file is only info from the last run
Example of the file under Jira issue
Jira Issues: [RHELC-1055](https://issues.redhat.com/browse/RHELC-1055)
Depends on https://github.com/oamg/convert2rhel/pull/903
Checklist
=> [RHELC-1055] Print pre-conversion report to txt file

convert2rhel/cert.py, convert2rhel/unit_tests/cert_test.py
=> [RHELC-965] Change `UNKNOWN_ERROR` to be more verbose with certificates

convert2rhel/backup.py, convert2rhel/unit_tests/backup_test.py
Converts two UNKNOWN_ERROR instances in package install/remove to use exceptions.CriticalError.
Checklist
=> [RHELC-965] Change `UNKNOWN_ERROR` to be more verbose with backup

.gitignore
Add TAGS (emacs tags file) to the list of files ignored by git.
Checklist
=> Add emacs TAGS file to .gitignore.

.github/workflows/build_images.yml, .github/workflows/coverage.yml, .github/workflows/release.yml, .github/workflows/tests.yml
This PR contains updates to the github workflow to enable el9 conversions taken from the larger PR - #883.
Until we get confirmation that everything works fine we will keep this in draft.
Jira Issues: [RHELC-1102](https://issues.redhat.com/browse/RHELC-1102)
Checklist
=> [RHELC-1102] Enable el9 conversions github workflow updates

convert2rhel/unit_tests/actions/pre_ponr_changes/kernel_modules_test.py
One of the tests in kernel_module_tests was missing a mock and causing problems where the lsmod binary was not found in the system after running the tests.
Checklist
=> Update kernel_module_tests with missing mock

plans/tier0.fmf, plans/tier1.fmf
Due to recent changes to tmt (multihost update) we have to make sure that all the test phases have unique names.
Previously the test jobs were failing with the following:
`Duplicate phase name 'reboot machine' in step 'prepare'.`
http://artifacts.osci.redhat.com/testing-farm/d701f487-6f44-4a00-82c9-b71620afe9f4/
http://artifacts.osci.redhat.com/testing-farm/c3455c3a-c9dc-4379-8be5-15f80812b56b/
Reference discussion: https://redhat-internal.slack.com/archives/C03BRN71JAF/p1697808031918609
=> Rename duplicate test phase names

convert2rhel/actions/pre_ponr_changes/kernel_modules.py, convert2rhel/actions/system_checks/rhel_compatible_kernel.py, convert2rhel/pkghandler.py, convert2rhel/pkgmanager/handlers/dnf/__init__.py, convert2rhel/redhatrelease.py, convert2rhel/repo.py, convert2rhel/subscription.py, convert2rhel/systeminfo.py, convert2rhel/unit_tests/subscription_test.py, convert2rhel/utils.py
This PR contains general updates to some main convert2rhel files and unit tests to enable el9 conversions taken from the larger PR - #883.
Until we get confirmation that everything works fine we will keep this in draft.
Jira Issues: [RHELC-1102](https://issues.redhat.com/browse/RHELC-1102)
Checklist
=> [RHELC-1102] Enable el9 conversions general updates

convert2rhel/actions/__init__.py, convert2rhel/unit_tests/actions/actions_test.py
This PR ensures that no action result with level set to "SUCCESS" has the fields description, diagnosis or remediation set. A custom exception `InvalidMessageError` will be raised if any of the fields are detected when setting the level field to "SUCCESS". This change is targeted for the 1.6 release of convert2rhel.
Jira Issues: [RHELC-1098](https://issues.redhat.com/browse/RHELC-1098)
Checklist
=> [RHELC-1098] Change Action results so that no information is given in SUCCESS results

convert2rhel/actions/system_checks/rhel_compatible_kernel.py, convert2rhel/unit_tests/actions/pre_ponr_changes/kernel_modules_test.py, convert2rhel/unit_tests/actions/system_checks/rhel_compatible_kernel_test.py
The old method we used was causing a backtrace during the fingerprint verification as it was consulting the yumdb and in return it was reporting metadata that was not relevant.
This commit introduces an minimal refactor that changes the way we query for the package, so instead of relying in querying the rpmdb first, we use rpm directly to do the job.
Jira Issues: [RHELC-1117](https://issues.redhat.com/browse/RHELC-1117)
Checklist
=> [RHELC-1117] Fix backtrace in kernel signature verification

convert2rhel/backup.py, convert2rhel/unit_tests/__init__.py, convert2rhel/unit_tests/backup_test.py, convert2rhel/unit_tests/main_test.py
Previously, if a RestorableChange managed by BackupController raised an exception on restore, then we would stop rollback.  This change makes it so we try to restore every change even if previous ones have failed.
Jira Issues: [RHELC-1154](https://issues.redhat.com/browse/RHELC-1154)
Checklist
=> [RHELC-1154] Try to rollback all changes even if one of them fails.

convert2rhel/actions/pre_ponr_changes/kernel_modules.py, convert2rhel/pkghandler.py, convert2rhel/unit_tests/actions/pre_ponr_changes/kernel_modules_test.py, convert2rhel/unit_tests/pkghandler_test.py
When repoquery fails to run (for instance, when repoquery decides that there isn't enough disk space to download metadata from the repository), we were printing an error message that there were no kmod containing packages.  With this change, we will print an error message that says repoquery failed.
Fixes https://issues.redhat.com/browse/RHELC-895
Fixes #610
Jira Issues: [RHELC-895](https://issues.redhat.com/browse/RHELC-895)
Checklist
=> [RHELC-895] Fix error message when repoquery fails to retrieve information on kmod packages

convert2rhel/actions/pre_ponr_changes/handle_packages.py, convert2rhel/unit_tests/actions/pre_ponr_changes/handle_packages_test.py
This PR adds the "OVERRIDABLE" result in areas where the ask_to_continue() function was previously removed. The change allows for users to skip these checks by setting an environment variable. 
Jira Issues: [RHELC-1089](https://issues.redhat.com/browse/RHELC-1089)
Checklist
=> [RHELC-1089] Add OVERRIDABLE result to handle_packages.py

convert2rhel/actions/system_checks/package_updates.py, convert2rhel/unit_tests/actions/system_checks/package_updates_test.py
This PR adds the "OVERRIDABLE" result in areas where the ask_to_continue() function was previously removed. The change allows for users to skip these checks by setting an environment variable.
Jira Issues: [RHELC-1089](https://issues.redhat.com/browse/RHELC-1089)
Checklist
=> [RHELC-1089] Add OVERRIDABLE result to package_updates.py

convert2rhel/pkghandler.py, convert2rhel/unit_tests/pkghandler_test.py
A bug processing output from the repoquery command caused packages with an Epoch equal to 2 to raise an exception in the third-party package listing task. This change fixes the processing.
Jira Issues: [RHELC-1225](https://issues.redhat.com/browse/RHELC-1225)
Checklist
=> [RHELC-1225] Fix an exception when listing third-party packages with Epoch 2

convert2rhel/actions/system_checks/custom_repos_are_valid.py, convert2rhel/unit_tests/actions/system_checks/custom_repos_are_valid_test.py
The `"Skipping the check of repositories due to the use of RHSM for the conversion"` informational message is confusing in the pre-conversion report as it does not have the context it has in the terminal where it's pre-empted by `"TASK - [Prepare: Check if --enablerepo repositories are accessible]"`.
This message would add no value for the user even if the context is added. Hence the removal.
Jira Issues: [RHELC-1242](https://issues.redhat.com/browse/RHELC-1242)
Checklist
=> [RHELC-1242] Remove "Skipping the check of repos" from report

convert2rhel/subscription.py, convert2rhel/unit_tests/subscription_test.py
Yumdownloader was downloading two different versions of the subscription-manager-rhsm-certificates package and convert2rhel failed when it wanted to install both at the same time.
subscription-manager-rhsm-certificates-1.28.36-3.el8_8.x86_64 subscription-manager-rhsm-certificates-20220623-1.el8.noarch
Pino Toscano from the subscription-manager team told us that the version 20220623 is the latest and the one we should be installing.
Since the two versions have different architecture, this quick solution is making sure that only the noarch one is downloaded and installed.
The same applies to conversions to RHEL 9. We were downloading incorrectly the x86_64 version of the package which is not the latest.
Jira Issues: [RHELC-1246](https://issues.redhat.com/browse/RHELC-1246)
Checklist
=> [RHELC-1246] Fix sub-man installation on EL8

Makefile
As pytest runs in a container in a read-only folder, the cache can not be created, thus it issues a warning.
This parameter disables the warning, so that the output looks cleaner.
Checklist
- NA Jira issue has been made public if possible
- NA `[RHELC-]` is part of the PR title 
- NA Code and tests are documented properly
- NA When merged: Jira issue has been updated to `Release Pending` if relevant
=> Disable cache for pytest

convert2rhel/actions/report.py, convert2rhel/unit_tests/actions/report_test.py
We reverse the order of items in the summary and adjust hardcoded test data accordingly.
Jira Issues: [RHELC-1096](https://issues.redhat.com/browse/RHELC-1096)
Checklist
=> [RHELC-1096] Change the sorting order for the report

convert2rhel/actions/pre_ponr_changes/handle_packages.py, convert2rhel/unit_tests/actions/pre_ponr_changes/handle_packages_test.py
This PR reverts the addition of an overridable result for the third party package check in handle_packages.py. The third party package check now only reports a warning if there are third party packages on the system. 
We've decided that this overridable would cause a bad user experience because the majority of users are expected to have third party packages installed (e.g. from EPEL) so almost everybody would need to use the environment variable to override the inhibitor. But having third party packages installed causes no issue for the conversion process. We just need to tell the user that the third party rpms won't be converted and with that Red Hat won't provide support for them. A warning in the pre-conversion analysis report is sufficient for that.
Jira Issues: …
=> [RHELC-1089] Revert overridable result in package handling check

convert2rhel/subscription.py, convert2rhel/unit_tests/subscription_test.py
The https://github.com/oamg/convert2rhel/pull/991 was dealing with a convert2rhel failure stemming from two different architectures of the subscription-manager-rhsm-certificates package being available in UBI repos. That fix however caused convert2rhel failures on older system minor versions where only x86_64 arch was available.
In the meantime Pino Toscano asked to have the UBI repos fixed in a way that there is now just one architecture of the package. With that we don't need to hardcode a specific arch in convert2rhel.
Jira Issues: [RHELC-1252](https://issues.redhat.com/browse/RHELC-1252)
Checklist
=> [RHELC-1252] Fix sub-man-rhsm-certs installation on 8.5/8.8

.packit.yaml, plans/main.fmf, pytest.ini, tests/ansible_collections/roles/install-testing-deps/tasks/main.yml, tests/integration/common/checks-after-conversion/test_release_version.py, tests/integration/tier0/non-destructive/assessment-report/main.fmf, tests/integration/tier0/non-destructive/assessment-report/test_assessment_report.py, tests/integration/tier0/non-destructive/eus/main.fmf, tests/integration/tier0/non-destructive/problematic-third-party-pkgs/main.fmf, tests/integration/tier0/non-destructive/problematic-third-party-pkgs/test_problematic_third_party_pkgs.py
* new integration tests verifying the overridable check list third party packages and verifying that listing the packages won't fail with packages reported as problematic
* set the CONVERT2RHEL_THIRD_PARTY_PACKAGE_CHECK_SKIP envar to the root of the test metadata to mitigate failing tests due to third party packages (convert2rhel copr build included)
* modify the test_release_version check after conversion to handle 8.9 release
Jira Issues: 
* [RHELC-1225](https://issues.redhat.com/browse/RHELC-1225)
* [RHELC-1227](https://issues.redhat.com/browse/RHELC-1227)
Checklist
=> [RHELC-1089, RHELC-1225] Add integration tests

convert2rhel/actions/pre_ponr_changes/handle_packages.py, convert2rhel/unit_tests/actions/pre_ponr_changes/handle_packages_test.py
With the current setup of the conditionals in handle_packages, there are cases where a message explaining that packages were removed will be made regardless if there are any packages removed or not. This PR changes the conditionals to only display the packages removed message when there are packages contained inside the pkgs_removed variable. 
Jira Issues: [RHELC-1270](https://issues.redhat.com/browse/RHELC-1270)
Checklist
=> [RHELC-1270] Update package handling check to properly report removed packages

convert2rhel/actions/report.py, convert2rhel/unit_tests/actions/report_test.py, schemas/assessment-schema-1.1.json, tests/integration/tier0/non-destructive/assessment-report/test_assessment_report.py
This PR adds a function find_highest_report_level to report.py to get the highest status level within the results and messages reported in the analysis. This highest status level is added as a new key to the report json at the top level for use in the rhc worker script. 
Jira Issues: [RHELC-1193](https://issues.redhat.com/browse/RHELC-1193)
Checklist
=> [RHELC-1193] Identify highest status in json report

convert2rhel/actions/pre_ponr_changes/handle_packages.py, convert2rhel/unit_tests/actions/pre_ponr_changes/handle_packages_test.py
Currently the pre-conversion analysis report states that certain packages were removed. But by the end of the conversion a rollback happens and the packages are installed back. So at the time of reading the report the packages are no longer removed.
This change rewords the messages to state that the packages are to be removed during the conversion.
Jira Issues: [RHELC-1241](https://issues.redhat.com/browse/RHELC-1241)
Checklist
=> [RHELC-1241] Make report messages about removed packages less confusing

convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py
The yumdownloader output seems to be printing a carriage return character on CentOS Linux 7 when the package to be downloaded is already downloaded. It prints:
`using local copy of centos-logos-70.0.6-3.el7.centos.noarch\r`
That lead convert2rhel to fail on the rollback:
```
Installing packages:
.rpm    /var/lib/convert2rhel/backup/centos-logos-70.0.6-3.el7.centos.noarch
```
Jira Issues: [RHELC-1272](https://issues.redhat.com/browse/RHELC-1272)
Checklist
=> [RHELC-1272] Fix parsing yumdownloader output with a carriage return

.github/workflows/release.yml, scripts/manpage_generation.sh
Supersedes #876 by doing it a bit more botched so that it will work for subsequent releases at least
Jira Issues: [RHELC-1037](https://issues.redhat.com/browse/RHELC-1037)
Checklist
=> [RHELC-1037] Add manpage generation to all releases

convert2rhel/actions/pre_ponr_changes/kernel_modules.py, convert2rhel/unit_tests/actions/pre_ponr_changes/kernel_modules_test.py
On systems that do not have /usr/sbin/ in the PATH, simply calling modinfo instead of /usr/sbin/modinfo would fail.
Jira Issues: [RHELC-1308](https://issues.redhat.com/browse/RHELC-1308)
Checklist
=> [RHELC-1308] Specify a full path to the called modinfo utility

convert2rhel/actions/system_checks/convert2rhel_latest.py, convert2rhel/unit_tests/actions/system_checks/convert2rhel_latest_test.py
Convert2RHEL is moving away from using the word unsupported, and we will gradually go away from using this terminology. This PR also goes through the log message to better explain how the conversion can fail.
* Add sanity test to verify the deprecated `CONVERT2RHEL_UNSUPPORTED_INCOMPLETE_ROLLBACK` envar is still allowed
Jira Issues: 
- [RHELC-750](https://issues.redhat.com/browse/RHELC-750)
- [RHELC-1005](https://issues.redhat.com/browse/RHELC-1005)
Checklist
=> [RHELC-750, RHELC-1005] Rewrite the log messages in download_pkg() to not use "unsupported"

convert2rhel/actions/system_checks/rhel_compatible_kernel.py, convert2rhel/data/8/x86_64/configs/almalinux-8-x86_64.cfg
With the latest packages signed with a new GPG key, said packages were recognized as third-party.
Add the GPG fingerprint to recognized in the config.
Jira Issues: [RHELC-1370](https://issues.redhat.com/browse/RHELC-1370)
Checklist
=> [RHELC-1370] Fix Alma Linux 8 packages being seen as third-party 

convert2rhel/breadcrumbs.py, convert2rhel/unit_tests/breadcrumbs_test.py
The _set_env() method was missing in the breadcrumbs early data collection. This commit introduces the function in the early collection again.
Jira Issues: [RHELC-1307](https://issues.redhat.com/browse/RHELC-1307)
Checklist
=> [RHELC-1307] Collect environment variables in breadcrumbs

convert2rhel/actions/system_checks/is_loaded_kernel_latest.py, convert2rhel/unit_tests/actions/system_checks/is_loaded_kernel_latest_test.py, tests/integration/tier0/non-destructive/system-release-backup/main.fmf, tests/integration/tier0/non-destructive/system-release-backup/test_system_release_backup.py, tests/integration/tier1/destructive/kernel-check-skip/main.fmf, tests/integration/tier1/destructive/kernel-check-skip/test_latest_kernel_check_skip.py, tests/integration/tier1/destructive/one-kernel-scenario/run_conversion.py, tests/integration/tier1/destructive/system-up-to-date/test_system_up_to_date.py
Convert2RHEL is moving away from using the word unsupported, and we will gradually go away from using this terminology. This PR also goes through the log message to better explain how the conversion can fail.
Jira Issue: [RHELC-750](https://issues.redhat.com/browse/RHELC-750)
Checklist
=> [RHELC-750] Rewrite the log messages using the word "unsupported"  in is_loaded_kernel_latest()

convert2rhel/unit_tests/actions/system_checks/is_loaded_kernel_latest_test.py
There were leftover `remediation` usage in #684 that needs to be changed to the new `remediations`
After the fix:
Checklist
=> Fix leftover remediation from #684

convert2rhel/actions/system_checks/convert2rhel_latest.py, convert2rhel/actions/system_checks/is_loaded_kernel_latest.py, convert2rhel/actions/system_checks/package_updates.py, convert2rhel/unit_tests/actions/system_checks/convert2rhel_latest_test.py, convert2rhel/unit_tests/actions/system_checks/is_loaded_kernel_latest_test.py, convert2rhel/unit_tests/actions/system_checks/package_updates_test.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py
Some of our remediation messages have used 'ignore' to tell the user they can override certain checks, example - "If you wish to ignore this message, set the environment variable 'CONVERT2RHEL_OUTDATED_PACKAGE_CHECK_SKIP' to 1". Using the word 'disregard' sounds better in this context so each instance of that has been changed.
Jira Issues: [RHELC-1372](https://issues.redhat.com/browse/RHELC-1372)
Checklist
=> [RHELC-1372] Change ignore to disregard in messages

convert2rhel/actions/system_checks/package_updates.py, convert2rhel/unit_tests/actions/system_checks/package_updates_test.py
This PR adds a remediation to the overrdiable result in the package_updates.py action. The remediation lets the user know they can set an environment variable to skip the OUT_OF_DATE_PACKAGES check within the action.
Jira Issues: [RHELC-1378](https://issues.redhat.com/browse/RHELC-1378)
Checklist
=> [RHELC-1378] Add remediation to overridable result in package updates action

convert2rhel/logger.py, convert2rhel/main.py, convert2rhel/unit_tests/__init__.py, convert2rhel/unit_tests/conftest.py, convert2rhel/unit_tests/logger_test.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py, tests/integration/tier0/non-destructive/basic-sanity-checks/test_basic_sanity_checks.py
To do
In short of the changes:
- Split the log handlers into an initialize and finalize function, where FileHandler is added later
- Logging when not being root no longer causes logs to not work or function correctly (as FileHandler isn't added)
- Also fixes the issue of clearing the log files if a duplicate process is found, we just initialize the FileHandler later
- Custom memory buffer is added to keep the last 100 logs, and once FileHandler is added we instantly log the buffer to it
Jira Issues: 
- [RHELC-1131](https://issues.redhat.com/browse/RHELC-1131)
- [RHELC-1234](https://issues.redhat.com/browse/RHELC-1234)
Checklist
=> [RHELC-1131, RHELC-1234] Refactor logger to not require root

convert2rhel/actions/system_checks/tainted_kmods.py, convert2rhel/unit_tests/actions/system_checks/tainted_kmods_test.py
This PR adds an overridable result to the tainted kernel module check allowing users to override in the event of a tainted kernel module detected on the system. Additionally improves the message to the user to not alarm them along with some documentation explaining what a tainted kernel module is. 
Jira Issues: [RHELC-1200](https://issues.redhat.com/browse/RHELC-1200)
Checklist
=> [RHELC-1200] Add OVERRIDABLE result to tainted kernel module check

convert2rhel/actions/system_checks/tainted_kmods.py, convert2rhel/unit_tests/actions/system_checks/tainted_kmods_test.py
Leftover from #1015 
To do:
Checklist
=> Change ignore to disregard in tainted kmods function

.devcontainer/devcontainer.json
The settings property was outside the "customization/vscode", thus, triggering a warning in the file itself.
Checklist
=> Move settings property to match the correct structure

.devcontainer/devcontainer.json
Without setting the language server to Pylance, the devcontainer was sometimes failling to initialize the server.
Checklist
=> Add language server to devcontainer

convert2rhel/actions/pre_ponr_changes/kernel_modules.py, convert2rhel/actions/pre_ponr_changes/special_cases.py, convert2rhel/actions/pre_ponr_changes/subscription.py, convert2rhel/actions/system_checks/check_firewalld_availability.py, convert2rhel/actions/system_checks/convert2rhel_latest.py, convert2rhel/actions/system_checks/custom_repos_are_valid.py, convert2rhel/actions/system_checks/dbus.py, convert2rhel/actions/system_checks/is_loaded_kernel_latest.py, convert2rhel/actions/system_checks/package_updates.py, convert2rhel/unit_tests/actions/pre_ponr_changes/kernel_modules_test.py, convert2rhel/unit_tests/actions/pre_ponr_changes/special_cases_test.py, convert2rhel/unit_tests/actions/pre_ponr_changes/subscription_test.py, convert2rhel/unit_tests/actions/system_checks/check_firewalld_availability_test.py, convert2rhel/unit_tests/actions/system_checks/convert2rhel_latest_test.py, convert2rhel/unit_tests/actions/system_checks/custom_repos_are_valid_test.py, convert2rhel/unit_tests/actions/system_checks/dbus_test.py, convert2rhel/unit_tests/actions/system_checks/is_loaded_kernel_latest_test.py, convert2rhel/unit_tests/actions/system_checks/package_updates_test.py, tests/integration/tier0/non-destructive/kernel/test_kernel_check_verification.py, tests/integration/tier0/non-destructive/subscription-manager/test_sub_man_pre_register.py
This PR replaces the use of 'skip' and 'skipping' with 'Did not perform' in the preconversion analysis report messages so as to not create confusion with the skip status put in place for when we cannot run an action because another one failed. 
Jira Issues: [RHELC-1173](https://issues.redhat.com/browse/RHELC-1173)
Checklist
=> [RHELC-1173] Replace the word `skip` in report messages

convert2rhel/actions/system_checks/package_updates.py, convert2rhel/unit_tests/actions/system_checks/package_updates_test.py
This PR changes an OVERRDIABLE result to a WARNING message in actions/package_updates.py for the case when a failure occurs in checking whether the installed packages on a system are up to date. This is to prevent the previous behavior of inhibiting the conversion when the mentioned check fails.
Jira Issues: [RHELC-1295](https://issues.redhat.com/browse/RHELC-1295)
Checklist
=> [RHELC-1295] Change OVERRIDABLE result to WARNING message in package update action

tests/integration/tier0/non-destructive/basic-sanity-checks/test_basic_sanity_checks.py
Splitting the string checking in the root_privileges test to assert that the needed messages are contained in the result output.
Checklist
=> Fix root_privileges test string checking

.github/renovate.json
=> Fix renovate to ignore all centos7 containers

.github/renovate.json
=> Renovate to ignore centos7 requirements file

convert2rhel/backup/files.py, convert2rhel/unit_tests/actions/pre_ponr_changes/backup_system_test.py, convert2rhel/unit_tests/backup/backup_test.py, convert2rhel/unit_tests/backup/files_test.py
There was a clash happening in the way we backup files, as if there is a file to backup that has the same name as one directory or another file already created, an error will be thrown to the user.
This commit fixes that clash by generating an hash directory based on the dirname of the absolute path.
Jira Issues: [RHELC-1361](https://issues.redhat.com/browse/RHELC-1361)
Checklist
=> [RHELC-1361] Fix file clash in NewRestorableFile

convert2rhel/actions/pre_ponr_changes/subscription.py, convert2rhel/backup/__init__.py, convert2rhel/backup/certs.py, convert2rhel/pkghandler.py, convert2rhel/unit_tests/actions/pre_ponr_changes/subscription_test.py, convert2rhel/unit_tests/backup/backup_test.py, convert2rhel/unit_tests/backup/certs_test.py, convert2rhel/unit_tests/conftest.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/subscription_test.py
Both the RestorableRpmKey and the PEMCert classes got migrated to their own module inside the backup folder.
Jira Issues: [RHELC-1379](https://issues.redhat.com/browse/RHELC-1379)
Checklist
=> [RHELC-1379] Port certs and restorable key to backup module

convert2rhel/backup/packages.py, convert2rhel/pkghandler.py, convert2rhel/subscription.py, convert2rhel/unit_tests/backup/packages_test.py, convert2rhel/unit_tests/pkghandler_test.py
RestorablePackageSet is moved to be under the packages module inside the backup folder. This is one part of the refactoring of the backup controller to make it more organized and easier to work with.
Jira Issues: [RHELC-1381](https://issues.redhat.com/browse/RHELC-1381)
Checklist
=> [RHELC-1381] Port RestorablePackageSet to packages module

.github/workflows/autotag.yml
As it was before, it would create a new tag with
the run number, so if no tags were created by us
it would look something like
- `v1.2.3-1`
- `v1.2.3-1-2`
- `v1.2.3-1-2-3`
- and so on.
To fix this we'll do a substring and
add epoch. Which will look like
- `v1.2.3-1707318660`
- `v1.2.3-1707318661`
- and so on.
Checklist
=> chore: update autotag naming

tests/integration/tier0/non-destructive/application-lock/main.fmf, tests/integration/tier0/non-destructive/application-lock/test_application_lock.py
* validate that second invocation of convert2rhel honors the already running process' logging
* validate the log does not get overwritten by the second invocation
Jira Issues: [RHELC-1239](https://issues.redhat.com/browse/RHELC-1239)
Checklist
=> [RHELC-1239] Add integration test for correct logging

.github/workflows/release.yml
This updates the release workflow to also update the release once it has been published to include links to the Jira issues. Has tested and works as intended
https://github.com/SpyTec/convert2rhel/releases/tag/v24.02.07.7
Checklist
=> chore: Update Jira links in releases

convert2rhel/actions/system_checks/efi.py, convert2rhel/grub.py, convert2rhel/unit_tests/actions/system_checks/efi_test.py, convert2rhel/unit_tests/grub_test.py
This PR adds a conditional to check if there is no output received from a subprocess call to blkid querying for the devices PART_ENTRY_NUMBER. If there is no output we raise a custom BootloaderError exception telling the user their device has no PART_ENTRY_NUMBER. In addition we have a call made to the function calling blkid (_get_device_number)inside the preconversion analysis efi check so we can error out early in the execution of convert2rhel instead of in the conversion process in the event there is no PART_ENTRY_NUMBER. 
Jira Issues: [RHELC-1187](https://issues.redhat.com/browse/RHELC-1187)
Checklist
=> [RHELC-1187] Add preconversion analysis check for device PART_ENTRY_NUMBER

convert2rhel/actions/system_checks/is_loaded_kernel_latest.py
The remediation was missing a newline at the end of it to separate the steps to follow and the env var message.
Checklist
=> Fix remediation spacing in IsLoadedKernelLatest action

convert2rhel/actions/system_checks/duplicate_packages.py, convert2rhel/unit_tests/actions/system_checks/duplicate_packages_test.py
This PR adds a check to preconversion analysis to run "package-cleanup --dupes" to see if the users system contains multiple versions of the same package. If multiple versions of the same package are detected then an error is raised and the user is instructed to remove the duplicate packages with the help of the package-cleanup command. 
Jira Issues: [RHELC-1070](https://issues.redhat.com/browse/RHELC-1070)
Checklist
=> [RHELC-1070] Duplicate package check for preconversion analysis

convert2rhel/backup/files.py, convert2rhel/initialize.py, convert2rhel/main.py, convert2rhel/unit_tests/__init__.py, convert2rhel/unit_tests/initialize_test.py, convert2rhel/unit_tests/main_test.py
Initializing the logger module earlier makes the tool work correctly when trying to find the /etc/system-release file, and if it is not there, throw a critical error to the user before anything else happens.
If we don't move the module to this point, the first /etc/system-releaes check will silently fail and only the next call will throw the exception, because at this point, we already have the logger initialized.
To prevent further executions in the system, it is more reliable to initialize the logger module earlier.
Jira Issues: [RHELC-1393](https://issues.redhat.com/browse/RHELC-1393)
Checklist
=> [RHELC-1393] Move logger initialization to initialize module

convert2rhel/data/7/ppc64/configs/centos-7-ppc64.cfg, convert2rhel/data/7/x86_64/configs/centos-7-x86_64.cfg, convert2rhel/data/7/x86_64/configs/oracle-7-x86_64.cfg, convert2rhel/data/7/x86_64/configs/scientific-7-x86_64.cfg, convert2rhel/data/8/x86_64/configs/almalinux-8-x86_64.cfg, convert2rhel/data/8/x86_64/configs/centos-8-x86_64.cfg, convert2rhel/data/8/x86_64/configs/oracle-8-x86_64.cfg, convert2rhel/data/8/x86_64/configs/rocky-8-x86_64.cfg, convert2rhel/data/9/x86_64/configs/almalinux-9-x86_64.cfg, convert2rhel/data/9/x86_64/configs/oracle-9-x86_64.cfg, convert2rhel/data/9/x86_64/configs/rocky-9-x86_64.cfg, convert2rhel/pkgmanager/handlers/dnf/__init__.py, convert2rhel/pkgmanager/handlers/yum/__init__.py, convert2rhel/systeminfo.py, convert2rhel/unit_tests/pkgmanager/handlers/dnf/dnf_test.py, convert2rhel/unit_tests/pkgmanager/handlers/yum/yum_test.py, convert2rhel/unit_tests/systeminfo_test.py
The problem is related to how we remove the excluded packages. When “rpm -e –nodeps” is used, yum doesn’t know that the package was removed. On the removed package can be depending some other package (pkg1 depends on removed pkg). So then during processing the [yum operations](https://github.com/oamg/convert2rhel/blob/main/convert2rhel/pkgmanager/handlers/yum/__init__.py#L166) (_perform_operations), specifically update operation (reinstall is fine), the dependency (which was satisfied before conversion and then removed by us manually using rpm -e –nodeps) is not checked and results in missing dependency. 
This problem with not checking the dependency is solved in later versions, but in the one present in our converted systems. So we need to swap the packages mainly on CentOS 7 (and …
=> [RHELC-1130] Swap base os specific packages

convert2rhel/data/8/x86_64/configs/almalinux-8-x86_64.cfg, plans/tier0.fmf
The package is causing dependency problem with the kernel-core package, as both of them are marked for downgrade. The dependencies does not match.
This solution is used for Oracle Linux 7 as well, as we simply add the package to the exclude list as well.
Jira Issues: [RHELC-1190](https://issues.redhat.com/browse/RHELC-1190)
Checklist
=> [RHELC-1190] Add shim-x64 to the exclude list for Alma 8

.packit.yaml
* OL8.9 finally available on AWS, bump the target
=> chore:Bump Oracle Linux to 8.9 target in .packit.yaml

tests/integration/conftest.py, tests/integration/tier0/non-destructive/file-backup/main.fmf, tests/integration/tier0/non-destructive/file-backup/test_file_backup.py
* refactor the test_file_backup.py
* add validation of the file clash not happening during the backup
Jira Issues: [RHELC-1374](https://issues.redhat.com/browse/RHELC-1374)
Checklist
=> [RHELC-1374] Add integration tests for enhanced file backup

pytest.ini, tests/integration/tier0/non-destructive/duplicate-pkgs/main.fmf, tests/integration/tier0/non-destructive/duplicate-pkgs/test_duplicate_pkgs.py
Verify that the conversion does not crash when the same package (of different version) is installed on the system.
Verify that the proper inhibitor is raised. The bug is reproducible only on EL7 distros. On EL8 the issue is handled by the DNF itself.
Address the https://issues.redhat.com/browse/RHELC-1070
Jira Issues: [RHELC-1070](https://issues.redhat.com/browse/RHELC-1070),  [RHELC-1288](https://issues.redhat.com/browse/RHELC-1288)
Checklist
=> [RHELC-1288] Add integration test verifying duplicate pkgs installed

convert2rhel/pkgmanager/handlers/dnf/__init__.py, convert2rhel/unit_tests/pkgmanager/handlers/dnf/dnf_test.py
Without strict mode, dnf will not tell us if there is a dependency problem with a downgrade. This is necessary so we can make sure to fail during the analysis phase.
Checklist
=> Set downgrade to strict mode to not miss deps

.github/workflows/coverage.yml
Add auto retry for coverage analysis
The "Upload coverage to Codecov" step of the coverage analysis often
fails due to network issues with an error like:
```
Commit creating failed: {"error": "Server Error (500)"}
```
GitHub coverage action doesn't have a retry parameter, thus we use a
trick:
we add one more upload step exactly as the previous one, but we would
trigger it only in case the previous step failed.
Additionally, as retrying one upload too close to the other still gets a
failure we add a sleep step to wait for a minute before retrying.
Checklist
=> Add auto retry for coverage analysis

plans/tier1.fmf, pytest.ini, tests/integration/tier1/non-destructive/httpd-package-transaction-error/main.fmf, tests/integration/tier1/non-destructive/httpd-package-transaction-error/test_httpd_package_transaction_error.py, tests/integration/tier1/non-destructive/main.fmf
The test is added as a tier1 as it is a corner
case scenario.
The bug to verify: https://issues.redhat.com/browse/RHELC-1130
Jira Issues: [RHELC-1243](https://issues.redhat.com/browse/RHELC-1243)
Checklist
=> [RHELC-1243] Add int test to verify the httpd package error

convert2rhel/backup/files.py, convert2rhel/unit_tests/backup/files_test.py
Moving a file back to its own directory is causing the file to lose the metadata and not letting the user enter in their system with SSH after the analysis is done.
Jira Issues: [RHELC-1432](https://issues.redhat.com/browse/RHELC-1432)
Checklist
=> [RHELC-1432] Copy instead of move when restoring a file

.devcontainer/alma9/devcontainer.json, CONTRIBUTING.md
When having the version locked, it causes issues with the pylance extension. Since everything works in up-to-date state, removing the lock.
The issues with pylance are mentioned there: https://github.com/oamg/convert2rhel/pull/1128
Checklist
=> Remove python version lock in dev container

.pre-commit-config.yaml, .pylintrc, convert2rhel/actions/system_checks/rhel_compatible_kernel.py, convert2rhel/pkghandler.py, convert2rhel/unit_tests/actions/actions_test.py, convert2rhel/unit_tests/actions/report_test.py, convert2rhel/unit_tests/actions/system_checks/rhel_compatible_kernel_test.py, convert2rhel/unit_tests/subscription_test.py
Update pre-commit config to use the latest version of pylint. Previously, we pinned the version of pylint as we still had to support older python versions because of RHEL 6.
Since we don't have this requirement anymore, we can update pylint and only ignore the flags that we know that won't be available for Python 2.7.
Checklist
=> Modify pre-commit to use latest pylint version

convert2rhel/backup/packages.py
Fix typo in rollback task log as it was using "convert" instead of "rollback".
Checklist
=> Rollback task using "Convert" instead of "Rollback"

convert2rhel/logger.py, convert2rhel/unit_tests/conftest.py, convert2rhel/unit_tests/logger_test.py
Since of merging #1029 we get an issue with unit tests that causes a lot
of strange errors to occur. Likely due to a stream not being closed
correctly.
This aims to either fix or mitigate this from occuring during test runs
as it should not appear in convert2rhel by itself.
Jira Issues: [RHELC-1396](https://issues.redhat.com/browse/RHELC-1396)
Checklist
=> [RHELC-1396] fix: errors in utils.py after full test suite

convert2rhel/main.py, convert2rhel/unit_tests/main_test.py, tests/integration/tier0/non-destructive/rhsm-facts/main.fmf, tests/integration/tier0/non-destructive/rhsm-facts/test_rhsm_facts_update_analysis.py
Enable the RHSM custom facts update during analysis mode.
The update will only happen if the system was registered before, otherwise, we won't do nothing
Jira Issues: [RHELC-1164](https://issues.redhat.com/browse/RHELC-1164)
Checklist
=> [RHELC-1164] Update RHSM custom facts during analysis

convert2rhel/toolopts.py, convert2rhel/unit_tests/toolopts_test.py, pytest.ini, tests/integration/tier0/destructive/offline-system-conversion/test_offline_system_conversion.py, tests/integration/tier0/non-destructive/config-file/main.fmf, tests/integration/tier0/non-destructive/config-file/test_config_file.py, tests/integration/tier0/non-destructive/system-release-backup/test_system_release_backup.py
This removes a few deprecated CLI arguments, they will no longer work
or give a warning about its deprecation.
This includes
- Removal of `convert2rhel -f|--password-from-file`
- Removal of unused `convert2rhel --keep-rhsm`
Jira Issues: [RHELC-1425](https://issues.redhat.com/browse/RHELC-1425)
Checklist
=> [RHELC-1425] breaking change: Remove deprecated CLI arguments

.devcontainer/alma9/alma9-development.Containerfile, convert2rhel/actions/system_checks/is_loaded_kernel_latest.py, convert2rhel/unit_tests/actions/system_checks/is_loaded_kernel_latest_test.py, plans/tier1.fmf, pytest.ini, tests/integration/tier0/non-destructive/system-release-backup/test_system_release_backup.py, tests/integration/tier1/destructive/kernel-check-skip/test_latest_kernel_check_skip.py
This removes `CONVERT2RHEL_UNSUPPORTED_SKIP_KERNEL_CURRENCY_CHECK`
as it is deprecated and to be removed in the next major version as a
breaking change.
Jira Issues: [RHELC-1425](https://issues.redhat.com/browse/RHELC-1425)
Checklist
=> [RHELC-1425] breaking change: Remove deprecated latest kernel env variable

convert2rhel/actions/system_checks/convert2rhel_latest.py, convert2rhel/unit_tests/actions/system_checks/convert2rhel_latest_test.py
This removes `CONVERT2RHEL_UNSUPPORTED_VERSION`
as it is deprecated and to be removed in the next major version as a
breaking change.
Jira Issues: [RHELC-1425](https://issues.redhat.com/browse/RHELC-1425)
Checklist
=> [RHELC-1425] breaking change: Remove deprecated unsupported version env variable

convert2rhel/hostmetering.py
Added a couple of debug logs to host-metering to help identify what is happening in case of a environment variable not being set, or what option the user specified in the env var.
```
[2024-03-13T15:49:55+0000] TASK - [Final: Configure host-metering] ***********************************
Writing breadcrumbs to '/etc/migration-results'.
Writing RHSM custom facts to '/etc/rhsm/facts/convert2rhel.facts'.
```
Checklist
=> Add debug logs to host-metering

convert2rhel/main.py
Without a log task, the breadcrumbs update part has its output very near to other logs from other tasks. This commit introduces a simple task log to separate what is the task running, and the breadcrumbs being updated.
Checklist
=> Add a task log for update breadcrumbs

convert2rhel/toolopts.py, convert2rhel/unit_tests/toolopts_test.py, tests/integration/tier1/destructive/one-kernel-scenario/test_one_kernel_scenario.py
As we are going to do a major version change we want to remove all
deprecated and unused client-facing things, such as the unsupported
naming and deprecated arguments.
This change has to do with removing `--disable-submgr` as we have the
equivalent and newer `--no-rhsm` argument.
Jira Issues: [RHELC-1425](https://issues.redhat.com/browse/RHELC-1425)
Checklist
=> [RHELC-1425] Breaking change: Remove `--disable-submgr` arg

convert2rhel/actions/pre_ponr_changes/backup_system.py, convert2rhel/toolopts.py, convert2rhel/unit_tests/actions/pre_ponr_changes/backup_system_test.py, convert2rhel/unit_tests/toolopts_test.py, convert2rhel/unit_tests/utils_test.py, convert2rhel/utils.py, man/convert2rhel.8, plans/tier1.fmf, tests/integration/tier0/non-destructive/basic-sanity-checks/test_basic_sanity_checks.py, tests/integration/tier0/non-destructive/system-release-backup/main.fmf, tests/integration/tier0/non-destructive/system-release-backup/test_system_release_backup.py, tests/integration/tier1/destructive/one-kernel-scenario/test_one_kernel_scenario.py
We are moving away from using the word UNSUPPORTED in environment
variables as it is confusing and not very descriptive of what is
unsupported. Since this relates to the tool itself not supporting it in
a predictable way, we are renaming mentions of the word unsupported.
This change has to do with renaming
``CONVERT2RHEL_UNSUPPORTED_INCOMPLETE_ROLLBACK``
to
`CONVERT2RHEL_INCOMPLETE_ROLLBACK`
`CONVERT2RHEL_INCOMPLETE_ROLLBACK` means that we can garantee a rollback
will be successful on a potential failure and user would have to specify
the environment variable themselves to understand this to not blame the
tool.
This change does not do anything else and no backwards compatibility is
considered as it is intended to be changed in a major version change.
Jira Issues: …
=> [RHELC-1430] Breaking change: Rename incomplete rollback envvar

convert2rhel/actions/__init__.py, convert2rhel/main.py, convert2rhel/unit_tests/actions/actions_test.py, convert2rhel/unit_tests/main_test.py
In this commit, we are introducing two new stages for enabling the post conversion in the action framework.
We are also introducing an environment variable to not break the current workflow and let the conversion function as-is for now. Anyone that is willing to test and run the post conversion actions will need to use this environment var.
Jira Issues: [RHELC-1342](https://issues.redhat.com/browse/RHELC-1342)
Checklist
=> [RHELC-1342] Add post conversion stages for Action Framework

convert2rhel/toolopts.py, convert2rhel/unit_tests/toolopts_test.py, man/convert2rhel.8, pytest.ini, tests/integration/tier0/non-destructive/basic-sanity-checks/main.fmf, tests/integration/tier0/non-destructive/basic-sanity-checks/test_basic_sanity_checks.py
As we are going to do a major version change we want to remove all
deprecated and unused client-facing things, such as the unsupported
naming and deprecated arguments.
This change has to do with removing `--variant` as it is no longer used
and serves no purpose.
Jira Issues: [RHELC-1425
](https://issues.redhat.com/browse/RHELC-1425
)
Checklist
=> [RHELC-1425] Breaking change: Remove `-v|--variant` arg

.devcontainer/centos7/devcontainer.json
When trying to use the CentOS 7 devcontainer, the syntax highlight didn't work. Removing the version lock solved this problem. 
The same as #1129 
Checklist
=> Fix: Remove version lock on centos7 devcontainer

.packit.yaml
This reverts commit b0713d6f2d13276fbba472fda7bec322f3d7645e.
Packit is having issues with the number of jobs being posted due to the automated triggering based on the labels.
Revert the required labels changes to try to mitigate the issues.
=> Revert "chore: trigger testing by label instead of comment"

.github/pull_request_template.md, .github/workflows/release.yml
Currently we do not add the Jira links correctly as was observed for the
v1.7.0 release as one PR title contained two RHELC Jira issues in the
title. E.g. `[RHELC-1, RHELC-2] Test title`. This change should now
be more flexible and also handles more edge-cases that could occur.
We now use python to do RegEx replace rather than sed or awk as they
were too limiting. Opted for not using perl as python shell is already
present for GitHub actions.
This is how we want it to be:
https://github.com/oamg/convert2rhel/releases/tag/v1.7.0
Tested on my repo
https://github.com/SpyTec/convert2rhel/releases/tag/v24.03.04.3
What changed
```diff
-- RHELC-1 test
-- RHEL-1, RHEL-2 testtest
-- [RHELC-1, RHEL-1234] Title test stuff here
-- [RHELC-12] Test title
+- …
```
=> Improve UX for release Jira auto-linking

convert2rhel/actions/pre_ponr_changes/handle_packages.py, convert2rhel/actions/pre_ponr_changes/special_cases.py, convert2rhel/actions/pre_ponr_changes/subscription.py, tests/integration/tier0/non-destructive/problematic-third-party-pkgs/main.fmf, tests/integration/tier0/non-destructive/problematic-third-party-pkgs/test_problematic_third_party_pkgs.py, tests/integration/tier0/non-destructive/rollback-handling/test_rollback_handling.py
Some task headers for pre-conversion were using "Convert" instead of "Prepare". Since we are dealing with actions that are present before we start the conversion, all of those log tasks were changed to contain the word "Prepare" instead to not sound confusing to the user as what is happening.
Jira Issues: [RHELC-1465](https://issues.redhat.com/browse/RHELC-1465)
Checklist
=> [RHELC-1465] Set consistent task prefix for pre-conversion

.github/workflows/release.yml
This adds another trigger for the rpm builds so that we will be able to
attach rpms to specific tags. This primarily helps out with the weekly
tags we do on Fridays where we can easily link to it for the latest
RPM that should be decently stable
Note that these RPMs are still not extensively verified like we would
for an actual release. Instead they are weekly snapshots of the current
state of the repository.
Jira Issues:
-
Checklist
=> chore: build RPMs on tags

convert2rhel/subscription.py
Jira Issues: [RHELC-465](https://issues.redhat.com/browse/RHELC-465)
Checklist
=> [RHELC-465] Remove deprecated todo comment about pool ids

convert2rhel/toolopts.py, convert2rhel/unit_tests/toolopts_test.py
The title says it all. A quick kaizen-style fix.
Jira Issues: -
- [RHELC-1489](https://issues.redhat.com/browse/RHELC-1489)
Checklist
=> [RHELC-1489] Fix an error message referring to a non-existing --organization option

.packit.yaml
* bump the parallel limit to 20
* discard the tier0 destructive/non-destructive payloads split, since both can be run in parallel now
Jira Issues: [RHELC-649](https://issues.redhat.com/browse/RHELC-649)
Checklist
=> [RHELC-649] Bump parallel-limit for plan execution

pytest.ini, tests/ansible_collections/main.yml, tests/ansible_collections/roles/remove-tf-artifact-leftovers/tasks/clean_up_el7.yml, tests/ansible_collections/roles/remove-tf-artifact-leftovers/tasks/clean_up_el8.yml, tests/ansible_collections/roles/remove-tf-artifact-leftovers/tasks/main.yml, tests/integration/conftest.py, tests/integration/tier0/non-destructive/kernel/files/alma_old.repo, tests/integration/tier0/non-destructive/kernel/files/rocky_old.repo, tests/integration/tier0/non-destructive/single-yum-transaction-validation/main.fmf, tests/integration/tier0/non-destructive/single-yum-transaction-validation/test_single_yum_transaction_validation.py
After the artifact installation done by TF there are some packages left on the system.
They are considered as a third party packages so we want to remove them from the system as well
as the corresponding repositories.
Also fix single-yum-transaction-validation int tests
Jira Issues: [RHELC-1488](https://issues.redhat.com/browse/RHELC-1488)
Checklist
=> [RHELC-1488]  Remove packages left after the TF artifact installation 

convert2rhel/actions/conversion/transaction.py, convert2rhel/main.py, convert2rhel/unit_tests/actions/conversion/transaction_test.py, convert2rhel/unit_tests/main_test.py
First function to be converted to the actions is done in this commit.
This function is responsible for converting system packages to rhel
packages, thus, being the first function to be executed, it was the
first one to be migrated as well.
Jira Issues: [RHELC-1328](https://issues.redhat.com/browse/RHELC-1328)
Checklist
=> [RHELC-1328] Migrate post conversion transaction function

convert2rhel/grub.py, convert2rhel/unit_tests/grub_test.py
A customer reported an issue where the EFI check found an unexpected error related to the devices PART_ENTRY_NUMBER - https://github.com/oamg/convert2rhel/issues/1167. A PR was made to error when the PART_ENTRY_NUMBER is missing but the check was not set to expect the output from `blkid -p -s PART_ENTRY_NUMBER [device]` to be "\n". This PR adds a conditional to ensure we error when blkid returns an empty string, "\n" or " ".
Jira Issues: [RHELC-1484](https://issues.redhat.com/browse/RHELC-1484)
Closes #1167 
Checklist
=> [RHELC-1484] Update efi check for PART_ENTRY_NUMBER

convert2rhel/systeminfo.py, convert2rhel/unit_tests/systeminfo_test.py
Jira Issues: [RHELC-676](https://issues.redhat.com/browse/RHELC-676)
There are several places where the system release string is parsed via regular expressions. These regexps are different and adjusting them requires refactoring in multiple places.
This change introduces one parsing function which does a full match of the system-release string and reads all possible data points from it, and provides the result as a dictionary for later use by other tools.
The function replaces three other helper methods: _get_system_name, _get_system_version and _get_system_distribution_id, which are removed.
NOTE1: The parsing function could be a static method or even implemented as a utility function outside the class. The only reason why it is in the class is the logger object.
NOTE2: the function …
=> [RHELC-676] Unify parsing of the system release string

.devcontainer/centos7/devcontainer.json
After releasing the VS Code 1.88 and the new versions of the extensions, there are problems with CentOS 7 devcontainer.
Without the lock there are problems with dependencies resulting in not working linting, syntax highlight or unit testing module. With the lock, the mentioned things works.
There is still problem with not working visual debugging of the unit tests, it seems there is some infinite loop.  But other things works.
For the feature, the working versions for the CentOS 7 devcontainer today:
VS Code: 1.87.2
Dev Container extension for VS Code:  0.348.0 (in the newer version 0.354.0, it waits for choosing the right image)
Checklist
=> Add version lock of python extensions in CentOS 7 Devcontainer

convert2rhel/actions/system_checks/convert2rhel_latest.py, convert2rhel/backup/certs.py, convert2rhel/backup/packages.py, convert2rhel/breadcrumbs.py, convert2rhel/unit_tests/backup/certs_test.py, convert2rhel/utils/__init__.py, convert2rhel/utils/files.py
As we kept using `utils.py` file and adding more and more things it
became quite bloated. To solve this the best thing to do, while also
making it easy to test and reduce cyclic imports is to split it into
smaller parts.
This takes care of the initial move by putting everything on the module
level while still having backwards compatibility for the time being.
To make this easier for ourselves we should migrate the file into
more modules over time
Checklist
=> refactor: move `utils.py` to a module

convert2rhel/breadcrumbs.py, tests/integration/tier0/non-destructive/basic-sanity-checks/test_basic_sanity_checks.py, tests/integration/tier0/non-destructive/single-yum-transaction-validation/test_single_yum_transaction_validation.py
The message said convert2rhel.fact while it should be convert2rhel.facts.
Jira Issues:
- [RHELC-1503](https://issues.redhat.com/browse/RHELC-1503)
Checklist
=> [RHELC-1503] Fix RHSM facts filepath in a log message

convert2rhel/actions/pre_ponr_changes/subscription.py, convert2rhel/subscription.py, convert2rhel/unit_tests/__init__.py, convert2rhel/unit_tests/actions/pre_ponr_changes/subscription_test.py, convert2rhel/unit_tests/subscription_test.py, pytest.ini, tests/integration/conftest.py, tests/integration/tier0/non-destructive/subscription-manager/main.fmf, tests/integration/tier0/non-destructive/subscription-manager/test_sub_man_pre_register.py
This PR adds a check to see if SCA is not enabled and if there is no subscription attached. In the event these conditions are met we attempt to auto attach a subscription for the customer. If the auto attachment fails we have an ERROR result `NO_ACCESS_TO_RHEL_REPOS`  to let the user know that the system is registered with an RHSM account that has SCA disabled but no subscription is attached and the auto attachment was unsuccessful. New functions is_subscription_attached() and auto_attach_subscription() have been made to facilitate these checks. Also made a new function _is_sca_enabled so we can detect if sca is enabled in both subscription.py and pre_ponr_changes/subscription.py. 
Jira Issues: 
* [RHELC-1228](https://issues.redhat.com/browse/RHELC-1228)
* …
=> [RHELC-1228, RHELC-1231] Improve detection of RHSM credentials in subscription check

convert2rhel/actions/report.py, convert2rhel/main.py, convert2rhel/unit_tests/actions/report_test.py, convert2rhel/unit_tests/main_test.py
The report had to be updated to include the post conversion results from
the actions, since we are extending the framework and migrating the
functions to become actions, we need to make a few modifications to
adapt the reporting to work with both pre and post conversion actions.
Jira Issues: [RHELC-1347](https://issues.redhat.com/browse/RHELC-1347)
Checklist
=> [RHELC-1347] Update report to include post conversion actions

convert2rhel/actions/system_checks/convert2rhel_latest.py, convert2rhel/pkghandler.py
The bug underlying [RHELC-1225](https://issues.redhat.com/browse/RHELC-1225) was an incorrect use of the python  lstrip  function. This change fixes all the other places in the code where we make the same mistake.
Checklist
=> Fix incorrect usages of rstrip with a string argument.

Makefile
After the merge of https://github.com/oamg/convert2rhel/pull/1189, the spam of information of test setups is causing problems in github actions log rendering, as well as executing it locally/container.
This commit is intended to override the addopts option in pytest.ini when the
execution is inside a container/locally.
Jira Issues:
-
Checklist
=> Override pytest addopts for local development

convert2rhel/actions/pre_ponr_changes/backup_system.py, convert2rhel/actions/system_checks/duplicate_packages.py, convert2rhel/backup/packages.py, convert2rhel/unit_tests/actions/pre_ponr_changes/backup_system_test.py, convert2rhel/unit_tests/actions/system_checks/duplicate_packages_test.py, convert2rhel/unit_tests/backup/packages_test.py
This PR changes our backups to now backup the redhat.repo file when running with satellite. The reason backups were failing on satellite was due to the redhat.repo file being excluded from backups which in turn causes the .repo files not to be backed up. This change also removes the requirement for internet access to backup using hardcoded repository files and defaults to always using the the hardcoded repository files. 
A similiar failure with backing up repo files has been reported for offline conversions with satellite - [RHELC-1040](https://issues.redhat.com/browse/RHELC-1040), however this PR does not fix the issue
Jira Issues:
- [RHELC-1385](https://issues.redhat.com/browse/RHELC-1385)
Checklist
=> [RHELC-1385] Satellite package backup failure fix

convert2rhel/unit_tests/backup/packages_test.py
There was an incorrect assigment in the test mock that caused one of the unit_tests to take a lot of time to finish.
Jira Issues:
-
Checklist
=> Fix incorrect test mock in unit tests

convert2rhel/actions/system_checks/dbus.py, convert2rhel/unit_tests/actions/system_checks/dbus_test.py
When converting through Insights, this message is always shown to the user. It provides little to no value to the user and is purely distractracting.
Having a message about that the check being skiped in the terminal and log is sufficient.
Jira Issues:
- [RHELC-1519](https://issues.redhat.com/browse/RHELC-1519)
Checklist
=> [RHELC-1519] Don't report on skipping dbus check

convert2rhel/main.py, convert2rhel/unit_tests/main_test.py, tests/integration/tier0/non-destructive/firewalld-inhibitor/test_firewalld_inhibitor.py
If an inhibitor is found during the analysis and we are running it in conversion mode, we want to exit with code 2 to differentiate from the others errors mode.
Jira Issues: [RHELC-1276](https://issues.redhat.com/browse/RHELC-1276)
Checklist
=> [RHELC-1276] Modify exit code for conversion when inhibitor is found

convert2rhel/systeminfo.py, convert2rhel/unit_tests/conftest.py
This PR adds rhel 9 versions up to 9.10 in systeminfo so customers can do conversions on all rhel 9 versions. 
Jira Issues:[RHELC-1493 ](https://issues.redhat.com/browse/RHELC-1493)
Checklist
=> [RHELC-1493] Add rhel 9 version support up to 9.10

convert2rhel/backup/packages.py
The condition to check for the existence of the reposdir folder was set in an incorrect place. This caused the program to raise an exception as we are trying to list the contents of the directory before checking for the path availability of the folder.
Jira Issues:
- [RHELC-1521](https://issues.redhat.com/browse/RHELC-1521)
Checklist
=> [RHELC-1521] Fix check for reposdir in RestorablePackage class

convert2rhel/data/7/x86_64/configs/centos-7-x86_64.cfg
The package needs to be excluded because it's not available in RHEL repos and has dependency requirements (requires libreport-web and libreport of specific NEVRA) which cannot be satisfied.
When it's not in this list it is removed from the system without notifying the user in the safety net of the yum transaction. This is better handling of known problematic package.
Jira Issues:
- [RHELC-1526](https://issues.redhat.com/browse/RHELC-1526)
Checklist
=> [RHELC-1526] Add the libreport-plugin-mantisbt to excluded list

convert2rhel/toolopts.py, convert2rhel/unit_tests/toolopts_test.py
If a user provided username and password CLI arguments and had set
activation key and organization in the config file, it would fail to
execute convert2rhel. Same also happens if organization is set and
activation key isn't.
This is addressed by also unsetting organization if we detect username
and password.
Jira Issues:
- [RHELC-1525](https://issues.redhat.com/browse/RHELC-1525)
Checklist
=> [RHELC-1525] Fix cornercase with userpass and keyorg

convert2rhel/backup/__init__.py, convert2rhel/backup/certs.py, convert2rhel/backup/files.py, convert2rhel/main.py, convert2rhel/subscription.py, convert2rhel/unit_tests/__init__.py, convert2rhel/unit_tests/backup/backup_test.py, convert2rhel/unit_tests/backup/certs_test.py, convert2rhel/unit_tests/backup/files_test.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/subscription_test.py
There is a need to exit with exit code 1 when rollback fails to provide the ability to better recognize those types of failures for Insights. This situation can mainly happen when user uses analyze command or during the conversion answers "No" and user doesn't want to continue over point of no return. In those situations, rollback is processed and when it fails, the system is in an unknown state.
**Expected behavior:**
When rollback fails, c2r exits with 1, warning about unknown state and system should be restored from backup is printed. Any summaries of the report aren't printed or saved - because there is any big value of the report when the rollback failed.
**How it was solved:**
The new property `backup_failed` of BackupController was added. This property is based on instance variable …
=> [RHELC-1275, RHELC-1516] Exit with 1 when rollback fails

convert2rhel/exceptions.py, convert2rhel/pkgmanager/handlers/dnf/__init__.py, convert2rhel/pkgmanager/handlers/yum/__init__.py, convert2rhel/unit_tests/pkgmanager/handlers/dnf/dnf_test.py, convert2rhel/unit_tests/pkgmanager/handlers/yum/yum_test.py
This PR resolves an issue where the error result from the YumBaseError exception would not be displayed in the diagnosis of the Error - FAILED_TO_VALIDATE_TRANSACTION for yum transcations. The issue was that the type of the error was of YumBaseError so when a .join was used on it the output would be blank. This PR extracts the actual value from the YumBaseError class and properly displays it with the Error result. There are also updates to the unit tests for both yum and dnf transcation failures so we assert the proper content is in the Error result
Jira Issues:
- [RHELC-1528](https://issues.redhat.com/browse/RHELC-1528)
Checklist
=> [RHELC-1528] Fix empty error message in Yum transaction failure

plans/main.fmf, plans/tier0.fmf, pytest.ini, tests/ansible_collections/roles/get-test-vars/tasks/get-test-vars.yml, tests/ansible_collections/roles/remove-tf-artifact-leftovers/tasks/clean_up_el7.yml, tests/integration/conftest.py, tests/integration/tier0/destructive/conversion-method/main.fmf, tests/integration/tier0/destructive/conversion-method/test_satellite.py, tests/integration/tier0/destructive/offline-system-conversion/prepare_system.py, tests/integration/tier0/destructive/single-yum-transaction/test_check_for_latest_packages.py, tests/integration/tier0/non-destructive/eus/test_eus_support.py, tests/integration/tier0/non-destructive/file-backup/test_file_backup.py, tests/integration/tier0/non-destructive/kernel/test_kernel_check_verification.py, tests/integration/tier0/non-destructive/kernel/test_oracle_unsupported_uek.py, tests/integration/tier0/non-destructive/main.fmf, tests/integration/tier0/non-destructive/modified-releasever/test_modified_releasever.py, tests/integration/tier0/non-destructive/rhsm-facts/main.fmf, tests/integration/tier0/non-destructive/rollback-handling/test_rollback_handling.py, tests/integration/tier0/non-destructive/single-yum-transaction-validation/test_single_yum_transaction_validation.py, tests/integration/tier0/non-destructive/subscription-manager/main.fmf, tests/integration/tier0/non-destructive/subscription-manager/test_sub_man_pre_register.py, tests/integration/tier0/non-destructive/system-release-backup/main.fmf, tests/integration/tier0/non-destructive/system-release-backup/test_system_release_backup.py, tests/integration/tier1/destructive/firewalld-disabled-ol8/test_firewalld_disabled_ol8.py, tests/integration/tier1/destructive/kernel-check-skip/test_latest_kernel_check_skip.py, tests/integration/tier1/destructive/proxy-conversion/test_proxy_conversion.py, tests/integration/tier1/non-destructive/main.fmf
* do not use the katello-ca-consumer package for registration to the Satellite since it will be deprecated in the near future
* use the API call to register instead
Jira Issues:
- [RHELC-1314](https://issues.redhat.com/browse/RHELC-1314)
- [RHELC-1524](https://issues.redhat.com/browse/RHELC-1524)
- [RHELC-1387](https://issues.redhat.com/browse/RHELC-1524)
Checklist
=> [RHELC-1314, RHELC-1524, RHELC-1387] Drop the use of the katello package from the tests

convert2rhel/main.py, convert2rhel/unit_tests/main_test.py
The report was being printed to the user twice after the analysis was done. This commit patches this by removing the second call to the report as it is not necessary.
Jira Issues:
- [RHELC-1551](https://issues.redhat.com/browse/RHELC-1551)
Checklist
=> [RHELC-1551 Fix report duplication after analysis

convert2rhel/pkgmanager/handlers/yum/__init__.py, convert2rhel/unit_tests/pkgmanager/handlers/yum/yum_test.py
We were passing a set object to iterate over to compose a message of packages that got removed during yum transaction. This problem was not happening before as we were dealing with a success case of restoring packages. In this regression, we found out that a set object does not have indexing, therefore, thus bug was hidden from most of our tests and pipeline.
Jira Issues:
- [RHELC-1547](https://issues.redhat.com/browse/RHELC-1547)
Checklist
=> [RHELC-1547] Fix regression in installing removed packages during rollback

convert2rhel/main.py, convert2rhel/unit_tests/main_test.py
When InhibitorFound exception is raised, check if rollback was successful is needed. This will affect the result return code: 
- 1 - rollback fail
- 2 - inhibitor
Jira Issues:
-
Checklist
=> Check if rollback failed when handling InhibitorFound exception

convert2rhel/actions/pre_ponr_changes/handle_packages.py, convert2rhel/actions/system_checks/is_loaded_kernel_latest.py, convert2rhel/backup/packages.py, convert2rhel/pkghandler.py, convert2rhel/repo.py, convert2rhel/unit_tests/actions/system_checks/is_loaded_kernel_latest_test.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/repo_test.py
We need to disable RHEL repos. If user registers the system to satellite which provides Centos and RHEL repos and the RHEL repos would be enabled, it would cause a fail. The recommended way is to disable the rhel repos prior the conversion, but is expected it might be forgotten. This helps avoiding the problems caused by wrong setup of the repos.
Jira Issues: https://issues.redhat.com/browse/RHELC-884
-
Checklist
=> [RHELC-884] Disable RHEL repos when performing checks

convert2rhel/actions/pre_ponr_changes/backup_system.py, convert2rhel/pkghandler.py, convert2rhel/unit_tests/actions/pre_ponr_changes/backup_system_test.py, tests/integration/tier1/destructive/system-not-up-to-date/test_system_not_up_to_date.py
Versionlock file has been backed up and cleared before we run the backup action via a prepare_system() call in main.py, thus we should exclude it, so that we do not overwrite it with empty data.
Jira Issues:
- [RHELC-1291](https://issues.redhat.com/browse/RHELC-1291)
- [RHELC-1292](https://issues.redhat.com/browse/RHELC-1292)
Checklist
=> [RHELC-1291, RHELC-1292] Skip versionlock file in backup system actions

convert2rhel/actions/system_checks/duplicate_packages.py, convert2rhel/unit_tests/actions/system_checks/duplicate_packages_test.py
This PR adds handlers for errors raised when running the DUPLICATE_PACKAGES check with Satellite on an offline system. On EL7 systems for this particular error case the return code is 0 and the output is [Errno -2] Name or service not known. while on EL8 the return code is 1 and the output is Failed to download metadata for repo [example repo]: Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried.
For EL7 we check for that specific output and for EL8 we check the return code. Both cases raise a WARNING DUPLICATE_PACKAGE_CHECK_FAILED and inform the user we couldn't perform the check and recommend they ensure they can access all repos enabled on their system and re-run convert2rhel or check for duplicate packages themselves. This way we don't hinder the …
=> [RHELC-1540] Fix bug with duplicate packages check when running with Satellite offline

convert2rhel/backup/packages.py, convert2rhel/unit_tests/backup/packages_test.py
Raise exception when RestorablePackage cannot access the backup folder or the installation of the backed up packages fails.
Jira Issues:
- [RHELC-1556](https://issues.redhat.com/browse/RHELC-1556)
Checklist
=> [RHELC-1556] Raise when RestorablePackage fails to restore

convert2rhel/actions/pre_ponr_changes/subscription.py, convert2rhel/backup/packages.py, convert2rhel/pkgmanager/__init__.py, convert2rhel/repo.py, convert2rhel/subscription.py, convert2rhel/unit_tests/backup/packages_test.py, convert2rhel/unit_tests/pkgmanager/pkgmanager_test.py, convert2rhel/unit_tests/repo_test.py, convert2rhel/unit_tests/subscription_test.py
In this commit, we are introducing the installation of subscription-manager directly through a package manager, instead of downloading the package first and then installing it with system package manager.
This is necessary as we want to do GPG verification when installing those set of packages, in which case, it was not available when we used to download the packages and then install it via local install.
Notable changes in this commit are:
* Replacing installing subscription-manager to install it directly from the client-tools repository with gpg check enabled for all supported versions
* Minor refactor to RestorablePackageSet class to allow it to be generic and use custom repository paths and content to install packages
* Small tweak to call_yum_cmd to use the reposdir option as a list …
=> [RHELC-601] Install subscription-manager using package manager

plans/tier1.fmf, pytest.ini, tests/integration/conftest.py, tests/integration/tier0/non-destructive/assessment-report/test_assessment_report.py, tests/integration/tier0/non-destructive/basic-sanity-checks/test_basic_sanity_checks.py, tests/integration/tier0/non-destructive/config-file/test_config_file.py, tests/integration/tier0/non-destructive/custom-repository/test_custom_repository.py, tests/integration/tier0/non-destructive/cve-2022-1662/test_cve-2022-1662.py, tests/integration/tier0/non-destructive/file-backup/test_file_backup.py, tests/integration/tier0/non-destructive/kernel-modules/test_unsupported_kmod.py, tests/integration/tier0/non-destructive/kernel/test_custom_kernel.py, tests/integration/tier0/non-destructive/kernel/test_kernel_check_verification.py, tests/integration/tier0/non-destructive/kernel/test_oracle_unsupported_uek.py, tests/integration/tier0/non-destructive/logged-command/test_logged_command.py, tests/integration/tier0/non-destructive/modified-releasever/test_modified_releasever.py, tests/integration/tier0/non-destructive/rollback-handling/main.fmf, tests/integration/tier0/non-destructive/rollback-handling/test_rollback_handling.py, tests/integration/tier0/non-destructive/single-yum-transaction-validation/test_single_yum_transaction_validation.py, tests/integration/tier0/non-destructive/subscription-manager/test_sub_man_pre_register.py, tests/integration/tier0/non-destructive/subscription-manager/test_sub_man_rollback.py, tests/integration/tier0/non-destructive/system-release-backup/test_system_release_backup.py, tests/integration/tier0/non-destructive/user-prompt-response/test_user_prompt_response.py, tests/integration/tier1/destructive/excluded-packages-removed/test_excluded_pkgs_removed.py, tests/integration/tier1/destructive/system-not-up-to-date/test_system_not_up_to_date.py
This PR fixes exit code asserts in the integration tests. Also adds one new integration test case with broken rollback scenario. 
Jira Issues:
-  [RHELC-1303](https://issues.redhat.com/browse/RHELC-1303) 
-  [RHELC-1301](https://issues.redhat.com/browse/RHELC-1301)
-  [RHELC-1527](https://issues.redhat.com/browse/RHELC-1527)
-  [RHELC-1557](https://issues.redhat.com/browse/RHELC-1557)
Checklist
=> [RHELC-1303, RHELC-1527, RHELC-1557] Enhance exit code testing

convert2rhel/actions/system_checks/convert2rhel_latest.py, convert2rhel/unit_tests/actions/system_checks/convert2rhel_latest_test.py, tests/integration/tier0/non-destructive/basic-sanity-checks/test_basic_sanity_checks.py
When a newer convert2rhel version was detected, the check result was set to ERROR however we allow overriding the check by setting the CONVERT2RHEL_ALLOW_OLDER_VERSION=1 enironment variable meaning that the result is supposed to be OVERRIDABLE.
Jira Issues:
- [RHELC-1561](https://issues.redhat.com/browse/RHELC-RHELC-1561)
Checklist
=> [RHELC-1561] Change result of the c2r version check to OVERRIDABLE

convert2rhel/actions/system_checks/is_loaded_kernel_latest.py, convert2rhel/pkghandler.py, convert2rhel/repo.py, convert2rhel/unit_tests/actions/system_checks/is_loaded_kernel_latest_test.py, convert2rhel/unit_tests/repo_test.py
The current `get_rhel_disable_repos_command` is returning a list of disablerepo commands to be passed down to run_subprocess functions. This is insecure as it contains white spaces inbetween the commands. This patch changes this to return them in a list instead.
Jira Issues:
-
Checklist
=> Return a list instead of string for disablerepo command

.gitignore, convert2rhel/actions/__init__.py, docs/Makefile, docs/source/_templates/custom-class-template.rst, docs/source/_templates/custom-module-template.rst, docs/source/actions.rst, docs/source/all.rst, docs/source/conf.py, docs/source/index.rst, docs/source/meta.rst, docs/source/pkgmanager.rst
This patch adds autodocs skeleton without adding any automation to generate the docs.
Checklist
- [N/A] PR has been tested manually in a VM (either author or reviewer)
- [N/A] Jira issue has been made public if possible
- [N/A] `[RHELC-]` is part of the PR title
=> Add autodocs boilerplate

convert2rhel/actions/pre_ponr_changes/subscription.py, convert2rhel/backup/subscription.py, convert2rhel/subscription.py, convert2rhel/unit_tests/actions/pre_ponr_changes/subscription_test.py, convert2rhel/unit_tests/backup/subscription_test.py, convert2rhel/unit_tests/subscription_test.py, pytest.ini, tests/integration/conftest.py, tests/integration/tier0/destructive/conversion-method/test_satellite.py, tests/integration/tier0/non-destructive/basic-sanity-checks/test_basic_sanity_checks.py, tests/integration/tier0/non-destructive/enabled-repositories-after-analysis/main.fmf, tests/integration/tier0/non-destructive/enabled-repositories-after-analysis/test_enabled_repositories_after_analysis.py
In a satellite analysis/conversion, we are disabling all repositories to not interfere with the rest of the execution.
With this commit, we are introducing a way of checking what repositories are enabled prior to disable them, and back the repositories names up. In the rollback phase, we enable the repositories back on the system to leave everything the way it was.
Jira Issues:
- [RHELC-1494](https://issues.redhat.com/browse/RHELC-1494)
- [RHELC-1289](https://issues.redhat.com/browse/RHELC-1289)
Checklist
-----
=> [RHELC-1494, RHELC-1289] Restore disabled repos during conversion in rollback

.devcontainer/alma9/requirements.txt, .devcontainer/centos7/requirements.txt, requirements/centos7.requirements.txt, requirements/centos8.requirements.txt, requirements/centos9.requirements.txt
The following dependencies were missing from the requirements file
- sphinx
- sphinx_autodoc_typehints
Jira Issues:
-
Checklist
=> Add missing dependencies to requirements file

plans/tier0.fmf, pytest.ini, tests/integration/conftest.py, tests/integration/tier0/destructive/conversion-method/main.fmf, tests/integration/tier0/destructive/conversion-method/test_one_key_satellite.py
* add a full conversion test validating, that systems pre-registered to the satellite with one activation key containing both original OS and RHEL repos work
Jira Issues:
- [RHELC-1289](https://issues.redhat.com/browse/RHELC-1289)
- 
Checklist
=> [RHELC-1289] Add a one key conversion method

convert2rhel/__init__.py, packaging/convert2rhel.spec
* [RHELC-1425] Remove deprecated CLI arguments by @Venefilyn in https://github.com/oamg/convert2rhel/pull/1058
* [RHELC-1425] Remove deprecated latest kernel check env variable by @Venefilyn in https://github.com/oamg/convert2rhel/pull/1056
* [RHELC-1425] Remove deprecated unsupported convert2rhel version env variable by @Venefilyn in https://github.com/oamg/convert2rhel/pull/1057
* [RHELC-1425, RHELC-1429] Remove `--disable-submgr` arg by @Venefilyn in https://github.com/oamg/convert2rhel/pull/1148
* [RHELC-1430, RHELC-1500] Rename incomplete rollback envvar by @Venefilyn in https://github.com/oamg/convert2rhel/pull/1147
* [RHELC-1425, RHELC-1429] Remove `-v|--variant` arg by @Venefilyn in https://github.com/oamg/convert2rhel/pull/1149
* [RHELC-1382] Port RestorablePackage and …
=> Bump version to 2.0.0

.packit.yaml
* the new gpg key is messing with convert2rhel installation
* import the key as a part of the tf_post_install_script
Jira Issues:
- [RHELC-1587](https://issues.redhat.com/browse/RHELC-1587) 
Checklist
=> [RHELC-1587] Fix failing artifact installation on Alma 8.8

.github/pull_request_template.md, .github/workflows/release.yml
This expands the RegEx for capturing and linking Jira issues to also
include HMS instead of just RHEL and RHELC
Jira Issues:
-
Checklist
=> chore: add HMS to release notes workflow

convert2rhel/actions/pre_ponr_changes/subscription.py, convert2rhel/actions/system_checks/convert2rhel_latest.py, convert2rhel/repo.py, convert2rhel/unit_tests/actions/system_checks/convert2rhel_latest_test.py, convert2rhel/unit_tests/repo_test.py, tests/integration/conftest.py, tests/integration/tier0/non-destructive/subscription-manager/test_sub_man_rollback.py
The convert2rhel repos moved from https://cdn.redhat.com/ to https://cdn-public.redhat.com/.
The convert2rhel repofiles moved from https://ftp.redhat.com/ to https://cdn-public.redhat.com/.
The https://cdn-public.redhat.com/ does not use a self-signed SSL cert as the https://cdn.redhat.com/ does. So we can drop handling the `redhat-uep.pem` certificate.
Jira Issues: [RHELC-1434](https://issues.redhat.com/browse/RHELC-1434)
Checklist
----
=> [RHELC-1434] Use public CDN instead of paywalled CDN and FTP

.devcontainer/alma9/alma9-development.Containerfile, .devcontainer/alma9/devcontainer.json, .devcontainer/alma9/requirements.txt, .devcontainer/centos7/requirements.txt, .github/workflows/main-docs-deploy.yml, .github/workflows/pr-docs-check.yml, docs/requirements.txt
This builds and checks the documentation builds and for commits on main branch it will deploy to GitHub Pages
Confirmed to work on my repo
https://venefilyn.github.io/convert2rhel
Jira Issues:
-
Checklist
=> chore: build docs on PR and push to main

convert2rhel/backup/subscription.py, convert2rhel/unit_tests/backup/subscription_test.py
The following comments are applied in this patch:
- https://github.com/oamg/convert2rhel/pull/1212#discussion_r1609603336
- https://github.com/oamg/convert2rhel/pull/1212#discussion_r1609610252
- https://github.com/oamg/convert2rhel/pull/1212#discussion_r1609612690
Jira Issues:
-
Checklist
=> Apply missing coments from PR#1212

.packit.yaml, plans/main.fmf, plans/stream.fmf, plans/tier0.fmf, plans/tier1.fmf, tests/ansible_collections/main.yml, tests/ansible_collections/roles/add-custom-repos/main.yml, tests/integration/common/checks-after-conversion/test_release_version.py, tests/integration/conftest.py, tests/integration/tier0/destructive/conversion-method/test_custom_repos.py, tests/integration/tier0/destructive/single-yum-transaction/install_dependency_packages.py, tests/integration/tier0/destructive/single-yum-transaction/test_single_yum_transaction.py, tests/integration/tier0/non-destructive/duplicate-pkgs/main.fmf, tests/integration/tier0/non-destructive/kernel/test_custom_kernel.py, tests/integration/tier0/non-destructive/rollback-handling/test_rollback_handling.py, tests/integration/tier0/non-destructive/single-yum-transaction-validation/main.fmf, tests/integration/tier0/non-destructive/single-yum-transaction-validation/test_single_yum_transaction_validation.py, tests/integration/tier0/non-destructive/system-release-backup/main.fmf, tests/integration/tier1/destructive/kernel-boot-files/test_handle_corrupted_files.py, tests/integration/tier1/destructive/kernel-boot-files/test_handle_missing_boot_files.py, tests/integration/tier1/destructive/kernel-check-skip/install_older_kernel.py, tests/integration/tier1/destructive/multiple-nic/multiple_nic.py
* create a new (for now) plan stream.fmf for CentOS Stream 8
* include CentOS Stream in the pipeline
* add 8.10 related adjustments to tests
* change Alma and Rocky Linux image versions to the 8.10 
Jira Issues:
- [RHELC-1428](https://issues.redhat.com/browse/RHELC-1428)
- [RHELC-1366](https://issues.redhat.com/browse/RHELC-1366)
- [RHELC-1594](https://issues.redhat.com/browse/RHELC-1594)
Checklist
=> [RHELC-1428, RHELC-1366, RHELC-1594] Include 8.10 in tests, introduce CentOS Stream

convert2rhel/toolopts.py, convert2rhel/unit_tests/main_test.py, tests/integration/tier0/non-destructive/rollback-handling/main.fmf, tests/integration/tier0/non-destructive/rollback-handling/test_rollback_handling.py
In the past, we introduced this environment variable to enable analysis when it was in tech preview. Since we are not in that stage anymore, the variable was left behind in the code after we started to remove all tech preview code.
Jira Issues:
-
Checklist
=> Remove leftover analysis environment variable

.devcontainer/alma9/requirements.txt, .github/workflows/main-docs-deploy.yml, .github/workflows/pr-docs-check.yml, docs/Makefile, docs/requirements.txt
=> chore: fix versioning of Sphinx in GH Actions

convert2rhel/main.py
Fix comments describing situations when convert2rhel can exit with different exit code than 0.
Jira Issues:
-
Checklist
=> Fix exit codes comments

.github/workflows/main-docs-deploy.yml, Containerfiles/centos9.Containerfile, docs/source/conf.py
This changes the Sphinx GitHub action to use a composite action that does not install Sphinx on its own, but rather takes care of comments so that we can more easily run everything as we want
We also add packages using apt instead of pip, as we otherwise ran into some weird issues. But I've tested on my branch and works fine
See
https://venefilyn.github.io/convert2rhel
Jira Issues:
-
Checklist
=> chore: improve sphinx workflow with composite action

.devcontainer/centos7/centos7-development.Containerfile, Containerfiles/centos7.Containerfile, Containerfiles/rpmbuild.centos7.Containerfile
With CentOS Linux 7 now being unsupported the packages were moved to the
vault as it is no longer recommended to use
Jira Issues:
-
Checklist
=> chore: update CentOS Linux 7 mirror to vault

plans/main.fmf, plans/stream.fmf, plans/tier0.fmf, tests/ansible_collections/main.yml, tests/integration/tier0/destructive/isolated-system-conversion/prepare_system.py, tests/integration/tier0/destructive/yum-distro-sync/add-extras-repo/centos7_extras.yml, tests/integration/tier0/destructive/yum-distro-sync/add-extras-repo/centos8_extras.yml, tests/integration/tier0/destructive/yum-distro-sync/add-extras-repo/main.yml
* condition the update-system and the subsequent reboot roles not to be used for the isolated system conversion
* system will be updated during the test preparation phase when it's registered to consume the satellite content
* move the reboot role to the main yaml out of the fmf
Jira Issues:
- [RHELC-1630](https://issues.redhat.com/browse/RHELC-1630)
Checklist
=> [RHELC-1630] Improve reliability of the Isolated system conversion test

convert2rhel/repo.py, convert2rhel/unit_tests/actions/system_checks/is_loaded_kernel_latest_test.py, convert2rhel/unit_tests/repo_test.py
We have a special function that returns a list of repositories that needs to be disabled during various command calls, and that list is returning always the user enablerepos command line switch in it. This patch only add the enablerepos option to the list when the --no-rhsm switch is also applied.
Jira Issues:
- [RHELC-1626](https://issues.redhat.com/browse/RHELC-1626)
Checklist
=> [RHELC-1626] Use no_rhsm to detect if enablerepos should be disabled

convert2rhel/utils/__init__.py
This PR updates the bufsize value for our run_subprocess function from 1 to -1 to avoid the RuntimeWarning introduced in python 3.8. The bufsize value of -1 is the new default value because it is compatible with most code according to the python docs - https://docs.python.org/3/library/subprocess.html .
Jira Issues:
- [RHELC-1600](https://issues.redhat.com/browse/RHELC-1600)
Checklist
=> [RHELC-1600] Update the bufsize value of run_subprocess

Makefile
A while back it was introduced to cleanup the containers due to caching
issue. This also cleans up your own containers and should not be ran
locally whatsoever as it forcefully removes all containers.
This is just a removal for now. It is better to have to run the command
twice than have to deal with the aftermath of all your own containers
suddenly being gone.
Introduced in #295
Jira Issues:
-
Checklist
=> chore: Remove forceful cleanup of all containers

.github/CODEOWNERS
This adds CODEOWNERS so that we can have specific tags for who is the
primary owner of that section of the codebase
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
Jira Issues:
-
Checklist
=> chore: Added CODEOWNERS to the repo for approvals

CONTRIBUTING.md
This adds the type comments section from the type hints PEP as a
recommendation within the CONTRIBUTING.md. In particular this will help
us with IDE and editor suggestions and warnings
https://peps.python.org/pep-0484/#type-comments
Jira Issues:
-
Checklist
=> chore: include type comments recommendation

Containerfiles/centos9.Containerfile, requirements/centos7.requirements.txt, requirements/centos8.requirements.txt, requirements/centos9.requirements.txt
Removed the sphinx* dependencies from the development requirements, and updated the centos9.Containerfile to use the requirements that comes from docs/requirements.txt instead.
Jira Issues:
-
Checklist
=> Use correct docs dependencies in centos9 container

convert2rhel/actions/post_conversion/modified_rpm_files_diff.py, convert2rhel/main.py, convert2rhel/systeminfo.py, convert2rhel/unit_tests/actions/post_conversion/modified_rpm_files_diff_test.py, convert2rhel/unit_tests/conftest.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/systeminfo_test.py
This new action provides information about difference between 'rpm -Va' from before and after the conversion.
Durign this port was needed to change the logging in the SystemInfo class to use global provided logging instead of the one inside of the class. Which was overall the same, just created dependency for logging to be inside of the class, or in the systeminfo.py would be duplicity for logging.
Jira Issues:
-[RHELC-1334](https://issues.redhat.com/browse/RHELC-1334)
Checklist
=> [RHELC-1334] Port ModifiedRPMFilesDiff to Action framework

packaging/convert2rhel.spec
The package manager on RHEL 8+ is dnf but for a backwards compatibility reason a yum rpm is available to create symlinks pointing to dnf.
If the yum package is missing, convert2rhel fails because it calls yum.
Having yum as a dependency of convert2rhel on RHEL 8+ based systems will ensure that yum will be available (unless someone intentionally removes yum after the convert2rhel installation but then ¯\_(ツ)_/¯).
Jira Issues:
- [RHELC-1622](https://issues.redhat.com/browse/RHELC-1622)
Checklist
=> [RHELC-1622] Require yum on RHEL 8+ based systems

convert2rhel/actions/conversion/preserve_only_rhel_kernel.py, convert2rhel/main.py, convert2rhel/pkghandler.py, convert2rhel/unit_tests/actions/conversion/preserve_only_rhel_kernel_test.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/pkghandler_test.py
This PR ports the function preserve_only_rhel_kernel to the action framework. Changing any relevant logger crictical, warning and info messages to Error results and Warning and Info messages respectively. 
Jira Issues:
- [RHELC-1329](https://issues.redhat.com/browse/RHELC-1329)
Checklist
=> [RHELC-1329] Port pkghandler.preserve_only_rhel_kernel() to Action framework

man/convert2rhel.8, man/synopsis
Running convert2rhel analyze gives warning to use --els option but --els option is not found on the man page.
Jira Issues:
Fixes #1334
-
Checklist
=> Add --els to convert2rhel man page and synopsis.

convert2rhel/actions/pre_ponr_changes/handle_packages.py
Move call of the function to be in the right place. This caused issues when the action return before reaching the super(run()) call.
Jira Issues:
- https://issues.redhat.com/browse/RHELC-1679
Checklist
=> [RHELC-1679] Fix of super(run()) call inside action

convert2rhel/actions/conversion/list_non_red_hat_pkgs_left.py, convert2rhel/main.py, convert2rhel/pkghandler.py, convert2rhel/unit_tests/actions/conversion/list_non_red_hat_pkgs_left_test.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/pkghandler_test.py
Port list_non_red_hat_pkgs_left to the Action framework
Jira Issues:
- [RHELC-1330](https://issues.redhat.com/browse/RHELC-1330)
Checklist
=> [RHELC-1330] Port list_non_red_hat_pkgs_left to Action framework

convert2rhel/actions/pre_ponr_changes/backup_system.py, convert2rhel/systeminfo.py, convert2rhel/unit_tests/actions/pre_ponr_changes/backup_system_test.py, convert2rhel/unit_tests/systeminfo_test.py, tests/integration/tier0/non-destructive/basic-sanity-checks/test_basic_sanity_checks.py
Fix rpm -Va parsing to accept also ghosts files. Do not generate message
about invalid output of lines related to ghosts files anymore. Those files
aren't backed up as they are temporary.
Extend rpm -Va command by  --nodeps switch. This improves
speed of the command and doesn't generate unimportant info about
unsatisfied dependencies for packages.
Jira Issues: 
- [RHELC-1427](https://issues.redhat.com/browse/RHELC-1427)
Checklist
=> [RHELC-1427] Fix rpm -Va parsing and improve speed

convert2rhel/actions/pre_ponr_changes/kernel_modules.py, convert2rhel/actions/system_checks/convert2rhel_latest.py, convert2rhel/pkghandler.py, convert2rhel/pkgmanager/__init__.py, convert2rhel/pkgmanager/handlers/dnf/__init__.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/pkgmanager/pkgmanager_test.py
We need to exclude any packages set in the /etc/yum.conf set by the user so we can make sure that when we run repoquery, we are really gathering all the data we want from the command. This patch introduces the overridable --setopt=exclude= in the remaining repoquery calls.
Jira Issues:
- [RHELC-774](https://issues.redhat.com/browse/RHELC-774)
Checklist
=> [RHELC-774] Add exclude setopt to remaining repoquery calls

convert2rhel/main.py
There are two places where we raise the _InhibitorsFound exception, and while this works correctly, we actually are reporting the wrong type of data in one of them. We always assume that the type of data that will be shown to the user is for pre-conversion, but in a further case down the road of conversion, we could also show post conversion results.
This commit patches this bug and tries to correctly show the appropriate result depending on the conversion state.
Jira Issues:
- [RHELC-1684](https://issues.redhat.com/browse/RHELC-1684) 
Checklist
=> [RHELC-1684] Pick correct report results after inhibitors

convert2rhel/actions/conversion/pkg_manager_config.py, convert2rhel/main.py, convert2rhel/redhatrelease.py, convert2rhel/unit_tests/actions/conversion/pkg_manager_config_test.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/redhatrelease_test.py, tests/integration/tier1/destructive/changed-yum-conf/test_patch_yum_conf.py
This PR calls the PkgManagerConf class inside a new action called pkg_manager_config so it can be executed alongside the other actions in the conversion section. Relevant tests have been written.
Jira Issues:
- [RHELC-1332](https://issues.redhat.com/browse/RHELC-1332) 
Checklist
=> [RHELC-1332] Port PkgManagerConf() to the Action framework

convert2rhel/actions/conversion/list_non_red_hat_pkgs_left.py
Without this dependency, the action can run before the package conversion in the system. Ideally, we want this to run after the `KERNEL_PACKAGES_INSTALLATION`, as it is no use to have this run before the package replacement.
Pointed out by @hosekadam in https://github.com/oamg/convert2rhel/pull/1256#discussion_r1718100982
Jira Issues:
-
Checklist
=> Add dependency for non redhat pkgs listing

convert2rhel/actions/post_conversion/modified_rpm_files_diff.py, convert2rhel/actions/post_conversion/remove_tmp_dir.py, convert2rhel/main.py, convert2rhel/unit_tests/actions/post_conversion/modified_rpm_files_diff_test.py, convert2rhel/unit_tests/actions/post_conversion/remove_tmp_dir_test.py, convert2rhel/unit_tests/main_test.py
[RHELC-1336] Port remove_tmp_dir to the Action framework.
Jira Issues:
- [RHELC-1336](https://issues.redhat.com/browse/RHELC-1336)
Checklist
=> [RHELC-1336] Port remove_tmp_dir to the Action framework.

convert2rhel/actions/post_conversion/kernel_boot_files.py, convert2rhel/checks.py, convert2rhel/main.py, convert2rhel/unit_tests/actions/post_conversion/kernel_boot_files_test.py, convert2rhel/unit_tests/checks_test.py, convert2rhel/unit_tests/main_test.py
This PR ports the function check_kernel_boot_files to the action framework. Changing any relevant logger crictical, warning and info messages to Error results and Warning and Info messages respectively.
Jira Issues:
- [RHELC-1337](https://issues.redhat.com/browse/RHELC-1337)
Checklist
=> [RHELC-1337] Port kernel_boot_files to the Action framework

convert2rhel/data/9/x86_64/configs/centos-9-x86_64.cfg, convert2rhel/systeminfo.py, convert2rhel/unit_tests/systeminfo_test.py, tests/integration/common/checks-after-conversion/test_release_version.py
* if the matched regex of the system-release file does not return a minor version (the full_version group lenght is one character only) disregard the minor version completely
* point the target releaseversion to major only, assuming the rhelX/X/ repository namespace mirrors the latest available rhelX/X.Y/ namespace
Jira Issues:
- [RHELC-1650](https://issues.redhat.com/browse/RHELC-1650)
Checklist
=> [RHELC-1650] Disregard minor version with CentOS Stream

convert2rhel/actions/post_conversion/breadcrumbs_finish_collection.py, convert2rhel/main.py, convert2rhel/unit_tests/actions/post_conversion/breadcrumbs_finish_collection_test.py, convert2rhel/unit_tests/main_test.py
Port one of the final steps of conversion to be called by action framework.
Jira Issues:
- [RHELC-1338](https://issues.redhat.com/browse/RHELC-1338)
Checklist
=> [RHELC-1338] Port breadcrumbs.finish_collection to action framework

docs/requirements.txt
Stream 9 has python v3.9 as the latest version in default stream. You
can enable an AppStream to get newer python versions, however that
would involve switching out some of the python specific rpms to their
pip counterparts, which requires more testing
Jira Issues:
-
Checklist
=> fix: lock Sphinx version on CentOS Stream 9

convert2rhel/subscription.py, convert2rhel/unit_tests/subscription_test.py, tests/integration/tier0/non-destructive/els/main.fmf, tests/integration/tier0/non-destructive/els/test_els_enablement.py, tests/integration/tier0/non-destructive/eus/test_eus_enablement.py
In case of repositories not being able to be enabled, we won't fallback to the normal RHSM repoids anymore. Instead, we want to throw an error and tell the user what was the reason on why we couldn't enable the repository.
This simplify the function that handles the enablement, making it much more simpler now.
Jira Issues:
- [RHELC-1554](https://issues.redhat.com/browse/RHELC-1554)
Checklist
=> [RHELC-1554] Remove RHSM repositories enablement fallback

tests/integration/conftest.py
* to test validate the fix from RHELC-1389, drop the automatic installation of python3-syspurpose after every test run
Jira Issues:
- [RHELC-1395](https://issues.redhat.com/browse/RHELC-1395])
Checklist
=> [RHELC-1395] Drop the python3-syspurpose workaround

convert2rhel/checks.py, convert2rhel/grub.py, convert2rhel/main.py, convert2rhel/pkghandler.py, convert2rhel/systeminfo.py, convert2rhel/unit_tests/actions/post_conversion/kernel_boot_files_test.py, convert2rhel/unit_tests/actions/pre_ponr_changes/backup_system_test.py, convert2rhel/unit_tests/actions/system_checks/dbus_test.py, convert2rhel/unit_tests/backup/files_test.py, convert2rhel/unit_tests/grub_test.py, convert2rhel/unit_tests/main_test.py, convert2rhel/unit_tests/pkghandler_test.py, convert2rhel/unit_tests/subscription_test.py, tests/integration/tier0/destructive/single-yum-transaction/install_dependency_packages.py
There were some leftovers imports from the past few merges. This patch is intended to remove them.
Jira Issues:
-
Checklist
=> Remove unused imports from code

convert2rhel/actions/conversion/preserve_only_rhel_kernel.py, convert2rhel/pkghandler.py, convert2rhel/unit_tests/actions/conversion/preserve_only_rhel_kernel_test.py, convert2rhel/unit_tests/pkghandler_test.py, tests/integration/common/checks-after-conversion/main.fmf, tests/integration/common/checks-after-conversion/test_yum_check_update.py
In this PR we try to detect, if a RHEL kernel was installed during the main transaction.
We compare which of the installed kernel packages has a higher version. 
* If the installed RHEL kernel has a higher version than the original vendor kernel, we do not perform any further action and set such kernel as default.
* If there is no non-RHEL kernel detected, we assume that the main transaction handled the whole kernel replacement by itself.
* If the latest available RHEL kernel package is the same version as the currently running non-RHEL kernel, we fall back to the original procedure of trying to install an older version and subsequently updating it.
Jira Issues:
- [RHELC-1672](https://issues.redhat.com/browse/RHELC-1672)
- [RHELC-1708](https://issues.redhat.com/browse/RHELC-1708)
- …
=> [RHELC-1672, RHELC-1707, RHELC-1708] Detect a newer version of RHEL kernel in the main transaction

convert2rhel/unit_tests/utils_test.py, convert2rhel/utils/__init__.py
As pointed out by QE, we forgot to override the exclude option during yumdownloader calls. This patch is fixing the command to also ignore it during the yumdownloader.
Jira Issues:
- [RHELC-774](https://issues.redhat.com/browse/RHELC-774)
Checklist
=> [RHELC-774] Override exclude option during yumdownloader call

convert2rhel/__init__.py, packaging/convert2rhel.spec
* [RHELC-1434] Use public CDN instead of paywalled CDN and FTP by @bocekm in https://github.com/oamg/convert2rhel/pull/1123
* [RHELC-1600] Remove RuntimeWarning caused by bufsize value of run_subprocess by @pr-watson in https://github.com/oamg/convert2rhel/pull/1313
* [RHELC-1334] Port ModifiedRPMFilesDiff to Action framework by @hosekadam in https://github.com/oamg/convert2rhel/pull/1266
* [RHELC-1329] Port preserve_only_rhel_kernel to Action framework by @pr-watson in https://github.com/oamg/convert2rhel/pull/1250
* [RHELC-1673] Include all reports in post-conversion report by @hosekadam in https://github.com/oamg/convert2rhel/pull/1336
* [RHELC-1330] Port list_non_red_hat_pkgs_left to Action framework by @jochapma in https://github.com/oamg/convert2rhel/pull/1292
* [RHELC-1331] Port …
=> Bump to version 2.1.0

convert2rhel/actions/conversion/preserve_only_rhel_kernel.py, convert2rhel/unit_tests/actions/conversion/preserve_only_rhel_kernel_test.py, tests/integration/common/checks-after-conversion/main.fmf
* when there is just the kernel-core package on the system and the meta kernel package is removed, the yum call to install kernel actually installs the meta-package and leaves already_installed variable unmatched
Jira Issues:
- [RHELC-1672](https://issues.redhat.com/browse/RHELC-1672) 
Checklist
=> [RHELC-1672] Fix edge case of kernel meta package not the on system

convert2rhel/actions/conversion/preserve_only_rhel_kernel.py, convert2rhel/unit_tests/actions/conversion/preserve_only_rhel_kernel_test.py
Info message about conflicting kerne from InstallRhelKernell was removed because it can be confusing for users to see this in the post-conversion report. The conflict was already solved in next action steps.
Jira Issues:
-
Checklist
=> Remove info message from InstallRhelKernel

tests/ansible_collections/roles/get-test-vars/tasks/get-test-vars.yml, tests/integration/conftest.py, tests/integration/tier0/destructive/conversion-method/test_one_key_satellite.py, tests/integration/tier0/destructive/conversion-method/test_satellite.py, tests/integration/tier0/destructive/isolated-system-conversion/prepare_system.py, tests/integration/tier0/non-destructive/enabled-repositories-after-analysis/test_enabled_repositories_after_analysis.py, tests/integration/tier0/non-destructive/system-release-backup/test_system_release_backup.py
Refactor Satellite usage in integration tests. Part of the `conftest.py` refactor
Jira Issues:
- https://issues.redhat.com/browse/RHELC-1712
- https://issues.redhat.com/browse/RHELC-1620
Checklist
=> [RHELC-1712] Conftest refactor - satellite 

tests/integration/tier0/non-destructive/config-file/main.fmf, tests/integration/tier0/non-destructive/config-file/test_config_file.py
Updating the user_path_cli_priority int tests to test for the changes done in #1208.
The test had a small refactor to make it easier to read assert for multiple strings at once. Also removed the interrupt at the beginning to let the tool to process the changes.
Jira Issues:
- [RHELC-1543](https://issues.redhat.com/browse/RHELC-1543)
Checklist
=> [RHELC-1543] Update integrations tests for overridable config

tests/integration/conftest.py
* pytest.skip was called, so the whole tests got skipped if conditions matched
=> hotfix/Fix backup_directory test fixture

tests/integration/conftest.py, tests/integration/tier1/destructive/proxy-conversion/test_proxy_conversion.py
Since September 3rd the location of the GPG Key has changed. This patch is to introduce the new URL in order to keep the tests working consistenly in the future.
Jira Issues:
-
Checklist
=> Update Red Hat GPG Key URL to new location

tests/integration/conftest.py, tests/integration/tier0/destructive/conversion-method/main.fmf, tests/integration/tier0/non-destructive/els/test_els_enablement.py, tests/integration/tier0/non-destructive/kernel-modules/test_unsupported_kmod.py, tests/integration/tier0/non-destructive/kernel/test_custom_kernel.py, tests/integration/tier0/non-destructive/modified-releasever/test_modified_releasever.py
Remove unnecessary code from conftest.py (part2)
Do NOT merge before https://github.com/oamg/convert2rhel/pull/1349
Jira Issues:
- [RHELC-1715](https://issues.redhat.com/browse/RHELC-1715) 
- [RHELC-1620]( https://issues.redhat.com/browse/RHELC-1620)
- [RHELC-1134](https://issues.redhat.com/browse/RHELC-1134)
Checklist
=> [RHELC-1715, RHELC-1134] conftest.py refactor - remove unnecessary code

convert2rhel/actions/system_checks/duplicate_packages.py, convert2rhel/unit_tests/actions/system_checks/duplicate_packages_test.py
This PR modifies the condition to handle duplicate package error results to also work when run on an el9 system. New unit tests have been added for the el9 scenarios. 
Jira Issues:
- [RHELC-1675](https://issues.redhat.com/browse/RHELC-1675)
Checklist
=> [RHELC-1675] Add handling for rhel9 systems in duplicate package check

plans/tier1.fmf, tests/integration/conftest.py, tests/integration/tier0/destructive/conversion-method/test_custom_repos.py, tests/integration/tier0/destructive/conversion-method/test_rhsm_eus.py, tests/integration/tier0/non-destructive/custom-repository/test_custom_repository.py, tests/integration/tier1/destructive/kernel-check-skip/test_latest_kernel_check_skip.py
Refactor how we use the custom repositories in `conftest.py`. 
Jira Issues:
- [RHELC-1687](https://issues.redhat.com/browse/RHELC-1687)
- [RHELC-1620](https://issues.redhat.com/browse/RHELC-1620)
Checklist
=> [RHELC-1687] - conftest.py refactor - custom repos

.github/renovate.json
We need to hardcode Sphinx atm due to issues with py3.9 being dropped
for the packages and we haven't setup the container with it yet
=> chore: set Renovate to ignore Sphinx deps

.github/renovate.json
Previous attempt didn't work, likely we need to add the files to ignore dependencies in for it to successfully ignore them.
=> chore(Renovate): ignore deps from specific files

convert2rhel/actions/system_checks/grub_validity.py, convert2rhel/unit_tests/actions/system_checks/grub_validity_test.py
This PR adds a preconversion analysis check that runs `grub2-mkconfig` to determine if the systems grub file is valid. If a non-zero return code is found then we raise an error telling the customer that their grub file is misconfigured and they need to fix it before rerunning the conversion. 
Jira Issues:
- [RHELC-1601](https://issues.redhat.com/browse/RHELC-1601)
Checklist
=> [RHELC-1601] Add preconversion check for invalid grub file

Makefile, requirements/centos7.requirements.txt, requirements/centos8.requirements.txt, requirements/centos9.requirements.txt
This adds concurrent pytest runs through pytest-xdist and automatically
decides how many processes it can start. Overall speeding up the tests
to around the slowest test to execute at the moment rather than having
to wait 10x that amount
Ref: https://pytest-xdist.readthedocs.io/en/stable/distribution.html
Note: the latest release of pytest-xdist that supports py27 is 1.34.0
Jira Issues:
-
Checklist
=> chore: add concurrent pytest runs

.github/workflows/build_images.yml
We used to use :latest tags like this
- ghcr.io/oamg/convert2rhel-centos7:latest
- ghcr.io/oamg/convert2rhel-centos8:latest
- ghcr.io/oamg/convert2rhel-centos9:latest
but now we unify them with
- ghcr.io/oamg/convert2rhel-centos:7
- ghcr.io/oamg/convert2rhel-centos:8
- ghcr.io/oamg/convert2rhel-centos:9
Jira Issues:
-
Checklist
=> chore: Update image builds with new tags

.packit.yaml, convert2rhel/data/9/x86_64/configs/centos-9-x86_64.cfg, plans/main.fmf, plans/stream.fmf, tests/integration/common/checks-after-conversion/main.fmf, tests/integration/common/checks-after-conversion/test_release_version.py, tests/integration/tier0/destructive/single-yum-transaction/test_single_yum_transaction.py, tests/integration/tier0/destructive/yum-distro-sync/add-extras-repo/main.yml, tests/integration/tier0/non-destructive/basic-sanity-checks/test_basic_sanity_checks.py, tests/integration/tier0/non-destructive/kernel-modules/main.fmf, tests/integration/tier0/non-destructive/modified-releasever/test_modified_releasever.py, tests/integration/tier0/non-destructive/rollback-handling/test_rollback_handling.py
* Include CentOS Stream 9 in the integration tests coverage
Jira Issues:
- [RHELC-1615](https://issues.redhat.com/browse/RHELC-1615)
Checklist
=> [RHELC-1615] CentOS Stream 9 test coverage

plans/tier1.fmf, tests/integration/tier0/destructive/conversion-method/test_config_file.py, tests/integration/tier1/destructive/error-after-ponr/main.fmf, tests/integration/tier1/destructive/error-after-ponr/test_error_after_ponr.py
Implement a new integration test to verify the log message when a fail occurs after PONR
Jira Issues:
- [RHELC-788](https://issues.redhat.com/browse/RHELC-788)
Checklist
=> [RHELC-788] Implement integration test error after ponr

.github/CODEOWNERS
This changes the owners around a bit, could possibly be removed for some
parts instead of reduced
=> chore: update CODEOWNERS to reflect latest status

convert2rhel/actions/post_conversion/hostmetering.py, convert2rhel/actions/pre_ponr_changes/backup_system.py, convert2rhel/actions/pre_ponr_changes/kernel_modules.py, convert2rhel/actions/system_checks/convert2rhel_latest.py, convert2rhel/actions/system_checks/is_loaded_kernel_latest.py, convert2rhel/actions/system_checks/package_updates.py, convert2rhel/actions/system_checks/tainted_kmods.py, convert2rhel/toolopts/__init__.py, convert2rhel/utils/__init__.py
With the most recent work to migrate all environment variables to the configuration file, we need now to warn the user that the variables will be deprecated in order to use configuration file as our main place to track configuarations.
This patch is introducing a very lightweight change to make sure that we will be able modify the code in the future to remove all environment variables.
Jira Issues:
- [RHELC-1508](https://issues.redhat.com/browse/RHELC-1508-)
Checklist
=> [RHELC-1508] Add deprecation notice about environment variables

convert2rhel/actions/pre_ponr_changes/handle_packages.py, convert2rhel/unit_tests/actions/pre_ponr_changes/handle_packages_test.py, tests/integration/tier0/non-destructive/system-release-backup/test_system_release_backup.py
Some packages (e.g. rocky-release or alma-release on EL9) can remove repository directory as their part. Without the directory, sub-man is unable to generate redhat.repo file. This results in inaccessibility of all rhel repositories.
Jira Issues:
- [RHELC-1677](https://issues.redhat.com/browse/RHELC-1677)
Checklist
=> [RHELC-1677] Fix missing repository directory

convert2rhel/actions/system_checks/convert2rhel_latest.py, convert2rhel/repo.py
This PR adds the new CDN repo for publishing convert2rhel on EL9. A correction to the diagnosis field in one of the repo.py results was also made. 
Jira Issues:
- [RHELC-1598](https://issues.redhat.com/browse/RHELC-1598)
Checklist
=> [RHELC-1598] Add EL9 repofile url to convert2rhel latest check

.github/workflows/build-rpm.yml, Makefile
This prevents building images for RPMs and instead makes sure we get from the registry. This also improves the versioning change based on the tag so it is more straight-forward
=> chore: RPM build workflow to fetch correct tags

.github/workflows/build-rpm.yml
There was issues relating to file permissions when it came to building RPM files. I've changed it around so it now only uploads the artifact files that were modified, so we always checkout the repo but keep the modified files when we build a release
=> chore: workflow to upload only modified files

plans/tier0.fmf, plans/tier1.fmf
* CentOS Stream has a separate plan, disable the original plans for both Stream 8 and 9
=> chore:Disable the tier0 a and tier1 plans for Stream 9

convert2rhel/breadcrumbs.py, convert2rhel/unit_tests/breadcrumbs_test.py
This PR adds the `non_default_channel` to our rhsm custom facts so we can properly record metrics on the use of EUS/ELS during conversions. 
Jira Issues:
-  [RHELC-1725](https://issues.redhat.com/browse/RHELC-1725)
Checklist
=> [RHELC-1725] Update rhsm custom facts

.github/renovate.json, .github/workflows/build-rpm.yml, .github/workflows/jira-links.yml
Auto tag workflow didn't trigger a follow-up RPM build and attach to the
tag which means no tags get the rpms attached. This defeats the point of
our autotagging as we want to have RPMs to test against.
Jira Issues:
-
Checklist
=> chore(workflows): Autotag to upload rpms

convert2rhel/checks.py, convert2rhel/unit_tests/checks_test.py, plans/tier1.fmf
* Except the UnicodeDecodeError exception when the initramfs file is badly miscofigured
Jira Issues:
- [RHELC-1711](https://issues.redhat.com/browse/RHELC-1711)
Checklist
=> [RHELC-1711] Except UnicodeDecodeError when parsing initramfs

convert2rhel/main.py, convert2rhel/unit_tests/main_test.py, tests/integration/tier0/non-destructive/assessment-report/test_assessment_report.py, tests/integration/tier0/non-destructive/basic-sanity-checks/main.fmf, tests/integration/tier0/non-destructive/duplicate-pkgs/test_duplicate_pkgs.py, tests/integration/tier0/non-destructive/els/test_els_enablement.py, tests/integration/tier0/non-destructive/eus/test_eus_enablement.py, tests/integration/tier0/non-destructive/file-backup/test_file_backup.py, tests/integration/tier0/non-destructive/grub/test_invalid_changed_to_grub.py, tests/integration/tier0/non-destructive/modified-releasever/test_modified_releasever.py, tests/integration/tier0/non-destructive/rollback-handling/test_rollback_handling.py, tests/integration/tier0/non-destructive/system-release-backup/main.fmf, tests/integration/tier1/non-destructive/httpd-package-transaction-error/test_httpd_package_transaction_error.py
The convert2rhel finished with different exit codes when inhibitor was found and different subcommands were used.
In the code was missing part for handling the inhibitors during analysis exit.
Jira Issues:
- [RHELC-1736](https://issues.redhat.com/browse/RHELC-1736)
Checklist
=> [RHELC-1736] Fix different exit codes

config/convert2rhel.ini, convert2rhel/actions/system_checks/package_updates.py, convert2rhel/toolopts/config.py, convert2rhel/unit_tests/actions/system_checks/package_updates_test.py, convert2rhel/unit_tests/toolopts/config_test.py, plans/tier1.fmf, tests/integration/tier1/destructive/system-not-up-to-date/main.fmf, tests/integration/tier1/destructive/system-not-up-to-date/test_system_not_up_to_date.py
This PR changes the overridable inhibitor result `OUT_OF_DATE_PACKAGES` to a warning. Relevant unit tests have been updated.
Jira Issues:
- [RHELC-1578](https://issues.redhat.com/browse/RHELC-1578)
Checklist
=> [RHELC-1578] Change out of date packages overridable inhibitor to warning

.github/workflows/autotag.yml, .github/workflows/build-rpm.yml
This should hopefully tag and have all the variables accessible without issue.
Jira Issues:
-
Checklist
=> chore: Improve autotag and build rpm again

convert2rhel/actions/conversion/list_non_red_hat_pkgs_left.py, convert2rhel/actions/conversion/preserve_only_rhel_kernel.py, convert2rhel/pkghandler.py, convert2rhel/unit_tests/actions/conversion/preserve_only_rhel_kernel_test.py, tests/integration/common/checks-after-conversion/main.fmf
* simplify the kernel (re-)installation 
* check if any RHEL kernel got installed during the main transaction, if not, handle the same version conflict
* try to update the installed kernel in every case
Jira Issues:
- [RHELC-1717](https://issues.redhat.com/browse/RHELC-1717)
Checklist
=> [RHELC-1717] Fix the latest RHEL kernel not being set as default when converting from CentOS Stream 9

tests/integration/common/checks-after-conversion/test_verify_strings_in_log.py, tests/integration/conftest.py, tests/integration/test_helpers/checks_nondestructive.py, tests/integration/test_helpers/common_functions.py, tests/integration/tier0/non-destructive/basic-sanity-checks/main.fmf, tests/integration/tier0/non-destructive/kernel-modules/main.fmf, tests/integration/tier0/non-destructive/single-yum-transaction-validation/main.fmf, tests/integration/tier0/non-destructive/single-yum-transaction-validation/test_single_yum_transaction_validation.py, tests/integration/tier1/destructive/system-not-up-to-date/test_system_not_up_to_date.py
Jira Issues:
- [RHELC-1536](https://issues.redhat.com/browse/RHELC-1536)
Checklist
=> [RHELC-1536] Add check to verify deprecated envar message

convert2rhel/actions/post_conversion/hostmetering.py, convert2rhel/actions/pre_ponr_changes/backup_system.py, convert2rhel/actions/pre_ponr_changes/kernel_modules.py, convert2rhel/actions/system_checks/convert2rhel_latest.py, convert2rhel/actions/system_checks/is_loaded_kernel_latest.py, convert2rhel/actions/system_checks/tainted_kmods.py, convert2rhel/cli.py, convert2rhel/toolopts/__init__.py, convert2rhel/unit_tests/actions/post_conversion/hostmetering_test.py, convert2rhel/unit_tests/actions/pre_ponr_changes/backup_system_test.py, convert2rhel/unit_tests/actions/pre_ponr_changes/kernel_modules_test.py, convert2rhel/unit_tests/actions/system_checks/convert2rhel_latest_test.py, convert2rhel/unit_tests/actions/system_checks/is_loaded_kernel_latest_test.py, convert2rhel/unit_tests/actions/system_checks/tainted_kmods_test.py, convert2rhel/unit_tests/cli_test.py, convert2rhel/unit_tests/toolopts/toolopts_test.py, convert2rhel/unit_tests/utils/utils_test.py, convert2rhel/utils/__init__.py, tests/integration/tier0/non-destructive/basic-sanity-checks/test_basic_sanity_checks.py, tests/integration/tier0/non-destructive/kernel-modules/test_unsupported_kmod.py, tests/integration/tier0/non-destructive/system-release-backup/test_system_release_backup.py, tests/integration/tier1/destructive/kernel-check-skip/test_latest_kernel_check_skip.py
Env vars have been deprecated in favor of the ini config file (e.g. /etc/convert2rhel.ini). We should be telling users to use the config file instead of the deprecated env vars.
Jira Issues:
- [RHELC-1511](https://issues.redhat.com/browse/RHELC-1511)
Checklist
=> [RHELC-1511] Tell users to use config ini instead of env vars

convert2rhel/main.py, convert2rhel/pkghandler.py, convert2rhel/subscription.py, convert2rhel/unit_tests/subscription_test.py, tests/integration/tier0/non-destructive/basic-sanity-checks/test_basic_sanity_checks.py
When an exception gets raised early before have a chance to install sub-man (for instance when any of the packages installed on the systems are not of the latest version available), convert2rhel hard stops with a traceback when trying to call sub-man which hasn't been installed.
Jira Issues:
- [RHELC-1728](https://issues.redhat.com/browse/RHELC-1728)
Checklist
=> [RHELC-1728] Don't update RHSM facts without sub-man installed

.packit.yaml
Jira Issues:
- [RHELC-1716](https://issues.redhat.com/browse/RHELC-1716)
Checklist
=> [RHELC-1716] Introduce finer granularity with packit test labels

convert2rhel/actions/pre_ponr_changes/handle_packages.py, convert2rhel/actions/system_checks/is_loaded_kernel_latest.py, convert2rhel/backup/packages.py, convert2rhel/pkghandler.py, convert2rhel/pkgmanager/__init__.py, convert2rhel/repo.py, convert2rhel/unit_tests/repo_test.py, tests/integration/tier0/non-destructive/custom-repository/test_custom_repository.py
Avoid reaching unaccessible repositories provided by user using
--enablerepo argument. Those repos are manually disabled during
analysis, but when user provides unreachable repo the analysis would
fail.
This change adds check if provided repos are accessible - if not, those
unaccessible ones are removed from the list for manual disable during
analysis.
Jira Issues:
- [RHELC-1753](https://issues.redhat.com/browse/RHELC-1753)
Checklist
=> [RHELC-1753] Fix reaching unaccessible repos from enablerepo 

convert2rhel/__init__.py, packaging/convert2rhel.spec
* [RHELC-961] Rename GPG fingerprint to key_id by @r0x0d in https://github.com/oamg/convert2rhel/pull/1280
* [RHELC-1507] Port environment variables to config file by @r0x0d in https://github.com/oamg/convert2rhel/pull/1272
* [RHELC-1601] Add pre-conversion check for invalid grub file by @pr-watson in https://github.com/oamg/convert2rhel/pull/1368
* [RHELC-1508] Add deprecation notice about environment variables by @r0x0d in https://github.com/oamg/convert2rhel/pull/1386
* [RHELC-1598] Enable checking for EL9 convert2rhel latest version by @pr-watson in https://github.com/oamg/convert2rhel/pull/1397
* [RHELC-1725] Include EUS/ELS switches in breadcrumbs by @pr-watson in https://github.com/oamg/convert2rhel/pull/1395
* [RHELC-1169]  Advise users to back up their system by @Andrew-ang9 in …
=> Bump version to 2.2.0

plans/tier1.fmf, tests/integration/tier1/destructive/host-metering/main.fmf, tests/integration/tier1/destructive/host-metering/test_run_conversion_with_metering.py
* modify one of the tests to validate the functionality
Jira Issues:
- [RHELC-1535](https://issues.redhat.com/browse/RHELC-1535)
Checklist
=> [RHELC-1535] Test set envar through config

convert2rhel/actions/__init__.py, tests/integration/tier0/non-destructive/assessment-report/test_assessment_report.py
I was not sure what "No changes needed" means (changes to do by the tool or myself?).
IMHO "No action required" is clearer.
Jira Issues:
- [RHELC-1760](https://issues.redhat.com/browse/RHELC-1760)
Checklist
=> [RHELC-1760] Make post-conversion analysis summary clearer

convert2rhel/actions/system_checks/convert2rhel_latest.py
The tool version check iterates over all the versions available in the convert2rhel repository. 
While doing so, it provides unnecessary information in the debug messages.
Remove the debug messages to keep the output less polluted.
Jira Issues:
- [RHELC-1682](https://issues.redhat.com/browse/RHELC-1682)
Checklist
=> [RHELC-1682] Remove debug messages when comparing c2r versions

.packit.yaml
* Oracle Linux 7.9 image we used for testing got removed from AWS, disable the pipelines until a new image is available
Jira Issues:
-
Checklist
=> Disable Oracle Linux 7.9 test pipelines

.github/workflows/generate_manpage.yml
The version 3.13.3 of Python is not available in the Ubuntu 22.04
=> Update Python version in manpage workflow to 3.13

.gitignore
To not bother devs with git reporting an unstaged file when using the VS Code IDE.
=> Add VS Code workspace file to .gitignore
